// Code generated by ent, DO NOT EDIT.

package intercept

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"github.com/nidao003/mclaw/backend/db"
	"github.com/nidao003/mclaw/backend/db/audit"
	"github.com/nidao003/mclaw/backend/db/checkin"
	"github.com/nidao003/mclaw/backend/db/dataapipricing"
	"github.com/nidao003/mclaw/backend/db/exchangecode"
	"github.com/nidao003/mclaw/backend/db/expert"
	"github.com/nidao003/mclaw/backend/db/gitbot"
	"github.com/nidao003/mclaw/backend/db/gitbottask"
	"github.com/nidao003/mclaw/backend/db/gitbotuser"
	"github.com/nidao003/mclaw/backend/db/gitidentity"
	"github.com/nidao003/mclaw/backend/db/gittask"
	"github.com/nidao003/mclaw/backend/db/host"
	"github.com/nidao003/mclaw/backend/db/image"
	"github.com/nidao003/mclaw/backend/db/invitation"
	"github.com/nidao003/mclaw/backend/db/mcptool"
	"github.com/nidao003/mclaw/backend/db/mcpupstream"
	"github.com/nidao003/mclaw/backend/db/mcpusertoolsetting"
	"github.com/nidao003/mclaw/backend/db/model"
	"github.com/nidao003/mclaw/backend/db/modelapikey"
	"github.com/nidao003/mclaw/backend/db/modelpricing"
	"github.com/nidao003/mclaw/backend/db/notifychannel"
	"github.com/nidao003/mclaw/backend/db/notifysendlog"
	"github.com/nidao003/mclaw/backend/db/notifysubscription"
	"github.com/nidao003/mclaw/backend/db/paymentorder"
	"github.com/nidao003/mclaw/backend/db/plan"
	"github.com/nidao003/mclaw/backend/db/predicate"
	"github.com/nidao003/mclaw/backend/db/project"
	"github.com/nidao003/mclaw/backend/db/projectcollaborator"
	"github.com/nidao003/mclaw/backend/db/projectgitbot"
	"github.com/nidao003/mclaw/backend/db/projectissue"
	"github.com/nidao003/mclaw/backend/db/projectissuecomment"
	"github.com/nidao003/mclaw/backend/db/projecttask"
	"github.com/nidao003/mclaw/backend/db/skill"
	"github.com/nidao003/mclaw/backend/db/skillrating"
	"github.com/nidao003/mclaw/backend/db/skillreview"
	"github.com/nidao003/mclaw/backend/db/skillversion"
	"github.com/nidao003/mclaw/backend/db/task"
	"github.com/nidao003/mclaw/backend/db/taskmodelswitch"
	"github.com/nidao003/mclaw/backend/db/taskusagestat"
	"github.com/nidao003/mclaw/backend/db/taskvirtualmachine"
	"github.com/nidao003/mclaw/backend/db/team"
	"github.com/nidao003/mclaw/backend/db/teamgroup"
	"github.com/nidao003/mclaw/backend/db/teamgrouphost"
	"github.com/nidao003/mclaw/backend/db/teamgroupimage"
	"github.com/nidao003/mclaw/backend/db/teamgroupmember"
	"github.com/nidao003/mclaw/backend/db/teamgroupmodel"
	"github.com/nidao003/mclaw/backend/db/teamhost"
	"github.com/nidao003/mclaw/backend/db/teamimage"
	"github.com/nidao003/mclaw/backend/db/teammember"
	"github.com/nidao003/mclaw/backend/db/teammodel"
	"github.com/nidao003/mclaw/backend/db/transactionlog"
	"github.com/nidao003/mclaw/backend/db/user"
	"github.com/nidao003/mclaw/backend/db/userapikey"
	"github.com/nidao003/mclaw/backend/db/useridentity"
	"github.com/nidao003/mclaw/backend/db/usersubscription"
	"github.com/nidao003/mclaw/backend/db/virtualmachine"
	"github.com/nidao003/mclaw/backend/db/wallet"
)

// The Query interface represents an operation that queries a graph.
// By using this interface, users can write generic code that manipulates
// query builders of different types.
type Query interface {
	// Type returns the string representation of the query type.
	Type() string
	// Limit the number of records to be returned by this query.
	Limit(int)
	// Offset to start from.
	Offset(int)
	// Unique configures the query builder to filter duplicate records.
	Unique(bool)
	// Order specifies how the records should be ordered.
	Order(...func(*sql.Selector))
	// WhereP appends storage-level predicates to the query builder. Using this method, users
	// can use type-assertion to append predicates that do not depend on any generated package.
	WhereP(...func(*sql.Selector))
}

// The Func type is an adapter that allows ordinary functions to be used as interceptors.
// Unlike traversal functions, interceptors are skipped during graph traversals. Note that the
// implementation of Func is different from the one defined in entgo.io/ent.InterceptFunc.
type Func func(context.Context, Query) error

// Intercept calls f(ctx, q) and then applied the next Querier.
func (f Func) Intercept(next db.Querier) db.Querier {
	return db.QuerierFunc(func(ctx context.Context, q db.Query) (db.Value, error) {
		query, err := NewQuery(q)
		if err != nil {
			return nil, err
		}
		if err := f(ctx, query); err != nil {
			return nil, err
		}
		return next.Query(ctx, q)
	})
}

// The TraverseFunc type is an adapter to allow the use of ordinary function as Traverser.
// If f is a function with the appropriate signature, TraverseFunc(f) is a Traverser that calls f.
type TraverseFunc func(context.Context, Query) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseFunc) Intercept(next db.Querier) db.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseFunc) Traverse(ctx context.Context, q db.Query) error {
	query, err := NewQuery(q)
	if err != nil {
		return err
	}
	return f(ctx, query)
}

// The AuditFunc type is an adapter to allow the use of ordinary function as a Querier.
type AuditFunc func(context.Context, *db.AuditQuery) (db.Value, error)

// Query calls f(ctx, q).
func (f AuditFunc) Query(ctx context.Context, q db.Query) (db.Value, error) {
	if q, ok := q.(*db.AuditQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *db.AuditQuery", q)
}

// The TraverseAudit type is an adapter to allow the use of ordinary function as Traverser.
type TraverseAudit func(context.Context, *db.AuditQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseAudit) Intercept(next db.Querier) db.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseAudit) Traverse(ctx context.Context, q db.Query) error {
	if q, ok := q.(*db.AuditQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *db.AuditQuery", q)
}

// The CheckInFunc type is an adapter to allow the use of ordinary function as a Querier.
type CheckInFunc func(context.Context, *db.CheckInQuery) (db.Value, error)

// Query calls f(ctx, q).
func (f CheckInFunc) Query(ctx context.Context, q db.Query) (db.Value, error) {
	if q, ok := q.(*db.CheckInQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *db.CheckInQuery", q)
}

// The TraverseCheckIn type is an adapter to allow the use of ordinary function as Traverser.
type TraverseCheckIn func(context.Context, *db.CheckInQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseCheckIn) Intercept(next db.Querier) db.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseCheckIn) Traverse(ctx context.Context, q db.Query) error {
	if q, ok := q.(*db.CheckInQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *db.CheckInQuery", q)
}

// The DataApiPricingFunc type is an adapter to allow the use of ordinary function as a Querier.
type DataApiPricingFunc func(context.Context, *db.DataApiPricingQuery) (db.Value, error)

// Query calls f(ctx, q).
func (f DataApiPricingFunc) Query(ctx context.Context, q db.Query) (db.Value, error) {
	if q, ok := q.(*db.DataApiPricingQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *db.DataApiPricingQuery", q)
}

// The TraverseDataApiPricing type is an adapter to allow the use of ordinary function as Traverser.
type TraverseDataApiPricing func(context.Context, *db.DataApiPricingQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseDataApiPricing) Intercept(next db.Querier) db.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseDataApiPricing) Traverse(ctx context.Context, q db.Query) error {
	if q, ok := q.(*db.DataApiPricingQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *db.DataApiPricingQuery", q)
}

// The ExchangeCodeFunc type is an adapter to allow the use of ordinary function as a Querier.
type ExchangeCodeFunc func(context.Context, *db.ExchangeCodeQuery) (db.Value, error)

// Query calls f(ctx, q).
func (f ExchangeCodeFunc) Query(ctx context.Context, q db.Query) (db.Value, error) {
	if q, ok := q.(*db.ExchangeCodeQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *db.ExchangeCodeQuery", q)
}

// The TraverseExchangeCode type is an adapter to allow the use of ordinary function as Traverser.
type TraverseExchangeCode func(context.Context, *db.ExchangeCodeQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseExchangeCode) Intercept(next db.Querier) db.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseExchangeCode) Traverse(ctx context.Context, q db.Query) error {
	if q, ok := q.(*db.ExchangeCodeQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *db.ExchangeCodeQuery", q)
}

// The ExpertFunc type is an adapter to allow the use of ordinary function as a Querier.
type ExpertFunc func(context.Context, *db.ExpertQuery) (db.Value, error)

// Query calls f(ctx, q).
func (f ExpertFunc) Query(ctx context.Context, q db.Query) (db.Value, error) {
	if q, ok := q.(*db.ExpertQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *db.ExpertQuery", q)
}

// The TraverseExpert type is an adapter to allow the use of ordinary function as Traverser.
type TraverseExpert func(context.Context, *db.ExpertQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseExpert) Intercept(next db.Querier) db.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseExpert) Traverse(ctx context.Context, q db.Query) error {
	if q, ok := q.(*db.ExpertQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *db.ExpertQuery", q)
}

// The GitBotFunc type is an adapter to allow the use of ordinary function as a Querier.
type GitBotFunc func(context.Context, *db.GitBotQuery) (db.Value, error)

// Query calls f(ctx, q).
func (f GitBotFunc) Query(ctx context.Context, q db.Query) (db.Value, error) {
	if q, ok := q.(*db.GitBotQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *db.GitBotQuery", q)
}

// The TraverseGitBot type is an adapter to allow the use of ordinary function as Traverser.
type TraverseGitBot func(context.Context, *db.GitBotQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseGitBot) Intercept(next db.Querier) db.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseGitBot) Traverse(ctx context.Context, q db.Query) error {
	if q, ok := q.(*db.GitBotQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *db.GitBotQuery", q)
}

// The GitBotTaskFunc type is an adapter to allow the use of ordinary function as a Querier.
type GitBotTaskFunc func(context.Context, *db.GitBotTaskQuery) (db.Value, error)

// Query calls f(ctx, q).
func (f GitBotTaskFunc) Query(ctx context.Context, q db.Query) (db.Value, error) {
	if q, ok := q.(*db.GitBotTaskQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *db.GitBotTaskQuery", q)
}

// The TraverseGitBotTask type is an adapter to allow the use of ordinary function as Traverser.
type TraverseGitBotTask func(context.Context, *db.GitBotTaskQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseGitBotTask) Intercept(next db.Querier) db.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseGitBotTask) Traverse(ctx context.Context, q db.Query) error {
	if q, ok := q.(*db.GitBotTaskQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *db.GitBotTaskQuery", q)
}

// The GitBotUserFunc type is an adapter to allow the use of ordinary function as a Querier.
type GitBotUserFunc func(context.Context, *db.GitBotUserQuery) (db.Value, error)

// Query calls f(ctx, q).
func (f GitBotUserFunc) Query(ctx context.Context, q db.Query) (db.Value, error) {
	if q, ok := q.(*db.GitBotUserQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *db.GitBotUserQuery", q)
}

// The TraverseGitBotUser type is an adapter to allow the use of ordinary function as Traverser.
type TraverseGitBotUser func(context.Context, *db.GitBotUserQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseGitBotUser) Intercept(next db.Querier) db.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseGitBotUser) Traverse(ctx context.Context, q db.Query) error {
	if q, ok := q.(*db.GitBotUserQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *db.GitBotUserQuery", q)
}

// The GitIdentityFunc type is an adapter to allow the use of ordinary function as a Querier.
type GitIdentityFunc func(context.Context, *db.GitIdentityQuery) (db.Value, error)

// Query calls f(ctx, q).
func (f GitIdentityFunc) Query(ctx context.Context, q db.Query) (db.Value, error) {
	if q, ok := q.(*db.GitIdentityQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *db.GitIdentityQuery", q)
}

// The TraverseGitIdentity type is an adapter to allow the use of ordinary function as Traverser.
type TraverseGitIdentity func(context.Context, *db.GitIdentityQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseGitIdentity) Intercept(next db.Querier) db.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseGitIdentity) Traverse(ctx context.Context, q db.Query) error {
	if q, ok := q.(*db.GitIdentityQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *db.GitIdentityQuery", q)
}

// The GitTaskFunc type is an adapter to allow the use of ordinary function as a Querier.
type GitTaskFunc func(context.Context, *db.GitTaskQuery) (db.Value, error)

// Query calls f(ctx, q).
func (f GitTaskFunc) Query(ctx context.Context, q db.Query) (db.Value, error) {
	if q, ok := q.(*db.GitTaskQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *db.GitTaskQuery", q)
}

// The TraverseGitTask type is an adapter to allow the use of ordinary function as Traverser.
type TraverseGitTask func(context.Context, *db.GitTaskQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseGitTask) Intercept(next db.Querier) db.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseGitTask) Traverse(ctx context.Context, q db.Query) error {
	if q, ok := q.(*db.GitTaskQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *db.GitTaskQuery", q)
}

// The HostFunc type is an adapter to allow the use of ordinary function as a Querier.
type HostFunc func(context.Context, *db.HostQuery) (db.Value, error)

// Query calls f(ctx, q).
func (f HostFunc) Query(ctx context.Context, q db.Query) (db.Value, error) {
	if q, ok := q.(*db.HostQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *db.HostQuery", q)
}

// The TraverseHost type is an adapter to allow the use of ordinary function as Traverser.
type TraverseHost func(context.Context, *db.HostQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseHost) Intercept(next db.Querier) db.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseHost) Traverse(ctx context.Context, q db.Query) error {
	if q, ok := q.(*db.HostQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *db.HostQuery", q)
}

// The ImageFunc type is an adapter to allow the use of ordinary function as a Querier.
type ImageFunc func(context.Context, *db.ImageQuery) (db.Value, error)

// Query calls f(ctx, q).
func (f ImageFunc) Query(ctx context.Context, q db.Query) (db.Value, error) {
	if q, ok := q.(*db.ImageQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *db.ImageQuery", q)
}

// The TraverseImage type is an adapter to allow the use of ordinary function as Traverser.
type TraverseImage func(context.Context, *db.ImageQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseImage) Intercept(next db.Querier) db.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseImage) Traverse(ctx context.Context, q db.Query) error {
	if q, ok := q.(*db.ImageQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *db.ImageQuery", q)
}

// The InvitationFunc type is an adapter to allow the use of ordinary function as a Querier.
type InvitationFunc func(context.Context, *db.InvitationQuery) (db.Value, error)

// Query calls f(ctx, q).
func (f InvitationFunc) Query(ctx context.Context, q db.Query) (db.Value, error) {
	if q, ok := q.(*db.InvitationQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *db.InvitationQuery", q)
}

// The TraverseInvitation type is an adapter to allow the use of ordinary function as Traverser.
type TraverseInvitation func(context.Context, *db.InvitationQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseInvitation) Intercept(next db.Querier) db.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseInvitation) Traverse(ctx context.Context, q db.Query) error {
	if q, ok := q.(*db.InvitationQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *db.InvitationQuery", q)
}

// The MCPToolFunc type is an adapter to allow the use of ordinary function as a Querier.
type MCPToolFunc func(context.Context, *db.MCPToolQuery) (db.Value, error)

// Query calls f(ctx, q).
func (f MCPToolFunc) Query(ctx context.Context, q db.Query) (db.Value, error) {
	if q, ok := q.(*db.MCPToolQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *db.MCPToolQuery", q)
}

// The TraverseMCPTool type is an adapter to allow the use of ordinary function as Traverser.
type TraverseMCPTool func(context.Context, *db.MCPToolQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseMCPTool) Intercept(next db.Querier) db.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseMCPTool) Traverse(ctx context.Context, q db.Query) error {
	if q, ok := q.(*db.MCPToolQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *db.MCPToolQuery", q)
}

// The MCPUpstreamFunc type is an adapter to allow the use of ordinary function as a Querier.
type MCPUpstreamFunc func(context.Context, *db.MCPUpstreamQuery) (db.Value, error)

// Query calls f(ctx, q).
func (f MCPUpstreamFunc) Query(ctx context.Context, q db.Query) (db.Value, error) {
	if q, ok := q.(*db.MCPUpstreamQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *db.MCPUpstreamQuery", q)
}

// The TraverseMCPUpstream type is an adapter to allow the use of ordinary function as Traverser.
type TraverseMCPUpstream func(context.Context, *db.MCPUpstreamQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseMCPUpstream) Intercept(next db.Querier) db.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseMCPUpstream) Traverse(ctx context.Context, q db.Query) error {
	if q, ok := q.(*db.MCPUpstreamQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *db.MCPUpstreamQuery", q)
}

// The MCPUserToolSettingFunc type is an adapter to allow the use of ordinary function as a Querier.
type MCPUserToolSettingFunc func(context.Context, *db.MCPUserToolSettingQuery) (db.Value, error)

// Query calls f(ctx, q).
func (f MCPUserToolSettingFunc) Query(ctx context.Context, q db.Query) (db.Value, error) {
	if q, ok := q.(*db.MCPUserToolSettingQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *db.MCPUserToolSettingQuery", q)
}

// The TraverseMCPUserToolSetting type is an adapter to allow the use of ordinary function as Traverser.
type TraverseMCPUserToolSetting func(context.Context, *db.MCPUserToolSettingQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseMCPUserToolSetting) Intercept(next db.Querier) db.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseMCPUserToolSetting) Traverse(ctx context.Context, q db.Query) error {
	if q, ok := q.(*db.MCPUserToolSettingQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *db.MCPUserToolSettingQuery", q)
}

// The ModelFunc type is an adapter to allow the use of ordinary function as a Querier.
type ModelFunc func(context.Context, *db.ModelQuery) (db.Value, error)

// Query calls f(ctx, q).
func (f ModelFunc) Query(ctx context.Context, q db.Query) (db.Value, error) {
	if q, ok := q.(*db.ModelQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *db.ModelQuery", q)
}

// The TraverseModel type is an adapter to allow the use of ordinary function as Traverser.
type TraverseModel func(context.Context, *db.ModelQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseModel) Intercept(next db.Querier) db.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseModel) Traverse(ctx context.Context, q db.Query) error {
	if q, ok := q.(*db.ModelQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *db.ModelQuery", q)
}

// The ModelApiKeyFunc type is an adapter to allow the use of ordinary function as a Querier.
type ModelApiKeyFunc func(context.Context, *db.ModelApiKeyQuery) (db.Value, error)

// Query calls f(ctx, q).
func (f ModelApiKeyFunc) Query(ctx context.Context, q db.Query) (db.Value, error) {
	if q, ok := q.(*db.ModelApiKeyQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *db.ModelApiKeyQuery", q)
}

// The TraverseModelApiKey type is an adapter to allow the use of ordinary function as Traverser.
type TraverseModelApiKey func(context.Context, *db.ModelApiKeyQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseModelApiKey) Intercept(next db.Querier) db.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseModelApiKey) Traverse(ctx context.Context, q db.Query) error {
	if q, ok := q.(*db.ModelApiKeyQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *db.ModelApiKeyQuery", q)
}

// The ModelPricingFunc type is an adapter to allow the use of ordinary function as a Querier.
type ModelPricingFunc func(context.Context, *db.ModelPricingQuery) (db.Value, error)

// Query calls f(ctx, q).
func (f ModelPricingFunc) Query(ctx context.Context, q db.Query) (db.Value, error) {
	if q, ok := q.(*db.ModelPricingQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *db.ModelPricingQuery", q)
}

// The TraverseModelPricing type is an adapter to allow the use of ordinary function as Traverser.
type TraverseModelPricing func(context.Context, *db.ModelPricingQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseModelPricing) Intercept(next db.Querier) db.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseModelPricing) Traverse(ctx context.Context, q db.Query) error {
	if q, ok := q.(*db.ModelPricingQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *db.ModelPricingQuery", q)
}

// The NotifyChannelFunc type is an adapter to allow the use of ordinary function as a Querier.
type NotifyChannelFunc func(context.Context, *db.NotifyChannelQuery) (db.Value, error)

// Query calls f(ctx, q).
func (f NotifyChannelFunc) Query(ctx context.Context, q db.Query) (db.Value, error) {
	if q, ok := q.(*db.NotifyChannelQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *db.NotifyChannelQuery", q)
}

// The TraverseNotifyChannel type is an adapter to allow the use of ordinary function as Traverser.
type TraverseNotifyChannel func(context.Context, *db.NotifyChannelQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseNotifyChannel) Intercept(next db.Querier) db.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseNotifyChannel) Traverse(ctx context.Context, q db.Query) error {
	if q, ok := q.(*db.NotifyChannelQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *db.NotifyChannelQuery", q)
}

// The NotifySendLogFunc type is an adapter to allow the use of ordinary function as a Querier.
type NotifySendLogFunc func(context.Context, *db.NotifySendLogQuery) (db.Value, error)

// Query calls f(ctx, q).
func (f NotifySendLogFunc) Query(ctx context.Context, q db.Query) (db.Value, error) {
	if q, ok := q.(*db.NotifySendLogQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *db.NotifySendLogQuery", q)
}

// The TraverseNotifySendLog type is an adapter to allow the use of ordinary function as Traverser.
type TraverseNotifySendLog func(context.Context, *db.NotifySendLogQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseNotifySendLog) Intercept(next db.Querier) db.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseNotifySendLog) Traverse(ctx context.Context, q db.Query) error {
	if q, ok := q.(*db.NotifySendLogQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *db.NotifySendLogQuery", q)
}

// The NotifySubscriptionFunc type is an adapter to allow the use of ordinary function as a Querier.
type NotifySubscriptionFunc func(context.Context, *db.NotifySubscriptionQuery) (db.Value, error)

// Query calls f(ctx, q).
func (f NotifySubscriptionFunc) Query(ctx context.Context, q db.Query) (db.Value, error) {
	if q, ok := q.(*db.NotifySubscriptionQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *db.NotifySubscriptionQuery", q)
}

// The TraverseNotifySubscription type is an adapter to allow the use of ordinary function as Traverser.
type TraverseNotifySubscription func(context.Context, *db.NotifySubscriptionQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseNotifySubscription) Intercept(next db.Querier) db.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseNotifySubscription) Traverse(ctx context.Context, q db.Query) error {
	if q, ok := q.(*db.NotifySubscriptionQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *db.NotifySubscriptionQuery", q)
}

// The PaymentOrderFunc type is an adapter to allow the use of ordinary function as a Querier.
type PaymentOrderFunc func(context.Context, *db.PaymentOrderQuery) (db.Value, error)

// Query calls f(ctx, q).
func (f PaymentOrderFunc) Query(ctx context.Context, q db.Query) (db.Value, error) {
	if q, ok := q.(*db.PaymentOrderQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *db.PaymentOrderQuery", q)
}

// The TraversePaymentOrder type is an adapter to allow the use of ordinary function as Traverser.
type TraversePaymentOrder func(context.Context, *db.PaymentOrderQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraversePaymentOrder) Intercept(next db.Querier) db.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraversePaymentOrder) Traverse(ctx context.Context, q db.Query) error {
	if q, ok := q.(*db.PaymentOrderQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *db.PaymentOrderQuery", q)
}

// The PlanFunc type is an adapter to allow the use of ordinary function as a Querier.
type PlanFunc func(context.Context, *db.PlanQuery) (db.Value, error)

// Query calls f(ctx, q).
func (f PlanFunc) Query(ctx context.Context, q db.Query) (db.Value, error) {
	if q, ok := q.(*db.PlanQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *db.PlanQuery", q)
}

// The TraversePlan type is an adapter to allow the use of ordinary function as Traverser.
type TraversePlan func(context.Context, *db.PlanQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraversePlan) Intercept(next db.Querier) db.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraversePlan) Traverse(ctx context.Context, q db.Query) error {
	if q, ok := q.(*db.PlanQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *db.PlanQuery", q)
}

// The ProjectFunc type is an adapter to allow the use of ordinary function as a Querier.
type ProjectFunc func(context.Context, *db.ProjectQuery) (db.Value, error)

// Query calls f(ctx, q).
func (f ProjectFunc) Query(ctx context.Context, q db.Query) (db.Value, error) {
	if q, ok := q.(*db.ProjectQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *db.ProjectQuery", q)
}

// The TraverseProject type is an adapter to allow the use of ordinary function as Traverser.
type TraverseProject func(context.Context, *db.ProjectQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseProject) Intercept(next db.Querier) db.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseProject) Traverse(ctx context.Context, q db.Query) error {
	if q, ok := q.(*db.ProjectQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *db.ProjectQuery", q)
}

// The ProjectCollaboratorFunc type is an adapter to allow the use of ordinary function as a Querier.
type ProjectCollaboratorFunc func(context.Context, *db.ProjectCollaboratorQuery) (db.Value, error)

// Query calls f(ctx, q).
func (f ProjectCollaboratorFunc) Query(ctx context.Context, q db.Query) (db.Value, error) {
	if q, ok := q.(*db.ProjectCollaboratorQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *db.ProjectCollaboratorQuery", q)
}

// The TraverseProjectCollaborator type is an adapter to allow the use of ordinary function as Traverser.
type TraverseProjectCollaborator func(context.Context, *db.ProjectCollaboratorQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseProjectCollaborator) Intercept(next db.Querier) db.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseProjectCollaborator) Traverse(ctx context.Context, q db.Query) error {
	if q, ok := q.(*db.ProjectCollaboratorQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *db.ProjectCollaboratorQuery", q)
}

// The ProjectGitBotFunc type is an adapter to allow the use of ordinary function as a Querier.
type ProjectGitBotFunc func(context.Context, *db.ProjectGitBotQuery) (db.Value, error)

// Query calls f(ctx, q).
func (f ProjectGitBotFunc) Query(ctx context.Context, q db.Query) (db.Value, error) {
	if q, ok := q.(*db.ProjectGitBotQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *db.ProjectGitBotQuery", q)
}

// The TraverseProjectGitBot type is an adapter to allow the use of ordinary function as Traverser.
type TraverseProjectGitBot func(context.Context, *db.ProjectGitBotQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseProjectGitBot) Intercept(next db.Querier) db.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseProjectGitBot) Traverse(ctx context.Context, q db.Query) error {
	if q, ok := q.(*db.ProjectGitBotQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *db.ProjectGitBotQuery", q)
}

// The ProjectIssueFunc type is an adapter to allow the use of ordinary function as a Querier.
type ProjectIssueFunc func(context.Context, *db.ProjectIssueQuery) (db.Value, error)

// Query calls f(ctx, q).
func (f ProjectIssueFunc) Query(ctx context.Context, q db.Query) (db.Value, error) {
	if q, ok := q.(*db.ProjectIssueQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *db.ProjectIssueQuery", q)
}

// The TraverseProjectIssue type is an adapter to allow the use of ordinary function as Traverser.
type TraverseProjectIssue func(context.Context, *db.ProjectIssueQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseProjectIssue) Intercept(next db.Querier) db.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseProjectIssue) Traverse(ctx context.Context, q db.Query) error {
	if q, ok := q.(*db.ProjectIssueQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *db.ProjectIssueQuery", q)
}

// The ProjectIssueCommentFunc type is an adapter to allow the use of ordinary function as a Querier.
type ProjectIssueCommentFunc func(context.Context, *db.ProjectIssueCommentQuery) (db.Value, error)

// Query calls f(ctx, q).
func (f ProjectIssueCommentFunc) Query(ctx context.Context, q db.Query) (db.Value, error) {
	if q, ok := q.(*db.ProjectIssueCommentQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *db.ProjectIssueCommentQuery", q)
}

// The TraverseProjectIssueComment type is an adapter to allow the use of ordinary function as Traverser.
type TraverseProjectIssueComment func(context.Context, *db.ProjectIssueCommentQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseProjectIssueComment) Intercept(next db.Querier) db.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseProjectIssueComment) Traverse(ctx context.Context, q db.Query) error {
	if q, ok := q.(*db.ProjectIssueCommentQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *db.ProjectIssueCommentQuery", q)
}

// The ProjectTaskFunc type is an adapter to allow the use of ordinary function as a Querier.
type ProjectTaskFunc func(context.Context, *db.ProjectTaskQuery) (db.Value, error)

// Query calls f(ctx, q).
func (f ProjectTaskFunc) Query(ctx context.Context, q db.Query) (db.Value, error) {
	if q, ok := q.(*db.ProjectTaskQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *db.ProjectTaskQuery", q)
}

// The TraverseProjectTask type is an adapter to allow the use of ordinary function as Traverser.
type TraverseProjectTask func(context.Context, *db.ProjectTaskQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseProjectTask) Intercept(next db.Querier) db.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseProjectTask) Traverse(ctx context.Context, q db.Query) error {
	if q, ok := q.(*db.ProjectTaskQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *db.ProjectTaskQuery", q)
}

// The SkillFunc type is an adapter to allow the use of ordinary function as a Querier.
type SkillFunc func(context.Context, *db.SkillQuery) (db.Value, error)

// Query calls f(ctx, q).
func (f SkillFunc) Query(ctx context.Context, q db.Query) (db.Value, error) {
	if q, ok := q.(*db.SkillQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *db.SkillQuery", q)
}

// The TraverseSkill type is an adapter to allow the use of ordinary function as Traverser.
type TraverseSkill func(context.Context, *db.SkillQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseSkill) Intercept(next db.Querier) db.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseSkill) Traverse(ctx context.Context, q db.Query) error {
	if q, ok := q.(*db.SkillQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *db.SkillQuery", q)
}

// The SkillRatingFunc type is an adapter to allow the use of ordinary function as a Querier.
type SkillRatingFunc func(context.Context, *db.SkillRatingQuery) (db.Value, error)

// Query calls f(ctx, q).
func (f SkillRatingFunc) Query(ctx context.Context, q db.Query) (db.Value, error) {
	if q, ok := q.(*db.SkillRatingQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *db.SkillRatingQuery", q)
}

// The TraverseSkillRating type is an adapter to allow the use of ordinary function as Traverser.
type TraverseSkillRating func(context.Context, *db.SkillRatingQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseSkillRating) Intercept(next db.Querier) db.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseSkillRating) Traverse(ctx context.Context, q db.Query) error {
	if q, ok := q.(*db.SkillRatingQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *db.SkillRatingQuery", q)
}

// The SkillReviewFunc type is an adapter to allow the use of ordinary function as a Querier.
type SkillReviewFunc func(context.Context, *db.SkillReviewQuery) (db.Value, error)

// Query calls f(ctx, q).
func (f SkillReviewFunc) Query(ctx context.Context, q db.Query) (db.Value, error) {
	if q, ok := q.(*db.SkillReviewQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *db.SkillReviewQuery", q)
}

// The TraverseSkillReview type is an adapter to allow the use of ordinary function as Traverser.
type TraverseSkillReview func(context.Context, *db.SkillReviewQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseSkillReview) Intercept(next db.Querier) db.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseSkillReview) Traverse(ctx context.Context, q db.Query) error {
	if q, ok := q.(*db.SkillReviewQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *db.SkillReviewQuery", q)
}

// The SkillVersionFunc type is an adapter to allow the use of ordinary function as a Querier.
type SkillVersionFunc func(context.Context, *db.SkillVersionQuery) (db.Value, error)

// Query calls f(ctx, q).
func (f SkillVersionFunc) Query(ctx context.Context, q db.Query) (db.Value, error) {
	if q, ok := q.(*db.SkillVersionQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *db.SkillVersionQuery", q)
}

// The TraverseSkillVersion type is an adapter to allow the use of ordinary function as Traverser.
type TraverseSkillVersion func(context.Context, *db.SkillVersionQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseSkillVersion) Intercept(next db.Querier) db.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseSkillVersion) Traverse(ctx context.Context, q db.Query) error {
	if q, ok := q.(*db.SkillVersionQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *db.SkillVersionQuery", q)
}

// The TaskFunc type is an adapter to allow the use of ordinary function as a Querier.
type TaskFunc func(context.Context, *db.TaskQuery) (db.Value, error)

// Query calls f(ctx, q).
func (f TaskFunc) Query(ctx context.Context, q db.Query) (db.Value, error) {
	if q, ok := q.(*db.TaskQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *db.TaskQuery", q)
}

// The TraverseTask type is an adapter to allow the use of ordinary function as Traverser.
type TraverseTask func(context.Context, *db.TaskQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseTask) Intercept(next db.Querier) db.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseTask) Traverse(ctx context.Context, q db.Query) error {
	if q, ok := q.(*db.TaskQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *db.TaskQuery", q)
}

// The TaskModelSwitchFunc type is an adapter to allow the use of ordinary function as a Querier.
type TaskModelSwitchFunc func(context.Context, *db.TaskModelSwitchQuery) (db.Value, error)

// Query calls f(ctx, q).
func (f TaskModelSwitchFunc) Query(ctx context.Context, q db.Query) (db.Value, error) {
	if q, ok := q.(*db.TaskModelSwitchQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *db.TaskModelSwitchQuery", q)
}

// The TraverseTaskModelSwitch type is an adapter to allow the use of ordinary function as Traverser.
type TraverseTaskModelSwitch func(context.Context, *db.TaskModelSwitchQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseTaskModelSwitch) Intercept(next db.Querier) db.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseTaskModelSwitch) Traverse(ctx context.Context, q db.Query) error {
	if q, ok := q.(*db.TaskModelSwitchQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *db.TaskModelSwitchQuery", q)
}

// The TaskUsageStatFunc type is an adapter to allow the use of ordinary function as a Querier.
type TaskUsageStatFunc func(context.Context, *db.TaskUsageStatQuery) (db.Value, error)

// Query calls f(ctx, q).
func (f TaskUsageStatFunc) Query(ctx context.Context, q db.Query) (db.Value, error) {
	if q, ok := q.(*db.TaskUsageStatQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *db.TaskUsageStatQuery", q)
}

// The TraverseTaskUsageStat type is an adapter to allow the use of ordinary function as Traverser.
type TraverseTaskUsageStat func(context.Context, *db.TaskUsageStatQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseTaskUsageStat) Intercept(next db.Querier) db.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseTaskUsageStat) Traverse(ctx context.Context, q db.Query) error {
	if q, ok := q.(*db.TaskUsageStatQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *db.TaskUsageStatQuery", q)
}

// The TaskVirtualMachineFunc type is an adapter to allow the use of ordinary function as a Querier.
type TaskVirtualMachineFunc func(context.Context, *db.TaskVirtualMachineQuery) (db.Value, error)

// Query calls f(ctx, q).
func (f TaskVirtualMachineFunc) Query(ctx context.Context, q db.Query) (db.Value, error) {
	if q, ok := q.(*db.TaskVirtualMachineQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *db.TaskVirtualMachineQuery", q)
}

// The TraverseTaskVirtualMachine type is an adapter to allow the use of ordinary function as Traverser.
type TraverseTaskVirtualMachine func(context.Context, *db.TaskVirtualMachineQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseTaskVirtualMachine) Intercept(next db.Querier) db.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseTaskVirtualMachine) Traverse(ctx context.Context, q db.Query) error {
	if q, ok := q.(*db.TaskVirtualMachineQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *db.TaskVirtualMachineQuery", q)
}

// The TeamFunc type is an adapter to allow the use of ordinary function as a Querier.
type TeamFunc func(context.Context, *db.TeamQuery) (db.Value, error)

// Query calls f(ctx, q).
func (f TeamFunc) Query(ctx context.Context, q db.Query) (db.Value, error) {
	if q, ok := q.(*db.TeamQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *db.TeamQuery", q)
}

// The TraverseTeam type is an adapter to allow the use of ordinary function as Traverser.
type TraverseTeam func(context.Context, *db.TeamQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseTeam) Intercept(next db.Querier) db.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseTeam) Traverse(ctx context.Context, q db.Query) error {
	if q, ok := q.(*db.TeamQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *db.TeamQuery", q)
}

// The TeamGroupFunc type is an adapter to allow the use of ordinary function as a Querier.
type TeamGroupFunc func(context.Context, *db.TeamGroupQuery) (db.Value, error)

// Query calls f(ctx, q).
func (f TeamGroupFunc) Query(ctx context.Context, q db.Query) (db.Value, error) {
	if q, ok := q.(*db.TeamGroupQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *db.TeamGroupQuery", q)
}

// The TraverseTeamGroup type is an adapter to allow the use of ordinary function as Traverser.
type TraverseTeamGroup func(context.Context, *db.TeamGroupQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseTeamGroup) Intercept(next db.Querier) db.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseTeamGroup) Traverse(ctx context.Context, q db.Query) error {
	if q, ok := q.(*db.TeamGroupQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *db.TeamGroupQuery", q)
}

// The TeamGroupHostFunc type is an adapter to allow the use of ordinary function as a Querier.
type TeamGroupHostFunc func(context.Context, *db.TeamGroupHostQuery) (db.Value, error)

// Query calls f(ctx, q).
func (f TeamGroupHostFunc) Query(ctx context.Context, q db.Query) (db.Value, error) {
	if q, ok := q.(*db.TeamGroupHostQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *db.TeamGroupHostQuery", q)
}

// The TraverseTeamGroupHost type is an adapter to allow the use of ordinary function as Traverser.
type TraverseTeamGroupHost func(context.Context, *db.TeamGroupHostQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseTeamGroupHost) Intercept(next db.Querier) db.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseTeamGroupHost) Traverse(ctx context.Context, q db.Query) error {
	if q, ok := q.(*db.TeamGroupHostQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *db.TeamGroupHostQuery", q)
}

// The TeamGroupImageFunc type is an adapter to allow the use of ordinary function as a Querier.
type TeamGroupImageFunc func(context.Context, *db.TeamGroupImageQuery) (db.Value, error)

// Query calls f(ctx, q).
func (f TeamGroupImageFunc) Query(ctx context.Context, q db.Query) (db.Value, error) {
	if q, ok := q.(*db.TeamGroupImageQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *db.TeamGroupImageQuery", q)
}

// The TraverseTeamGroupImage type is an adapter to allow the use of ordinary function as Traverser.
type TraverseTeamGroupImage func(context.Context, *db.TeamGroupImageQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseTeamGroupImage) Intercept(next db.Querier) db.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseTeamGroupImage) Traverse(ctx context.Context, q db.Query) error {
	if q, ok := q.(*db.TeamGroupImageQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *db.TeamGroupImageQuery", q)
}

// The TeamGroupMemberFunc type is an adapter to allow the use of ordinary function as a Querier.
type TeamGroupMemberFunc func(context.Context, *db.TeamGroupMemberQuery) (db.Value, error)

// Query calls f(ctx, q).
func (f TeamGroupMemberFunc) Query(ctx context.Context, q db.Query) (db.Value, error) {
	if q, ok := q.(*db.TeamGroupMemberQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *db.TeamGroupMemberQuery", q)
}

// The TraverseTeamGroupMember type is an adapter to allow the use of ordinary function as Traverser.
type TraverseTeamGroupMember func(context.Context, *db.TeamGroupMemberQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseTeamGroupMember) Intercept(next db.Querier) db.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseTeamGroupMember) Traverse(ctx context.Context, q db.Query) error {
	if q, ok := q.(*db.TeamGroupMemberQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *db.TeamGroupMemberQuery", q)
}

// The TeamGroupModelFunc type is an adapter to allow the use of ordinary function as a Querier.
type TeamGroupModelFunc func(context.Context, *db.TeamGroupModelQuery) (db.Value, error)

// Query calls f(ctx, q).
func (f TeamGroupModelFunc) Query(ctx context.Context, q db.Query) (db.Value, error) {
	if q, ok := q.(*db.TeamGroupModelQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *db.TeamGroupModelQuery", q)
}

// The TraverseTeamGroupModel type is an adapter to allow the use of ordinary function as Traverser.
type TraverseTeamGroupModel func(context.Context, *db.TeamGroupModelQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseTeamGroupModel) Intercept(next db.Querier) db.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseTeamGroupModel) Traverse(ctx context.Context, q db.Query) error {
	if q, ok := q.(*db.TeamGroupModelQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *db.TeamGroupModelQuery", q)
}

// The TeamHostFunc type is an adapter to allow the use of ordinary function as a Querier.
type TeamHostFunc func(context.Context, *db.TeamHostQuery) (db.Value, error)

// Query calls f(ctx, q).
func (f TeamHostFunc) Query(ctx context.Context, q db.Query) (db.Value, error) {
	if q, ok := q.(*db.TeamHostQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *db.TeamHostQuery", q)
}

// The TraverseTeamHost type is an adapter to allow the use of ordinary function as Traverser.
type TraverseTeamHost func(context.Context, *db.TeamHostQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseTeamHost) Intercept(next db.Querier) db.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseTeamHost) Traverse(ctx context.Context, q db.Query) error {
	if q, ok := q.(*db.TeamHostQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *db.TeamHostQuery", q)
}

// The TeamImageFunc type is an adapter to allow the use of ordinary function as a Querier.
type TeamImageFunc func(context.Context, *db.TeamImageQuery) (db.Value, error)

// Query calls f(ctx, q).
func (f TeamImageFunc) Query(ctx context.Context, q db.Query) (db.Value, error) {
	if q, ok := q.(*db.TeamImageQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *db.TeamImageQuery", q)
}

// The TraverseTeamImage type is an adapter to allow the use of ordinary function as Traverser.
type TraverseTeamImage func(context.Context, *db.TeamImageQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseTeamImage) Intercept(next db.Querier) db.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseTeamImage) Traverse(ctx context.Context, q db.Query) error {
	if q, ok := q.(*db.TeamImageQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *db.TeamImageQuery", q)
}

// The TeamMemberFunc type is an adapter to allow the use of ordinary function as a Querier.
type TeamMemberFunc func(context.Context, *db.TeamMemberQuery) (db.Value, error)

// Query calls f(ctx, q).
func (f TeamMemberFunc) Query(ctx context.Context, q db.Query) (db.Value, error) {
	if q, ok := q.(*db.TeamMemberQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *db.TeamMemberQuery", q)
}

// The TraverseTeamMember type is an adapter to allow the use of ordinary function as Traverser.
type TraverseTeamMember func(context.Context, *db.TeamMemberQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseTeamMember) Intercept(next db.Querier) db.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseTeamMember) Traverse(ctx context.Context, q db.Query) error {
	if q, ok := q.(*db.TeamMemberQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *db.TeamMemberQuery", q)
}

// The TeamModelFunc type is an adapter to allow the use of ordinary function as a Querier.
type TeamModelFunc func(context.Context, *db.TeamModelQuery) (db.Value, error)

// Query calls f(ctx, q).
func (f TeamModelFunc) Query(ctx context.Context, q db.Query) (db.Value, error) {
	if q, ok := q.(*db.TeamModelQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *db.TeamModelQuery", q)
}

// The TraverseTeamModel type is an adapter to allow the use of ordinary function as Traverser.
type TraverseTeamModel func(context.Context, *db.TeamModelQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseTeamModel) Intercept(next db.Querier) db.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseTeamModel) Traverse(ctx context.Context, q db.Query) error {
	if q, ok := q.(*db.TeamModelQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *db.TeamModelQuery", q)
}

// The TransactionLogFunc type is an adapter to allow the use of ordinary function as a Querier.
type TransactionLogFunc func(context.Context, *db.TransactionLogQuery) (db.Value, error)

// Query calls f(ctx, q).
func (f TransactionLogFunc) Query(ctx context.Context, q db.Query) (db.Value, error) {
	if q, ok := q.(*db.TransactionLogQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *db.TransactionLogQuery", q)
}

// The TraverseTransactionLog type is an adapter to allow the use of ordinary function as Traverser.
type TraverseTransactionLog func(context.Context, *db.TransactionLogQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseTransactionLog) Intercept(next db.Querier) db.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseTransactionLog) Traverse(ctx context.Context, q db.Query) error {
	if q, ok := q.(*db.TransactionLogQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *db.TransactionLogQuery", q)
}

// The UserFunc type is an adapter to allow the use of ordinary function as a Querier.
type UserFunc func(context.Context, *db.UserQuery) (db.Value, error)

// Query calls f(ctx, q).
func (f UserFunc) Query(ctx context.Context, q db.Query) (db.Value, error) {
	if q, ok := q.(*db.UserQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *db.UserQuery", q)
}

// The TraverseUser type is an adapter to allow the use of ordinary function as Traverser.
type TraverseUser func(context.Context, *db.UserQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseUser) Intercept(next db.Querier) db.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseUser) Traverse(ctx context.Context, q db.Query) error {
	if q, ok := q.(*db.UserQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *db.UserQuery", q)
}

// The UserApiKeyFunc type is an adapter to allow the use of ordinary function as a Querier.
type UserApiKeyFunc func(context.Context, *db.UserApiKeyQuery) (db.Value, error)

// Query calls f(ctx, q).
func (f UserApiKeyFunc) Query(ctx context.Context, q db.Query) (db.Value, error) {
	if q, ok := q.(*db.UserApiKeyQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *db.UserApiKeyQuery", q)
}

// The TraverseUserApiKey type is an adapter to allow the use of ordinary function as Traverser.
type TraverseUserApiKey func(context.Context, *db.UserApiKeyQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseUserApiKey) Intercept(next db.Querier) db.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseUserApiKey) Traverse(ctx context.Context, q db.Query) error {
	if q, ok := q.(*db.UserApiKeyQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *db.UserApiKeyQuery", q)
}

// The UserIdentityFunc type is an adapter to allow the use of ordinary function as a Querier.
type UserIdentityFunc func(context.Context, *db.UserIdentityQuery) (db.Value, error)

// Query calls f(ctx, q).
func (f UserIdentityFunc) Query(ctx context.Context, q db.Query) (db.Value, error) {
	if q, ok := q.(*db.UserIdentityQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *db.UserIdentityQuery", q)
}

// The TraverseUserIdentity type is an adapter to allow the use of ordinary function as Traverser.
type TraverseUserIdentity func(context.Context, *db.UserIdentityQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseUserIdentity) Intercept(next db.Querier) db.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseUserIdentity) Traverse(ctx context.Context, q db.Query) error {
	if q, ok := q.(*db.UserIdentityQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *db.UserIdentityQuery", q)
}

// The UserSubscriptionFunc type is an adapter to allow the use of ordinary function as a Querier.
type UserSubscriptionFunc func(context.Context, *db.UserSubscriptionQuery) (db.Value, error)

// Query calls f(ctx, q).
func (f UserSubscriptionFunc) Query(ctx context.Context, q db.Query) (db.Value, error) {
	if q, ok := q.(*db.UserSubscriptionQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *db.UserSubscriptionQuery", q)
}

// The TraverseUserSubscription type is an adapter to allow the use of ordinary function as Traverser.
type TraverseUserSubscription func(context.Context, *db.UserSubscriptionQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseUserSubscription) Intercept(next db.Querier) db.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseUserSubscription) Traverse(ctx context.Context, q db.Query) error {
	if q, ok := q.(*db.UserSubscriptionQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *db.UserSubscriptionQuery", q)
}

// The VirtualMachineFunc type is an adapter to allow the use of ordinary function as a Querier.
type VirtualMachineFunc func(context.Context, *db.VirtualMachineQuery) (db.Value, error)

// Query calls f(ctx, q).
func (f VirtualMachineFunc) Query(ctx context.Context, q db.Query) (db.Value, error) {
	if q, ok := q.(*db.VirtualMachineQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *db.VirtualMachineQuery", q)
}

// The TraverseVirtualMachine type is an adapter to allow the use of ordinary function as Traverser.
type TraverseVirtualMachine func(context.Context, *db.VirtualMachineQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseVirtualMachine) Intercept(next db.Querier) db.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseVirtualMachine) Traverse(ctx context.Context, q db.Query) error {
	if q, ok := q.(*db.VirtualMachineQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *db.VirtualMachineQuery", q)
}

// The WalletFunc type is an adapter to allow the use of ordinary function as a Querier.
type WalletFunc func(context.Context, *db.WalletQuery) (db.Value, error)

// Query calls f(ctx, q).
func (f WalletFunc) Query(ctx context.Context, q db.Query) (db.Value, error) {
	if q, ok := q.(*db.WalletQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *db.WalletQuery", q)
}

// The TraverseWallet type is an adapter to allow the use of ordinary function as Traverser.
type TraverseWallet func(context.Context, *db.WalletQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseWallet) Intercept(next db.Querier) db.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseWallet) Traverse(ctx context.Context, q db.Query) error {
	if q, ok := q.(*db.WalletQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *db.WalletQuery", q)
}

// NewQuery returns the generic Query interface for the given typed query.
func NewQuery(q db.Query) (Query, error) {
	switch q := q.(type) {
	case *db.AuditQuery:
		return &query[*db.AuditQuery, predicate.Audit, audit.OrderOption]{typ: db.TypeAudit, tq: q}, nil
	case *db.CheckInQuery:
		return &query[*db.CheckInQuery, predicate.CheckIn, checkin.OrderOption]{typ: db.TypeCheckIn, tq: q}, nil
	case *db.DataApiPricingQuery:
		return &query[*db.DataApiPricingQuery, predicate.DataApiPricing, dataapipricing.OrderOption]{typ: db.TypeDataApiPricing, tq: q}, nil
	case *db.ExchangeCodeQuery:
		return &query[*db.ExchangeCodeQuery, predicate.ExchangeCode, exchangecode.OrderOption]{typ: db.TypeExchangeCode, tq: q}, nil
	case *db.ExpertQuery:
		return &query[*db.ExpertQuery, predicate.Expert, expert.OrderOption]{typ: db.TypeExpert, tq: q}, nil
	case *db.GitBotQuery:
		return &query[*db.GitBotQuery, predicate.GitBot, gitbot.OrderOption]{typ: db.TypeGitBot, tq: q}, nil
	case *db.GitBotTaskQuery:
		return &query[*db.GitBotTaskQuery, predicate.GitBotTask, gitbottask.OrderOption]{typ: db.TypeGitBotTask, tq: q}, nil
	case *db.GitBotUserQuery:
		return &query[*db.GitBotUserQuery, predicate.GitBotUser, gitbotuser.OrderOption]{typ: db.TypeGitBotUser, tq: q}, nil
	case *db.GitIdentityQuery:
		return &query[*db.GitIdentityQuery, predicate.GitIdentity, gitidentity.OrderOption]{typ: db.TypeGitIdentity, tq: q}, nil
	case *db.GitTaskQuery:
		return &query[*db.GitTaskQuery, predicate.GitTask, gittask.OrderOption]{typ: db.TypeGitTask, tq: q}, nil
	case *db.HostQuery:
		return &query[*db.HostQuery, predicate.Host, host.OrderOption]{typ: db.TypeHost, tq: q}, nil
	case *db.ImageQuery:
		return &query[*db.ImageQuery, predicate.Image, image.OrderOption]{typ: db.TypeImage, tq: q}, nil
	case *db.InvitationQuery:
		return &query[*db.InvitationQuery, predicate.Invitation, invitation.OrderOption]{typ: db.TypeInvitation, tq: q}, nil
	case *db.MCPToolQuery:
		return &query[*db.MCPToolQuery, predicate.MCPTool, mcptool.OrderOption]{typ: db.TypeMCPTool, tq: q}, nil
	case *db.MCPUpstreamQuery:
		return &query[*db.MCPUpstreamQuery, predicate.MCPUpstream, mcpupstream.OrderOption]{typ: db.TypeMCPUpstream, tq: q}, nil
	case *db.MCPUserToolSettingQuery:
		return &query[*db.MCPUserToolSettingQuery, predicate.MCPUserToolSetting, mcpusertoolsetting.OrderOption]{typ: db.TypeMCPUserToolSetting, tq: q}, nil
	case *db.ModelQuery:
		return &query[*db.ModelQuery, predicate.Model, model.OrderOption]{typ: db.TypeModel, tq: q}, nil
	case *db.ModelApiKeyQuery:
		return &query[*db.ModelApiKeyQuery, predicate.ModelApiKey, modelapikey.OrderOption]{typ: db.TypeModelApiKey, tq: q}, nil
	case *db.ModelPricingQuery:
		return &query[*db.ModelPricingQuery, predicate.ModelPricing, modelpricing.OrderOption]{typ: db.TypeModelPricing, tq: q}, nil
	case *db.NotifyChannelQuery:
		return &query[*db.NotifyChannelQuery, predicate.NotifyChannel, notifychannel.OrderOption]{typ: db.TypeNotifyChannel, tq: q}, nil
	case *db.NotifySendLogQuery:
		return &query[*db.NotifySendLogQuery, predicate.NotifySendLog, notifysendlog.OrderOption]{typ: db.TypeNotifySendLog, tq: q}, nil
	case *db.NotifySubscriptionQuery:
		return &query[*db.NotifySubscriptionQuery, predicate.NotifySubscription, notifysubscription.OrderOption]{typ: db.TypeNotifySubscription, tq: q}, nil
	case *db.PaymentOrderQuery:
		return &query[*db.PaymentOrderQuery, predicate.PaymentOrder, paymentorder.OrderOption]{typ: db.TypePaymentOrder, tq: q}, nil
	case *db.PlanQuery:
		return &query[*db.PlanQuery, predicate.Plan, plan.OrderOption]{typ: db.TypePlan, tq: q}, nil
	case *db.ProjectQuery:
		return &query[*db.ProjectQuery, predicate.Project, project.OrderOption]{typ: db.TypeProject, tq: q}, nil
	case *db.ProjectCollaboratorQuery:
		return &query[*db.ProjectCollaboratorQuery, predicate.ProjectCollaborator, projectcollaborator.OrderOption]{typ: db.TypeProjectCollaborator, tq: q}, nil
	case *db.ProjectGitBotQuery:
		return &query[*db.ProjectGitBotQuery, predicate.ProjectGitBot, projectgitbot.OrderOption]{typ: db.TypeProjectGitBot, tq: q}, nil
	case *db.ProjectIssueQuery:
		return &query[*db.ProjectIssueQuery, predicate.ProjectIssue, projectissue.OrderOption]{typ: db.TypeProjectIssue, tq: q}, nil
	case *db.ProjectIssueCommentQuery:
		return &query[*db.ProjectIssueCommentQuery, predicate.ProjectIssueComment, projectissuecomment.OrderOption]{typ: db.TypeProjectIssueComment, tq: q}, nil
	case *db.ProjectTaskQuery:
		return &query[*db.ProjectTaskQuery, predicate.ProjectTask, projecttask.OrderOption]{typ: db.TypeProjectTask, tq: q}, nil
	case *db.SkillQuery:
		return &query[*db.SkillQuery, predicate.Skill, skill.OrderOption]{typ: db.TypeSkill, tq: q}, nil
	case *db.SkillRatingQuery:
		return &query[*db.SkillRatingQuery, predicate.SkillRating, skillrating.OrderOption]{typ: db.TypeSkillRating, tq: q}, nil
	case *db.SkillReviewQuery:
		return &query[*db.SkillReviewQuery, predicate.SkillReview, skillreview.OrderOption]{typ: db.TypeSkillReview, tq: q}, nil
	case *db.SkillVersionQuery:
		return &query[*db.SkillVersionQuery, predicate.SkillVersion, skillversion.OrderOption]{typ: db.TypeSkillVersion, tq: q}, nil
	case *db.TaskQuery:
		return &query[*db.TaskQuery, predicate.Task, task.OrderOption]{typ: db.TypeTask, tq: q}, nil
	case *db.TaskModelSwitchQuery:
		return &query[*db.TaskModelSwitchQuery, predicate.TaskModelSwitch, taskmodelswitch.OrderOption]{typ: db.TypeTaskModelSwitch, tq: q}, nil
	case *db.TaskUsageStatQuery:
		return &query[*db.TaskUsageStatQuery, predicate.TaskUsageStat, taskusagestat.OrderOption]{typ: db.TypeTaskUsageStat, tq: q}, nil
	case *db.TaskVirtualMachineQuery:
		return &query[*db.TaskVirtualMachineQuery, predicate.TaskVirtualMachine, taskvirtualmachine.OrderOption]{typ: db.TypeTaskVirtualMachine, tq: q}, nil
	case *db.TeamQuery:
		return &query[*db.TeamQuery, predicate.Team, team.OrderOption]{typ: db.TypeTeam, tq: q}, nil
	case *db.TeamGroupQuery:
		return &query[*db.TeamGroupQuery, predicate.TeamGroup, teamgroup.OrderOption]{typ: db.TypeTeamGroup, tq: q}, nil
	case *db.TeamGroupHostQuery:
		return &query[*db.TeamGroupHostQuery, predicate.TeamGroupHost, teamgrouphost.OrderOption]{typ: db.TypeTeamGroupHost, tq: q}, nil
	case *db.TeamGroupImageQuery:
		return &query[*db.TeamGroupImageQuery, predicate.TeamGroupImage, teamgroupimage.OrderOption]{typ: db.TypeTeamGroupImage, tq: q}, nil
	case *db.TeamGroupMemberQuery:
		return &query[*db.TeamGroupMemberQuery, predicate.TeamGroupMember, teamgroupmember.OrderOption]{typ: db.TypeTeamGroupMember, tq: q}, nil
	case *db.TeamGroupModelQuery:
		return &query[*db.TeamGroupModelQuery, predicate.TeamGroupModel, teamgroupmodel.OrderOption]{typ: db.TypeTeamGroupModel, tq: q}, nil
	case *db.TeamHostQuery:
		return &query[*db.TeamHostQuery, predicate.TeamHost, teamhost.OrderOption]{typ: db.TypeTeamHost, tq: q}, nil
	case *db.TeamImageQuery:
		return &query[*db.TeamImageQuery, predicate.TeamImage, teamimage.OrderOption]{typ: db.TypeTeamImage, tq: q}, nil
	case *db.TeamMemberQuery:
		return &query[*db.TeamMemberQuery, predicate.TeamMember, teammember.OrderOption]{typ: db.TypeTeamMember, tq: q}, nil
	case *db.TeamModelQuery:
		return &query[*db.TeamModelQuery, predicate.TeamModel, teammodel.OrderOption]{typ: db.TypeTeamModel, tq: q}, nil
	case *db.TransactionLogQuery:
		return &query[*db.TransactionLogQuery, predicate.TransactionLog, transactionlog.OrderOption]{typ: db.TypeTransactionLog, tq: q}, nil
	case *db.UserQuery:
		return &query[*db.UserQuery, predicate.User, user.OrderOption]{typ: db.TypeUser, tq: q}, nil
	case *db.UserApiKeyQuery:
		return &query[*db.UserApiKeyQuery, predicate.UserApiKey, userapikey.OrderOption]{typ: db.TypeUserApiKey, tq: q}, nil
	case *db.UserIdentityQuery:
		return &query[*db.UserIdentityQuery, predicate.UserIdentity, useridentity.OrderOption]{typ: db.TypeUserIdentity, tq: q}, nil
	case *db.UserSubscriptionQuery:
		return &query[*db.UserSubscriptionQuery, predicate.UserSubscription, usersubscription.OrderOption]{typ: db.TypeUserSubscription, tq: q}, nil
	case *db.VirtualMachineQuery:
		return &query[*db.VirtualMachineQuery, predicate.VirtualMachine, virtualmachine.OrderOption]{typ: db.TypeVirtualMachine, tq: q}, nil
	case *db.WalletQuery:
		return &query[*db.WalletQuery, predicate.Wallet, wallet.OrderOption]{typ: db.TypeWallet, tq: q}, nil
	default:
		return nil, fmt.Errorf("unknown query type %T", q)
	}
}

type query[T any, P ~func(*sql.Selector), R ~func(*sql.Selector)] struct {
	typ string
	tq  interface {
		Limit(int) T
		Offset(int) T
		Unique(bool) T
		Order(...R) T
		Where(...P) T
	}
}

func (q query[T, P, R]) Type() string {
	return q.typ
}

func (q query[T, P, R]) Limit(limit int) {
	q.tq.Limit(limit)
}

func (q query[T, P, R]) Offset(offset int) {
	q.tq.Offset(offset)
}

func (q query[T, P, R]) Unique(unique bool) {
	q.tq.Unique(unique)
}

func (q query[T, P, R]) Order(orders ...func(*sql.Selector)) {
	rs := make([]R, len(orders))
	for i := range orders {
		rs[i] = orders[i]
	}
	q.tq.Order(rs...)
}

func (q query[T, P, R]) WhereP(ps ...func(*sql.Selector)) {
	p := make([]P, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	q.tq.Where(p...)
}
