// Code generated by ent, DO NOT EDIT.

package modelapikey

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/nidao003/mclaw/backend/db/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldLTE(FieldID, id))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldEQ(FieldDeletedAt, v))
}

// ModelID applies equality check predicate on the "model_id" field. It's identical to ModelIDEQ.
func ModelID(v uuid.UUID) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldEQ(FieldModelID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldEQ(FieldUserID, v))
}

// VirtualmachineID applies equality check predicate on the "virtualmachine_id" field. It's identical to VirtualmachineIDEQ.
func VirtualmachineID(v string) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldEQ(FieldVirtualmachineID, v))
}

// APIKey applies equality check predicate on the "api_key" field. It's identical to APIKeyEQ.
func APIKey(v string) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldEQ(FieldAPIKey, v))
}

// DeviceSecret applies equality check predicate on the "device_secret" field. It's identical to DeviceSecretEQ.
func DeviceSecret(v string) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldEQ(FieldDeviceSecret, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldEQ(FieldExpiresAt, v))
}

// RevokedAt applies equality check predicate on the "revoked_at" field. It's identical to RevokedAtEQ.
func RevokedAt(v time.Time) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldEQ(FieldRevokedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldEQ(FieldCreatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldNotNull(FieldDeletedAt))
}

// ModelIDEQ applies the EQ predicate on the "model_id" field.
func ModelIDEQ(v uuid.UUID) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldEQ(FieldModelID, v))
}

// ModelIDNEQ applies the NEQ predicate on the "model_id" field.
func ModelIDNEQ(v uuid.UUID) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldNEQ(FieldModelID, v))
}

// ModelIDIn applies the In predicate on the "model_id" field.
func ModelIDIn(vs ...uuid.UUID) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldIn(FieldModelID, vs...))
}

// ModelIDNotIn applies the NotIn predicate on the "model_id" field.
func ModelIDNotIn(vs ...uuid.UUID) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldNotIn(FieldModelID, vs...))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uuid.UUID) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uuid.UUID) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uuid.UUID) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v uuid.UUID) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v uuid.UUID) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v uuid.UUID) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v uuid.UUID) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldLTE(FieldUserID, v))
}

// VirtualmachineIDEQ applies the EQ predicate on the "virtualmachine_id" field.
func VirtualmachineIDEQ(v string) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldEQ(FieldVirtualmachineID, v))
}

// VirtualmachineIDNEQ applies the NEQ predicate on the "virtualmachine_id" field.
func VirtualmachineIDNEQ(v string) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldNEQ(FieldVirtualmachineID, v))
}

// VirtualmachineIDIn applies the In predicate on the "virtualmachine_id" field.
func VirtualmachineIDIn(vs ...string) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldIn(FieldVirtualmachineID, vs...))
}

// VirtualmachineIDNotIn applies the NotIn predicate on the "virtualmachine_id" field.
func VirtualmachineIDNotIn(vs ...string) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldNotIn(FieldVirtualmachineID, vs...))
}

// VirtualmachineIDGT applies the GT predicate on the "virtualmachine_id" field.
func VirtualmachineIDGT(v string) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldGT(FieldVirtualmachineID, v))
}

// VirtualmachineIDGTE applies the GTE predicate on the "virtualmachine_id" field.
func VirtualmachineIDGTE(v string) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldGTE(FieldVirtualmachineID, v))
}

// VirtualmachineIDLT applies the LT predicate on the "virtualmachine_id" field.
func VirtualmachineIDLT(v string) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldLT(FieldVirtualmachineID, v))
}

// VirtualmachineIDLTE applies the LTE predicate on the "virtualmachine_id" field.
func VirtualmachineIDLTE(v string) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldLTE(FieldVirtualmachineID, v))
}

// VirtualmachineIDContains applies the Contains predicate on the "virtualmachine_id" field.
func VirtualmachineIDContains(v string) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldContains(FieldVirtualmachineID, v))
}

// VirtualmachineIDHasPrefix applies the HasPrefix predicate on the "virtualmachine_id" field.
func VirtualmachineIDHasPrefix(v string) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldHasPrefix(FieldVirtualmachineID, v))
}

// VirtualmachineIDHasSuffix applies the HasSuffix predicate on the "virtualmachine_id" field.
func VirtualmachineIDHasSuffix(v string) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldHasSuffix(FieldVirtualmachineID, v))
}

// VirtualmachineIDIsNil applies the IsNil predicate on the "virtualmachine_id" field.
func VirtualmachineIDIsNil() predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldIsNull(FieldVirtualmachineID))
}

// VirtualmachineIDNotNil applies the NotNil predicate on the "virtualmachine_id" field.
func VirtualmachineIDNotNil() predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldNotNull(FieldVirtualmachineID))
}

// VirtualmachineIDEqualFold applies the EqualFold predicate on the "virtualmachine_id" field.
func VirtualmachineIDEqualFold(v string) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldEqualFold(FieldVirtualmachineID, v))
}

// VirtualmachineIDContainsFold applies the ContainsFold predicate on the "virtualmachine_id" field.
func VirtualmachineIDContainsFold(v string) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldContainsFold(FieldVirtualmachineID, v))
}

// APIKeyEQ applies the EQ predicate on the "api_key" field.
func APIKeyEQ(v string) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldEQ(FieldAPIKey, v))
}

// APIKeyNEQ applies the NEQ predicate on the "api_key" field.
func APIKeyNEQ(v string) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldNEQ(FieldAPIKey, v))
}

// APIKeyIn applies the In predicate on the "api_key" field.
func APIKeyIn(vs ...string) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldIn(FieldAPIKey, vs...))
}

// APIKeyNotIn applies the NotIn predicate on the "api_key" field.
func APIKeyNotIn(vs ...string) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldNotIn(FieldAPIKey, vs...))
}

// APIKeyGT applies the GT predicate on the "api_key" field.
func APIKeyGT(v string) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldGT(FieldAPIKey, v))
}

// APIKeyGTE applies the GTE predicate on the "api_key" field.
func APIKeyGTE(v string) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldGTE(FieldAPIKey, v))
}

// APIKeyLT applies the LT predicate on the "api_key" field.
func APIKeyLT(v string) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldLT(FieldAPIKey, v))
}

// APIKeyLTE applies the LTE predicate on the "api_key" field.
func APIKeyLTE(v string) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldLTE(FieldAPIKey, v))
}

// APIKeyContains applies the Contains predicate on the "api_key" field.
func APIKeyContains(v string) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldContains(FieldAPIKey, v))
}

// APIKeyHasPrefix applies the HasPrefix predicate on the "api_key" field.
func APIKeyHasPrefix(v string) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldHasPrefix(FieldAPIKey, v))
}

// APIKeyHasSuffix applies the HasSuffix predicate on the "api_key" field.
func APIKeyHasSuffix(v string) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldHasSuffix(FieldAPIKey, v))
}

// APIKeyEqualFold applies the EqualFold predicate on the "api_key" field.
func APIKeyEqualFold(v string) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldEqualFold(FieldAPIKey, v))
}

// APIKeyContainsFold applies the ContainsFold predicate on the "api_key" field.
func APIKeyContainsFold(v string) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldContainsFold(FieldAPIKey, v))
}

// DeviceSecretEQ applies the EQ predicate on the "device_secret" field.
func DeviceSecretEQ(v string) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldEQ(FieldDeviceSecret, v))
}

// DeviceSecretNEQ applies the NEQ predicate on the "device_secret" field.
func DeviceSecretNEQ(v string) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldNEQ(FieldDeviceSecret, v))
}

// DeviceSecretIn applies the In predicate on the "device_secret" field.
func DeviceSecretIn(vs ...string) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldIn(FieldDeviceSecret, vs...))
}

// DeviceSecretNotIn applies the NotIn predicate on the "device_secret" field.
func DeviceSecretNotIn(vs ...string) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldNotIn(FieldDeviceSecret, vs...))
}

// DeviceSecretGT applies the GT predicate on the "device_secret" field.
func DeviceSecretGT(v string) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldGT(FieldDeviceSecret, v))
}

// DeviceSecretGTE applies the GTE predicate on the "device_secret" field.
func DeviceSecretGTE(v string) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldGTE(FieldDeviceSecret, v))
}

// DeviceSecretLT applies the LT predicate on the "device_secret" field.
func DeviceSecretLT(v string) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldLT(FieldDeviceSecret, v))
}

// DeviceSecretLTE applies the LTE predicate on the "device_secret" field.
func DeviceSecretLTE(v string) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldLTE(FieldDeviceSecret, v))
}

// DeviceSecretContains applies the Contains predicate on the "device_secret" field.
func DeviceSecretContains(v string) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldContains(FieldDeviceSecret, v))
}

// DeviceSecretHasPrefix applies the HasPrefix predicate on the "device_secret" field.
func DeviceSecretHasPrefix(v string) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldHasPrefix(FieldDeviceSecret, v))
}

// DeviceSecretHasSuffix applies the HasSuffix predicate on the "device_secret" field.
func DeviceSecretHasSuffix(v string) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldHasSuffix(FieldDeviceSecret, v))
}

// DeviceSecretIsNil applies the IsNil predicate on the "device_secret" field.
func DeviceSecretIsNil() predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldIsNull(FieldDeviceSecret))
}

// DeviceSecretNotNil applies the NotNil predicate on the "device_secret" field.
func DeviceSecretNotNil() predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldNotNull(FieldDeviceSecret))
}

// DeviceSecretEqualFold applies the EqualFold predicate on the "device_secret" field.
func DeviceSecretEqualFold(v string) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldEqualFold(FieldDeviceSecret, v))
}

// DeviceSecretContainsFold applies the ContainsFold predicate on the "device_secret" field.
func DeviceSecretContainsFold(v string) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldContainsFold(FieldDeviceSecret, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldLTE(FieldExpiresAt, v))
}

// ExpiresAtIsNil applies the IsNil predicate on the "expires_at" field.
func ExpiresAtIsNil() predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldIsNull(FieldExpiresAt))
}

// ExpiresAtNotNil applies the NotNil predicate on the "expires_at" field.
func ExpiresAtNotNil() predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldNotNull(FieldExpiresAt))
}

// RevokedAtEQ applies the EQ predicate on the "revoked_at" field.
func RevokedAtEQ(v time.Time) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldEQ(FieldRevokedAt, v))
}

// RevokedAtNEQ applies the NEQ predicate on the "revoked_at" field.
func RevokedAtNEQ(v time.Time) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldNEQ(FieldRevokedAt, v))
}

// RevokedAtIn applies the In predicate on the "revoked_at" field.
func RevokedAtIn(vs ...time.Time) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldIn(FieldRevokedAt, vs...))
}

// RevokedAtNotIn applies the NotIn predicate on the "revoked_at" field.
func RevokedAtNotIn(vs ...time.Time) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldNotIn(FieldRevokedAt, vs...))
}

// RevokedAtGT applies the GT predicate on the "revoked_at" field.
func RevokedAtGT(v time.Time) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldGT(FieldRevokedAt, v))
}

// RevokedAtGTE applies the GTE predicate on the "revoked_at" field.
func RevokedAtGTE(v time.Time) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldGTE(FieldRevokedAt, v))
}

// RevokedAtLT applies the LT predicate on the "revoked_at" field.
func RevokedAtLT(v time.Time) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldLT(FieldRevokedAt, v))
}

// RevokedAtLTE applies the LTE predicate on the "revoked_at" field.
func RevokedAtLTE(v time.Time) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldLTE(FieldRevokedAt, v))
}

// RevokedAtIsNil applies the IsNil predicate on the "revoked_at" field.
func RevokedAtIsNil() predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldIsNull(FieldRevokedAt))
}

// RevokedAtNotNil applies the NotNil predicate on the "revoked_at" field.
func RevokedAtNotNil() predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldNotNull(FieldRevokedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.FieldLTE(FieldCreatedAt, v))
}

// HasModel applies the HasEdge predicate on the "model" edge.
func HasModel() predicate.ModelApiKey {
	return predicate.ModelApiKey(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ModelTable, ModelColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasModelWith applies the HasEdge predicate on the "model" edge with a given conditions (other predicates).
func HasModelWith(preds ...predicate.Model) predicate.ModelApiKey {
	return predicate.ModelApiKey(func(s *sql.Selector) {
		step := newModelStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ModelApiKey) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ModelApiKey) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ModelApiKey) predicate.ModelApiKey {
	return predicate.ModelApiKey(sql.NotPredicates(p))
}
