// Code generated by ent, DO NOT EDIT.

package dataapipricing

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the dataapipricing type in the database.
	Label = "data_api_pricing"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAPICode holds the string denoting the api_code field in the database.
	FieldAPICode = "api_code"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldGroup holds the string denoting the group field in the database.
	FieldGroup = "group"
	// FieldCategory holds the string denoting the category field in the database.
	FieldCategory = "category"
	// FieldMethod holds the string denoting the method field in the database.
	FieldMethod = "method"
	// FieldPath holds the string denoting the path field in the database.
	FieldPath = "path"
	// FieldSummary holds the string denoting the summary field in the database.
	FieldSummary = "summary"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldCreditsPerCall holds the string denoting the credits_per_call field in the database.
	FieldCreditsPerCall = "credits_per_call"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldNeedAPIKey holds the string denoting the need_api_key field in the database.
	FieldNeedAPIKey = "need_api_key"
	// FieldParams holds the string denoting the params field in the database.
	FieldParams = "params"
	// FieldResponseFields holds the string denoting the response_fields field in the database.
	FieldResponseFields = "response_fields"
	// FieldExampleRequest holds the string denoting the example_request field in the database.
	FieldExampleRequest = "example_request"
	// FieldExampleResponse holds the string denoting the example_response field in the database.
	FieldExampleResponse = "example_response"
	// FieldSortOrder holds the string denoting the sort_order field in the database.
	FieldSortOrder = "sort_order"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the dataapipricing in the database.
	Table = "data_api_pricings"
)

// Columns holds all SQL columns for dataapipricing fields.
var Columns = []string{
	FieldID,
	FieldAPICode,
	FieldName,
	FieldGroup,
	FieldCategory,
	FieldMethod,
	FieldPath,
	FieldSummary,
	FieldDescription,
	FieldCreditsPerCall,
	FieldEnabled,
	FieldNeedAPIKey,
	FieldParams,
	FieldResponseFields,
	FieldExampleRequest,
	FieldExampleResponse,
	FieldSortOrder,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// APICodeValidator is a validator for the "api_code" field. It is called by the builders before save.
	APICodeValidator func(string) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultGroup holds the default value on creation for the "group" field.
	DefaultGroup string
	// CategoryValidator is a validator for the "category" field. It is called by the builders before save.
	CategoryValidator func(string) error
	// DefaultMethod holds the default value on creation for the "method" field.
	DefaultMethod string
	// PathValidator is a validator for the "path" field. It is called by the builders before save.
	PathValidator func(string) error
	// DefaultCreditsPerCall holds the default value on creation for the "credits_per_call" field.
	DefaultCreditsPerCall int64
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultNeedAPIKey holds the default value on creation for the "need_api_key" field.
	DefaultNeedAPIKey bool
	// DefaultSortOrder holds the default value on creation for the "sort_order" field.
	DefaultSortOrder int
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the DataApiPricing queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByAPICode orders the results by the api_code field.
func ByAPICode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPICode, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByGroup orders the results by the group field.
func ByGroup(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroup, opts...).ToFunc()
}

// ByCategory orders the results by the category field.
func ByCategory(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCategory, opts...).ToFunc()
}

// ByMethod orders the results by the method field.
func ByMethod(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMethod, opts...).ToFunc()
}

// ByPath orders the results by the path field.
func ByPath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPath, opts...).ToFunc()
}

// BySummary orders the results by the summary field.
func BySummary(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSummary, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByCreditsPerCall orders the results by the credits_per_call field.
func ByCreditsPerCall(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreditsPerCall, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByNeedAPIKey orders the results by the need_api_key field.
func ByNeedAPIKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNeedAPIKey, opts...).ToFunc()
}

// ByExampleRequest orders the results by the example_request field.
func ByExampleRequest(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExampleRequest, opts...).ToFunc()
}

// ByExampleResponse orders the results by the example_response field.
func ByExampleResponse(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExampleResponse, opts...).ToFunc()
}

// BySortOrder orders the results by the sort_order field.
func BySortOrder(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSortOrder, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
