// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/nidao003/mclaw/backend/db/dataapipricing"
	"github.com/nidao003/mclaw/backend/db/predicate"
)

// DataApiPricingQuery is the builder for querying DataApiPricing entities.
type DataApiPricingQuery struct {
	config
	ctx        *QueryContext
	order      []dataapipricing.OrderOption
	inters     []Interceptor
	predicates []predicate.DataApiPricing
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the DataApiPricingQuery builder.
func (_q *DataApiPricingQuery) Where(ps ...predicate.DataApiPricing) *DataApiPricingQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *DataApiPricingQuery) Limit(limit int) *DataApiPricingQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *DataApiPricingQuery) Offset(offset int) *DataApiPricingQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *DataApiPricingQuery) Unique(unique bool) *DataApiPricingQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *DataApiPricingQuery) Order(o ...dataapipricing.OrderOption) *DataApiPricingQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// First returns the first DataApiPricing entity from the query.
// Returns a *NotFoundError when no DataApiPricing was found.
func (_q *DataApiPricingQuery) First(ctx context.Context) (*DataApiPricing, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{dataapipricing.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *DataApiPricingQuery) FirstX(ctx context.Context) *DataApiPricing {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first DataApiPricing ID from the query.
// Returns a *NotFoundError when no DataApiPricing ID was found.
func (_q *DataApiPricingQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{dataapipricing.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *DataApiPricingQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single DataApiPricing entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one DataApiPricing entity is found.
// Returns a *NotFoundError when no DataApiPricing entities are found.
func (_q *DataApiPricingQuery) Only(ctx context.Context) (*DataApiPricing, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{dataapipricing.Label}
	default:
		return nil, &NotSingularError{dataapipricing.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *DataApiPricingQuery) OnlyX(ctx context.Context) *DataApiPricing {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only DataApiPricing ID in the query.
// Returns a *NotSingularError when more than one DataApiPricing ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *DataApiPricingQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{dataapipricing.Label}
	default:
		err = &NotSingularError{dataapipricing.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *DataApiPricingQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of DataApiPricings.
func (_q *DataApiPricingQuery) All(ctx context.Context) ([]*DataApiPricing, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*DataApiPricing, *DataApiPricingQuery]()
	return withInterceptors[[]*DataApiPricing](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *DataApiPricingQuery) AllX(ctx context.Context) []*DataApiPricing {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of DataApiPricing IDs.
func (_q *DataApiPricingQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(dataapipricing.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *DataApiPricingQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *DataApiPricingQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*DataApiPricingQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *DataApiPricingQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *DataApiPricingQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("db: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *DataApiPricingQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the DataApiPricingQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *DataApiPricingQuery) Clone() *DataApiPricingQuery {
	if _q == nil {
		return nil
	}
	return &DataApiPricingQuery{
		config:     _q.config,
		ctx:        _q.ctx.Clone(),
		order:      append([]dataapipricing.OrderOption{}, _q.order...),
		inters:     append([]Interceptor{}, _q.inters...),
		predicates: append([]predicate.DataApiPricing{}, _q.predicates...),
		// clone intermediate query.
		sql:       _q.sql.Clone(),
		path:      _q.path,
		modifiers: append([]func(*sql.Selector){}, _q.modifiers...),
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		APICode string `json:"api_code,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.DataApiPricing.Query().
//		GroupBy(dataapipricing.FieldAPICode).
//		Aggregate(db.Count()).
//		Scan(ctx, &v)
func (_q *DataApiPricingQuery) GroupBy(field string, fields ...string) *DataApiPricingGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &DataApiPricingGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = dataapipricing.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		APICode string `json:"api_code,omitempty"`
//	}
//
//	client.DataApiPricing.Query().
//		Select(dataapipricing.FieldAPICode).
//		Scan(ctx, &v)
func (_q *DataApiPricingQuery) Select(fields ...string) *DataApiPricingSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &DataApiPricingSelect{DataApiPricingQuery: _q}
	sbuild.label = dataapipricing.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a DataApiPricingSelect configured with the given aggregations.
func (_q *DataApiPricingQuery) Aggregate(fns ...AggregateFunc) *DataApiPricingSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *DataApiPricingQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("db: uninitialized interceptor (forgotten import db/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !dataapipricing.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("db: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *DataApiPricingQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*DataApiPricing, error) {
	var (
		nodes = []*DataApiPricing{}
		_spec = _q.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*DataApiPricing).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &DataApiPricing{config: _q.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (_q *DataApiPricingQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *DataApiPricingQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(dataapipricing.Table, dataapipricing.Columns, sqlgraph.NewFieldSpec(dataapipricing.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, dataapipricing.FieldID)
		for i := range fields {
			if fields[i] != dataapipricing.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *DataApiPricingQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(dataapipricing.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = dataapipricing.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *DataApiPricingQuery) ForUpdate(opts ...sql.LockOption) *DataApiPricingQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *DataApiPricingQuery) ForShare(opts ...sql.LockOption) *DataApiPricingQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_q *DataApiPricingQuery) Modify(modifiers ...func(s *sql.Selector)) *DataApiPricingSelect {
	_q.modifiers = append(_q.modifiers, modifiers...)
	return _q.Select()
}

// DataApiPricingGroupBy is the group-by builder for DataApiPricing entities.
type DataApiPricingGroupBy struct {
	selector
	build *DataApiPricingQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *DataApiPricingGroupBy) Aggregate(fns ...AggregateFunc) *DataApiPricingGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *DataApiPricingGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DataApiPricingQuery, *DataApiPricingGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *DataApiPricingGroupBy) sqlScan(ctx context.Context, root *DataApiPricingQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// DataApiPricingSelect is the builder for selecting fields of DataApiPricing entities.
type DataApiPricingSelect struct {
	*DataApiPricingQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *DataApiPricingSelect) Aggregate(fns ...AggregateFunc) *DataApiPricingSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *DataApiPricingSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DataApiPricingQuery, *DataApiPricingSelect](ctx, _s.DataApiPricingQuery, _s, _s.inters, v)
}

func (_s *DataApiPricingSelect) sqlScan(ctx context.Context, root *DataApiPricingQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_s *DataApiPricingSelect) Modify(modifiers ...func(s *sql.Selector)) *DataApiPricingSelect {
	_s.modifiers = append(_s.modifiers, modifiers...)
	return _s
}
