// Code generated by ent, DO NOT EDIT.

package db

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/nidao003/mclaw/backend/db/dataapipricing"
)

// DataApiPricing is the model entity for the DataApiPricing schema.
type DataApiPricing struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// APICode holds the value of the "api_code" field.
	APICode string `json:"api_code,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Group holds the value of the "group" field.
	Group string `json:"group,omitempty"`
	// Category holds the value of the "category" field.
	Category string `json:"category,omitempty"`
	// Method holds the value of the "method" field.
	Method string `json:"method,omitempty"`
	// Path holds the value of the "path" field.
	Path string `json:"path,omitempty"`
	// Summary holds the value of the "summary" field.
	Summary string `json:"summary,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// CreditsPerCall holds the value of the "credits_per_call" field.
	CreditsPerCall int64 `json:"credits_per_call,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// NeedAPIKey holds the value of the "need_api_key" field.
	NeedAPIKey bool `json:"need_api_key,omitempty"`
	// Params holds the value of the "params" field.
	Params []map[string]interface{} `json:"params,omitempty"`
	// ResponseFields holds the value of the "response_fields" field.
	ResponseFields []map[string]interface{} `json:"response_fields,omitempty"`
	// ExampleRequest holds the value of the "example_request" field.
	ExampleRequest string `json:"example_request,omitempty"`
	// ExampleResponse holds the value of the "example_response" field.
	ExampleResponse string `json:"example_response,omitempty"`
	// SortOrder holds the value of the "sort_order" field.
	SortOrder int `json:"sort_order,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DataApiPricing) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case dataapipricing.FieldParams, dataapipricing.FieldResponseFields:
			values[i] = new([]byte)
		case dataapipricing.FieldEnabled, dataapipricing.FieldNeedAPIKey:
			values[i] = new(sql.NullBool)
		case dataapipricing.FieldCreditsPerCall, dataapipricing.FieldSortOrder:
			values[i] = new(sql.NullInt64)
		case dataapipricing.FieldAPICode, dataapipricing.FieldName, dataapipricing.FieldGroup, dataapipricing.FieldCategory, dataapipricing.FieldMethod, dataapipricing.FieldPath, dataapipricing.FieldSummary, dataapipricing.FieldDescription, dataapipricing.FieldExampleRequest, dataapipricing.FieldExampleResponse:
			values[i] = new(sql.NullString)
		case dataapipricing.FieldCreatedAt, dataapipricing.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case dataapipricing.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DataApiPricing fields.
func (_m *DataApiPricing) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case dataapipricing.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case dataapipricing.FieldAPICode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field api_code", values[i])
			} else if value.Valid {
				_m.APICode = value.String
			}
		case dataapipricing.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case dataapipricing.FieldGroup:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field group", values[i])
			} else if value.Valid {
				_m.Group = value.String
			}
		case dataapipricing.FieldCategory:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field category", values[i])
			} else if value.Valid {
				_m.Category = value.String
			}
		case dataapipricing.FieldMethod:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field method", values[i])
			} else if value.Valid {
				_m.Method = value.String
			}
		case dataapipricing.FieldPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field path", values[i])
			} else if value.Valid {
				_m.Path = value.String
			}
		case dataapipricing.FieldSummary:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field summary", values[i])
			} else if value.Valid {
				_m.Summary = value.String
			}
		case dataapipricing.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case dataapipricing.FieldCreditsPerCall:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field credits_per_call", values[i])
			} else if value.Valid {
				_m.CreditsPerCall = value.Int64
			}
		case dataapipricing.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case dataapipricing.FieldNeedAPIKey:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field need_api_key", values[i])
			} else if value.Valid {
				_m.NeedAPIKey = value.Bool
			}
		case dataapipricing.FieldParams:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field params", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Params); err != nil {
					return fmt.Errorf("unmarshal field params: %w", err)
				}
			}
		case dataapipricing.FieldResponseFields:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field response_fields", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ResponseFields); err != nil {
					return fmt.Errorf("unmarshal field response_fields: %w", err)
				}
			}
		case dataapipricing.FieldExampleRequest:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field example_request", values[i])
			} else if value.Valid {
				_m.ExampleRequest = value.String
			}
		case dataapipricing.FieldExampleResponse:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field example_response", values[i])
			} else if value.Valid {
				_m.ExampleResponse = value.String
			}
		case dataapipricing.FieldSortOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort_order", values[i])
			} else if value.Valid {
				_m.SortOrder = int(value.Int64)
			}
		case dataapipricing.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case dataapipricing.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DataApiPricing.
// This includes values selected through modifiers, order, etc.
func (_m *DataApiPricing) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this DataApiPricing.
// Note that you need to call DataApiPricing.Unwrap() before calling this method if this DataApiPricing
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *DataApiPricing) Update() *DataApiPricingUpdateOne {
	return NewDataApiPricingClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the DataApiPricing entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *DataApiPricing) Unwrap() *DataApiPricing {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("db: DataApiPricing is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *DataApiPricing) String() string {
	var builder strings.Builder
	builder.WriteString("DataApiPricing(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("api_code=")
	builder.WriteString(_m.APICode)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("group=")
	builder.WriteString(_m.Group)
	builder.WriteString(", ")
	builder.WriteString("category=")
	builder.WriteString(_m.Category)
	builder.WriteString(", ")
	builder.WriteString("method=")
	builder.WriteString(_m.Method)
	builder.WriteString(", ")
	builder.WriteString("path=")
	builder.WriteString(_m.Path)
	builder.WriteString(", ")
	builder.WriteString("summary=")
	builder.WriteString(_m.Summary)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("credits_per_call=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreditsPerCall))
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("need_api_key=")
	builder.WriteString(fmt.Sprintf("%v", _m.NeedAPIKey))
	builder.WriteString(", ")
	builder.WriteString("params=")
	builder.WriteString(fmt.Sprintf("%v", _m.Params))
	builder.WriteString(", ")
	builder.WriteString("response_fields=")
	builder.WriteString(fmt.Sprintf("%v", _m.ResponseFields))
	builder.WriteString(", ")
	builder.WriteString("example_request=")
	builder.WriteString(_m.ExampleRequest)
	builder.WriteString(", ")
	builder.WriteString("example_response=")
	builder.WriteString(_m.ExampleResponse)
	builder.WriteString(", ")
	builder.WriteString("sort_order=")
	builder.WriteString(fmt.Sprintf("%v", _m.SortOrder))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// DataApiPricings is a parsable slice of DataApiPricing.
type DataApiPricings []*DataApiPricing
