// Code generated by ent, DO NOT EDIT.

package db

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/nidao003/mclaw/backend/db/exchangecode"
)

// ExchangeCode is the model entity for the ExchangeCode schema.
type ExchangeCode struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Code holds the value of the "code" field.
	Code string `json:"code,omitempty"`
	// Credits holds the value of the "credits" field.
	Credits int64 `json:"credits,omitempty"`
	// MaxUses holds the value of the "max_uses" field.
	MaxUses int `json:"max_uses,omitempty"`
	// UsedCount holds the value of the "used_count" field.
	UsedCount int `json:"used_count,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy uuid.UUID `json:"created_by,omitempty"`
	// IsActive holds the value of the "is_active" field.
	IsActive bool `json:"is_active,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ExchangeCode) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case exchangecode.FieldIsActive:
			values[i] = new(sql.NullBool)
		case exchangecode.FieldCredits, exchangecode.FieldMaxUses, exchangecode.FieldUsedCount:
			values[i] = new(sql.NullInt64)
		case exchangecode.FieldCode:
			values[i] = new(sql.NullString)
		case exchangecode.FieldExpiresAt, exchangecode.FieldCreatedAt, exchangecode.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case exchangecode.FieldID, exchangecode.FieldCreatedBy:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ExchangeCode fields.
func (_m *ExchangeCode) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case exchangecode.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case exchangecode.FieldCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code", values[i])
			} else if value.Valid {
				_m.Code = value.String
			}
		case exchangecode.FieldCredits:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field credits", values[i])
			} else if value.Valid {
				_m.Credits = value.Int64
			}
		case exchangecode.FieldMaxUses:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field max_uses", values[i])
			} else if value.Valid {
				_m.MaxUses = int(value.Int64)
			}
		case exchangecode.FieldUsedCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field used_count", values[i])
			} else if value.Valid {
				_m.UsedCount = int(value.Int64)
			}
		case exchangecode.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		case exchangecode.FieldCreatedBy:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value != nil {
				_m.CreatedBy = *value
			}
		case exchangecode.FieldIsActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_active", values[i])
			} else if value.Valid {
				_m.IsActive = value.Bool
			}
		case exchangecode.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case exchangecode.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ExchangeCode.
// This includes values selected through modifiers, order, etc.
func (_m *ExchangeCode) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ExchangeCode.
// Note that you need to call ExchangeCode.Unwrap() before calling this method if this ExchangeCode
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ExchangeCode) Update() *ExchangeCodeUpdateOne {
	return NewExchangeCodeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ExchangeCode entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ExchangeCode) Unwrap() *ExchangeCode {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("db: ExchangeCode is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ExchangeCode) String() string {
	var builder strings.Builder
	builder.WriteString("ExchangeCode(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("code=")
	builder.WriteString(_m.Code)
	builder.WriteString(", ")
	builder.WriteString("credits=")
	builder.WriteString(fmt.Sprintf("%v", _m.Credits))
	builder.WriteString(", ")
	builder.WriteString("max_uses=")
	builder.WriteString(fmt.Sprintf("%v", _m.MaxUses))
	builder.WriteString(", ")
	builder.WriteString("used_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.UsedCount))
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedBy))
	builder.WriteString(", ")
	builder.WriteString("is_active=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsActive))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ExchangeCodes is a parsable slice of ExchangeCode.
type ExchangeCodes []*ExchangeCode
