// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/nidao003/mclaw/backend/db/exchangecode"
)

// ExchangeCodeCreate is the builder for creating a ExchangeCode entity.
type ExchangeCodeCreate struct {
	config
	mutation *ExchangeCodeMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCode sets the "code" field.
func (_c *ExchangeCodeCreate) SetCode(v string) *ExchangeCodeCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetCredits sets the "credits" field.
func (_c *ExchangeCodeCreate) SetCredits(v int64) *ExchangeCodeCreate {
	_c.mutation.SetCredits(v)
	return _c
}

// SetMaxUses sets the "max_uses" field.
func (_c *ExchangeCodeCreate) SetMaxUses(v int) *ExchangeCodeCreate {
	_c.mutation.SetMaxUses(v)
	return _c
}

// SetNillableMaxUses sets the "max_uses" field if the given value is not nil.
func (_c *ExchangeCodeCreate) SetNillableMaxUses(v *int) *ExchangeCodeCreate {
	if v != nil {
		_c.SetMaxUses(*v)
	}
	return _c
}

// SetUsedCount sets the "used_count" field.
func (_c *ExchangeCodeCreate) SetUsedCount(v int) *ExchangeCodeCreate {
	_c.mutation.SetUsedCount(v)
	return _c
}

// SetNillableUsedCount sets the "used_count" field if the given value is not nil.
func (_c *ExchangeCodeCreate) SetNillableUsedCount(v *int) *ExchangeCodeCreate {
	if v != nil {
		_c.SetUsedCount(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *ExchangeCodeCreate) SetExpiresAt(v time.Time) *ExchangeCodeCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *ExchangeCodeCreate) SetNillableExpiresAt(v *time.Time) *ExchangeCodeCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *ExchangeCodeCreate) SetCreatedBy(v uuid.UUID) *ExchangeCodeCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetIsActive sets the "is_active" field.
func (_c *ExchangeCodeCreate) SetIsActive(v bool) *ExchangeCodeCreate {
	_c.mutation.SetIsActive(v)
	return _c
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_c *ExchangeCodeCreate) SetNillableIsActive(v *bool) *ExchangeCodeCreate {
	if v != nil {
		_c.SetIsActive(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ExchangeCodeCreate) SetCreatedAt(v time.Time) *ExchangeCodeCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ExchangeCodeCreate) SetNillableCreatedAt(v *time.Time) *ExchangeCodeCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ExchangeCodeCreate) SetUpdatedAt(v time.Time) *ExchangeCodeCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ExchangeCodeCreate) SetNillableUpdatedAt(v *time.Time) *ExchangeCodeCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ExchangeCodeCreate) SetID(v uuid.UUID) *ExchangeCodeCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the ExchangeCodeMutation object of the builder.
func (_c *ExchangeCodeCreate) Mutation() *ExchangeCodeMutation {
	return _c.mutation
}

// Save creates the ExchangeCode in the database.
func (_c *ExchangeCodeCreate) Save(ctx context.Context) (*ExchangeCode, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ExchangeCodeCreate) SaveX(ctx context.Context) *ExchangeCode {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ExchangeCodeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ExchangeCodeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ExchangeCodeCreate) defaults() {
	if _, ok := _c.mutation.MaxUses(); !ok {
		v := exchangecode.DefaultMaxUses
		_c.mutation.SetMaxUses(v)
	}
	if _, ok := _c.mutation.UsedCount(); !ok {
		v := exchangecode.DefaultUsedCount
		_c.mutation.SetUsedCount(v)
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		v := exchangecode.DefaultIsActive
		_c.mutation.SetIsActive(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := exchangecode.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := exchangecode.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ExchangeCodeCreate) check() error {
	if _, ok := _c.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`db: missing required field "ExchangeCode.code"`)}
	}
	if v, ok := _c.mutation.Code(); ok {
		if err := exchangecode.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`db: validator failed for field "ExchangeCode.code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Credits(); !ok {
		return &ValidationError{Name: "credits", err: errors.New(`db: missing required field "ExchangeCode.credits"`)}
	}
	if _, ok := _c.mutation.MaxUses(); !ok {
		return &ValidationError{Name: "max_uses", err: errors.New(`db: missing required field "ExchangeCode.max_uses"`)}
	}
	if _, ok := _c.mutation.UsedCount(); !ok {
		return &ValidationError{Name: "used_count", err: errors.New(`db: missing required field "ExchangeCode.used_count"`)}
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`db: missing required field "ExchangeCode.created_by"`)}
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		return &ValidationError{Name: "is_active", err: errors.New(`db: missing required field "ExchangeCode.is_active"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`db: missing required field "ExchangeCode.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`db: missing required field "ExchangeCode.updated_at"`)}
	}
	return nil
}

func (_c *ExchangeCodeCreate) sqlSave(ctx context.Context) (*ExchangeCode, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ExchangeCodeCreate) createSpec() (*ExchangeCode, *sqlgraph.CreateSpec) {
	var (
		_node = &ExchangeCode{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(exchangecode.Table, sqlgraph.NewFieldSpec(exchangecode.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(exchangecode.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := _c.mutation.Credits(); ok {
		_spec.SetField(exchangecode.FieldCredits, field.TypeInt64, value)
		_node.Credits = value
	}
	if value, ok := _c.mutation.MaxUses(); ok {
		_spec.SetField(exchangecode.FieldMaxUses, field.TypeInt, value)
		_node.MaxUses = value
	}
	if value, ok := _c.mutation.UsedCount(); ok {
		_spec.SetField(exchangecode.FieldUsedCount, field.TypeInt, value)
		_node.UsedCount = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(exchangecode.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(exchangecode.FieldCreatedBy, field.TypeUUID, value)
		_node.CreatedBy = value
	}
	if value, ok := _c.mutation.IsActive(); ok {
		_spec.SetField(exchangecode.FieldIsActive, field.TypeBool, value)
		_node.IsActive = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(exchangecode.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(exchangecode.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ExchangeCode.Create().
//		SetCode(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ExchangeCodeUpsert) {
//			SetCode(v+v).
//		}).
//		Exec(ctx)
func (_c *ExchangeCodeCreate) OnConflict(opts ...sql.ConflictOption) *ExchangeCodeUpsertOne {
	_c.conflict = opts
	return &ExchangeCodeUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ExchangeCode.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ExchangeCodeCreate) OnConflictColumns(columns ...string) *ExchangeCodeUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ExchangeCodeUpsertOne{
		create: _c,
	}
}

type (
	// ExchangeCodeUpsertOne is the builder for "upsert"-ing
	//  one ExchangeCode node.
	ExchangeCodeUpsertOne struct {
		create *ExchangeCodeCreate
	}

	// ExchangeCodeUpsert is the "OnConflict" setter.
	ExchangeCodeUpsert struct {
		*sql.UpdateSet
	}
)

// SetCode sets the "code" field.
func (u *ExchangeCodeUpsert) SetCode(v string) *ExchangeCodeUpsert {
	u.Set(exchangecode.FieldCode, v)
	return u
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *ExchangeCodeUpsert) UpdateCode() *ExchangeCodeUpsert {
	u.SetExcluded(exchangecode.FieldCode)
	return u
}

// SetCredits sets the "credits" field.
func (u *ExchangeCodeUpsert) SetCredits(v int64) *ExchangeCodeUpsert {
	u.Set(exchangecode.FieldCredits, v)
	return u
}

// UpdateCredits sets the "credits" field to the value that was provided on create.
func (u *ExchangeCodeUpsert) UpdateCredits() *ExchangeCodeUpsert {
	u.SetExcluded(exchangecode.FieldCredits)
	return u
}

// AddCredits adds v to the "credits" field.
func (u *ExchangeCodeUpsert) AddCredits(v int64) *ExchangeCodeUpsert {
	u.Add(exchangecode.FieldCredits, v)
	return u
}

// SetMaxUses sets the "max_uses" field.
func (u *ExchangeCodeUpsert) SetMaxUses(v int) *ExchangeCodeUpsert {
	u.Set(exchangecode.FieldMaxUses, v)
	return u
}

// UpdateMaxUses sets the "max_uses" field to the value that was provided on create.
func (u *ExchangeCodeUpsert) UpdateMaxUses() *ExchangeCodeUpsert {
	u.SetExcluded(exchangecode.FieldMaxUses)
	return u
}

// AddMaxUses adds v to the "max_uses" field.
func (u *ExchangeCodeUpsert) AddMaxUses(v int) *ExchangeCodeUpsert {
	u.Add(exchangecode.FieldMaxUses, v)
	return u
}

// SetUsedCount sets the "used_count" field.
func (u *ExchangeCodeUpsert) SetUsedCount(v int) *ExchangeCodeUpsert {
	u.Set(exchangecode.FieldUsedCount, v)
	return u
}

// UpdateUsedCount sets the "used_count" field to the value that was provided on create.
func (u *ExchangeCodeUpsert) UpdateUsedCount() *ExchangeCodeUpsert {
	u.SetExcluded(exchangecode.FieldUsedCount)
	return u
}

// AddUsedCount adds v to the "used_count" field.
func (u *ExchangeCodeUpsert) AddUsedCount(v int) *ExchangeCodeUpsert {
	u.Add(exchangecode.FieldUsedCount, v)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *ExchangeCodeUpsert) SetExpiresAt(v time.Time) *ExchangeCodeUpsert {
	u.Set(exchangecode.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *ExchangeCodeUpsert) UpdateExpiresAt() *ExchangeCodeUpsert {
	u.SetExcluded(exchangecode.FieldExpiresAt)
	return u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *ExchangeCodeUpsert) ClearExpiresAt() *ExchangeCodeUpsert {
	u.SetNull(exchangecode.FieldExpiresAt)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *ExchangeCodeUpsert) SetCreatedBy(v uuid.UUID) *ExchangeCodeUpsert {
	u.Set(exchangecode.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *ExchangeCodeUpsert) UpdateCreatedBy() *ExchangeCodeUpsert {
	u.SetExcluded(exchangecode.FieldCreatedBy)
	return u
}

// SetIsActive sets the "is_active" field.
func (u *ExchangeCodeUpsert) SetIsActive(v bool) *ExchangeCodeUpsert {
	u.Set(exchangecode.FieldIsActive, v)
	return u
}

// UpdateIsActive sets the "is_active" field to the value that was provided on create.
func (u *ExchangeCodeUpsert) UpdateIsActive() *ExchangeCodeUpsert {
	u.SetExcluded(exchangecode.FieldIsActive)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *ExchangeCodeUpsert) SetCreatedAt(v time.Time) *ExchangeCodeUpsert {
	u.Set(exchangecode.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *ExchangeCodeUpsert) UpdateCreatedAt() *ExchangeCodeUpsert {
	u.SetExcluded(exchangecode.FieldCreatedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ExchangeCodeUpsert) SetUpdatedAt(v time.Time) *ExchangeCodeUpsert {
	u.Set(exchangecode.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ExchangeCodeUpsert) UpdateUpdatedAt() *ExchangeCodeUpsert {
	u.SetExcluded(exchangecode.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.ExchangeCode.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(exchangecode.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ExchangeCodeUpsertOne) UpdateNewValues() *ExchangeCodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(exchangecode.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ExchangeCode.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ExchangeCodeUpsertOne) Ignore() *ExchangeCodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ExchangeCodeUpsertOne) DoNothing() *ExchangeCodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ExchangeCodeCreate.OnConflict
// documentation for more info.
func (u *ExchangeCodeUpsertOne) Update(set func(*ExchangeCodeUpsert)) *ExchangeCodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ExchangeCodeUpsert{UpdateSet: update})
	}))
	return u
}

// SetCode sets the "code" field.
func (u *ExchangeCodeUpsertOne) SetCode(v string) *ExchangeCodeUpsertOne {
	return u.Update(func(s *ExchangeCodeUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *ExchangeCodeUpsertOne) UpdateCode() *ExchangeCodeUpsertOne {
	return u.Update(func(s *ExchangeCodeUpsert) {
		s.UpdateCode()
	})
}

// SetCredits sets the "credits" field.
func (u *ExchangeCodeUpsertOne) SetCredits(v int64) *ExchangeCodeUpsertOne {
	return u.Update(func(s *ExchangeCodeUpsert) {
		s.SetCredits(v)
	})
}

// AddCredits adds v to the "credits" field.
func (u *ExchangeCodeUpsertOne) AddCredits(v int64) *ExchangeCodeUpsertOne {
	return u.Update(func(s *ExchangeCodeUpsert) {
		s.AddCredits(v)
	})
}

// UpdateCredits sets the "credits" field to the value that was provided on create.
func (u *ExchangeCodeUpsertOne) UpdateCredits() *ExchangeCodeUpsertOne {
	return u.Update(func(s *ExchangeCodeUpsert) {
		s.UpdateCredits()
	})
}

// SetMaxUses sets the "max_uses" field.
func (u *ExchangeCodeUpsertOne) SetMaxUses(v int) *ExchangeCodeUpsertOne {
	return u.Update(func(s *ExchangeCodeUpsert) {
		s.SetMaxUses(v)
	})
}

// AddMaxUses adds v to the "max_uses" field.
func (u *ExchangeCodeUpsertOne) AddMaxUses(v int) *ExchangeCodeUpsertOne {
	return u.Update(func(s *ExchangeCodeUpsert) {
		s.AddMaxUses(v)
	})
}

// UpdateMaxUses sets the "max_uses" field to the value that was provided on create.
func (u *ExchangeCodeUpsertOne) UpdateMaxUses() *ExchangeCodeUpsertOne {
	return u.Update(func(s *ExchangeCodeUpsert) {
		s.UpdateMaxUses()
	})
}

// SetUsedCount sets the "used_count" field.
func (u *ExchangeCodeUpsertOne) SetUsedCount(v int) *ExchangeCodeUpsertOne {
	return u.Update(func(s *ExchangeCodeUpsert) {
		s.SetUsedCount(v)
	})
}

// AddUsedCount adds v to the "used_count" field.
func (u *ExchangeCodeUpsertOne) AddUsedCount(v int) *ExchangeCodeUpsertOne {
	return u.Update(func(s *ExchangeCodeUpsert) {
		s.AddUsedCount(v)
	})
}

// UpdateUsedCount sets the "used_count" field to the value that was provided on create.
func (u *ExchangeCodeUpsertOne) UpdateUsedCount() *ExchangeCodeUpsertOne {
	return u.Update(func(s *ExchangeCodeUpsert) {
		s.UpdateUsedCount()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *ExchangeCodeUpsertOne) SetExpiresAt(v time.Time) *ExchangeCodeUpsertOne {
	return u.Update(func(s *ExchangeCodeUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *ExchangeCodeUpsertOne) UpdateExpiresAt() *ExchangeCodeUpsertOne {
	return u.Update(func(s *ExchangeCodeUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *ExchangeCodeUpsertOne) ClearExpiresAt() *ExchangeCodeUpsertOne {
	return u.Update(func(s *ExchangeCodeUpsert) {
		s.ClearExpiresAt()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *ExchangeCodeUpsertOne) SetCreatedBy(v uuid.UUID) *ExchangeCodeUpsertOne {
	return u.Update(func(s *ExchangeCodeUpsert) {
		s.SetCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *ExchangeCodeUpsertOne) UpdateCreatedBy() *ExchangeCodeUpsertOne {
	return u.Update(func(s *ExchangeCodeUpsert) {
		s.UpdateCreatedBy()
	})
}

// SetIsActive sets the "is_active" field.
func (u *ExchangeCodeUpsertOne) SetIsActive(v bool) *ExchangeCodeUpsertOne {
	return u.Update(func(s *ExchangeCodeUpsert) {
		s.SetIsActive(v)
	})
}

// UpdateIsActive sets the "is_active" field to the value that was provided on create.
func (u *ExchangeCodeUpsertOne) UpdateIsActive() *ExchangeCodeUpsertOne {
	return u.Update(func(s *ExchangeCodeUpsert) {
		s.UpdateIsActive()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *ExchangeCodeUpsertOne) SetCreatedAt(v time.Time) *ExchangeCodeUpsertOne {
	return u.Update(func(s *ExchangeCodeUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *ExchangeCodeUpsertOne) UpdateCreatedAt() *ExchangeCodeUpsertOne {
	return u.Update(func(s *ExchangeCodeUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ExchangeCodeUpsertOne) SetUpdatedAt(v time.Time) *ExchangeCodeUpsertOne {
	return u.Update(func(s *ExchangeCodeUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ExchangeCodeUpsertOne) UpdateUpdatedAt() *ExchangeCodeUpsertOne {
	return u.Update(func(s *ExchangeCodeUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ExchangeCodeUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("db: missing options for ExchangeCodeCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ExchangeCodeUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ExchangeCodeUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("db: ExchangeCodeUpsertOne.ID is not supported by MySQL driver. Use ExchangeCodeUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ExchangeCodeUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ExchangeCodeCreateBulk is the builder for creating many ExchangeCode entities in bulk.
type ExchangeCodeCreateBulk struct {
	config
	err      error
	builders []*ExchangeCodeCreate
	conflict []sql.ConflictOption
}

// Save creates the ExchangeCode entities in the database.
func (_c *ExchangeCodeCreateBulk) Save(ctx context.Context) ([]*ExchangeCode, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ExchangeCode, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ExchangeCodeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ExchangeCodeCreateBulk) SaveX(ctx context.Context) []*ExchangeCode {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ExchangeCodeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ExchangeCodeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ExchangeCode.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ExchangeCodeUpsert) {
//			SetCode(v+v).
//		}).
//		Exec(ctx)
func (_c *ExchangeCodeCreateBulk) OnConflict(opts ...sql.ConflictOption) *ExchangeCodeUpsertBulk {
	_c.conflict = opts
	return &ExchangeCodeUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ExchangeCode.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ExchangeCodeCreateBulk) OnConflictColumns(columns ...string) *ExchangeCodeUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ExchangeCodeUpsertBulk{
		create: _c,
	}
}

// ExchangeCodeUpsertBulk is the builder for "upsert"-ing
// a bulk of ExchangeCode nodes.
type ExchangeCodeUpsertBulk struct {
	create *ExchangeCodeCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ExchangeCode.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(exchangecode.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ExchangeCodeUpsertBulk) UpdateNewValues() *ExchangeCodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(exchangecode.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ExchangeCode.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ExchangeCodeUpsertBulk) Ignore() *ExchangeCodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ExchangeCodeUpsertBulk) DoNothing() *ExchangeCodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ExchangeCodeCreateBulk.OnConflict
// documentation for more info.
func (u *ExchangeCodeUpsertBulk) Update(set func(*ExchangeCodeUpsert)) *ExchangeCodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ExchangeCodeUpsert{UpdateSet: update})
	}))
	return u
}

// SetCode sets the "code" field.
func (u *ExchangeCodeUpsertBulk) SetCode(v string) *ExchangeCodeUpsertBulk {
	return u.Update(func(s *ExchangeCodeUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *ExchangeCodeUpsertBulk) UpdateCode() *ExchangeCodeUpsertBulk {
	return u.Update(func(s *ExchangeCodeUpsert) {
		s.UpdateCode()
	})
}

// SetCredits sets the "credits" field.
func (u *ExchangeCodeUpsertBulk) SetCredits(v int64) *ExchangeCodeUpsertBulk {
	return u.Update(func(s *ExchangeCodeUpsert) {
		s.SetCredits(v)
	})
}

// AddCredits adds v to the "credits" field.
func (u *ExchangeCodeUpsertBulk) AddCredits(v int64) *ExchangeCodeUpsertBulk {
	return u.Update(func(s *ExchangeCodeUpsert) {
		s.AddCredits(v)
	})
}

// UpdateCredits sets the "credits" field to the value that was provided on create.
func (u *ExchangeCodeUpsertBulk) UpdateCredits() *ExchangeCodeUpsertBulk {
	return u.Update(func(s *ExchangeCodeUpsert) {
		s.UpdateCredits()
	})
}

// SetMaxUses sets the "max_uses" field.
func (u *ExchangeCodeUpsertBulk) SetMaxUses(v int) *ExchangeCodeUpsertBulk {
	return u.Update(func(s *ExchangeCodeUpsert) {
		s.SetMaxUses(v)
	})
}

// AddMaxUses adds v to the "max_uses" field.
func (u *ExchangeCodeUpsertBulk) AddMaxUses(v int) *ExchangeCodeUpsertBulk {
	return u.Update(func(s *ExchangeCodeUpsert) {
		s.AddMaxUses(v)
	})
}

// UpdateMaxUses sets the "max_uses" field to the value that was provided on create.
func (u *ExchangeCodeUpsertBulk) UpdateMaxUses() *ExchangeCodeUpsertBulk {
	return u.Update(func(s *ExchangeCodeUpsert) {
		s.UpdateMaxUses()
	})
}

// SetUsedCount sets the "used_count" field.
func (u *ExchangeCodeUpsertBulk) SetUsedCount(v int) *ExchangeCodeUpsertBulk {
	return u.Update(func(s *ExchangeCodeUpsert) {
		s.SetUsedCount(v)
	})
}

// AddUsedCount adds v to the "used_count" field.
func (u *ExchangeCodeUpsertBulk) AddUsedCount(v int) *ExchangeCodeUpsertBulk {
	return u.Update(func(s *ExchangeCodeUpsert) {
		s.AddUsedCount(v)
	})
}

// UpdateUsedCount sets the "used_count" field to the value that was provided on create.
func (u *ExchangeCodeUpsertBulk) UpdateUsedCount() *ExchangeCodeUpsertBulk {
	return u.Update(func(s *ExchangeCodeUpsert) {
		s.UpdateUsedCount()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *ExchangeCodeUpsertBulk) SetExpiresAt(v time.Time) *ExchangeCodeUpsertBulk {
	return u.Update(func(s *ExchangeCodeUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *ExchangeCodeUpsertBulk) UpdateExpiresAt() *ExchangeCodeUpsertBulk {
	return u.Update(func(s *ExchangeCodeUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *ExchangeCodeUpsertBulk) ClearExpiresAt() *ExchangeCodeUpsertBulk {
	return u.Update(func(s *ExchangeCodeUpsert) {
		s.ClearExpiresAt()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *ExchangeCodeUpsertBulk) SetCreatedBy(v uuid.UUID) *ExchangeCodeUpsertBulk {
	return u.Update(func(s *ExchangeCodeUpsert) {
		s.SetCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *ExchangeCodeUpsertBulk) UpdateCreatedBy() *ExchangeCodeUpsertBulk {
	return u.Update(func(s *ExchangeCodeUpsert) {
		s.UpdateCreatedBy()
	})
}

// SetIsActive sets the "is_active" field.
func (u *ExchangeCodeUpsertBulk) SetIsActive(v bool) *ExchangeCodeUpsertBulk {
	return u.Update(func(s *ExchangeCodeUpsert) {
		s.SetIsActive(v)
	})
}

// UpdateIsActive sets the "is_active" field to the value that was provided on create.
func (u *ExchangeCodeUpsertBulk) UpdateIsActive() *ExchangeCodeUpsertBulk {
	return u.Update(func(s *ExchangeCodeUpsert) {
		s.UpdateIsActive()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *ExchangeCodeUpsertBulk) SetCreatedAt(v time.Time) *ExchangeCodeUpsertBulk {
	return u.Update(func(s *ExchangeCodeUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *ExchangeCodeUpsertBulk) UpdateCreatedAt() *ExchangeCodeUpsertBulk {
	return u.Update(func(s *ExchangeCodeUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ExchangeCodeUpsertBulk) SetUpdatedAt(v time.Time) *ExchangeCodeUpsertBulk {
	return u.Update(func(s *ExchangeCodeUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ExchangeCodeUpsertBulk) UpdateUpdatedAt() *ExchangeCodeUpsertBulk {
	return u.Update(func(s *ExchangeCodeUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ExchangeCodeUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("db: OnConflict was set for builder %d. Set it on the ExchangeCodeCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("db: missing options for ExchangeCodeCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ExchangeCodeUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
