// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/nidao003/mclaw/backend/db/expert"
)

// ExpertCreate is the builder for creating a Expert entity.
type ExpertCreate struct {
	config
	mutation *ExpertMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *ExpertCreate) SetDeletedAt(v time.Time) *ExpertCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *ExpertCreate) SetNillableDeletedAt(v *time.Time) *ExpertCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetSlug sets the "slug" field.
func (_c *ExpertCreate) SetSlug(v string) *ExpertCreate {
	_c.mutation.SetSlug(v)
	return _c
}

// SetName sets the "name" field.
func (_c *ExpertCreate) SetName(v string) *ExpertCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetSubtitle sets the "subtitle" field.
func (_c *ExpertCreate) SetSubtitle(v string) *ExpertCreate {
	_c.mutation.SetSubtitle(v)
	return _c
}

// SetNillableSubtitle sets the "subtitle" field if the given value is not nil.
func (_c *ExpertCreate) SetNillableSubtitle(v *string) *ExpertCreate {
	if v != nil {
		_c.SetSubtitle(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *ExpertCreate) SetDescription(v string) *ExpertCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *ExpertCreate) SetNillableDescription(v *string) *ExpertCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetIcon sets the "icon" field.
func (_c *ExpertCreate) SetIcon(v string) *ExpertCreate {
	_c.mutation.SetIcon(v)
	return _c
}

// SetNillableIcon sets the "icon" field if the given value is not nil.
func (_c *ExpertCreate) SetNillableIcon(v *string) *ExpertCreate {
	if v != nil {
		_c.SetIcon(*v)
	}
	return _c
}

// SetScenarios sets the "scenarios" field.
func (_c *ExpertCreate) SetScenarios(v []string) *ExpertCreate {
	_c.mutation.SetScenarios(v)
	return _c
}

// SetRelatedSkills sets the "related_skills" field.
func (_c *ExpertCreate) SetRelatedSkills(v []string) *ExpertCreate {
	_c.mutation.SetRelatedSkills(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *ExpertCreate) SetStatus(v string) *ExpertCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ExpertCreate) SetNillableStatus(v *string) *ExpertCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *ExpertCreate) SetSortOrder(v int) *ExpertCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *ExpertCreate) SetNillableSortOrder(v *int) *ExpertCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ExpertCreate) SetCreatedAt(v time.Time) *ExpertCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ExpertCreate) SetNillableCreatedAt(v *time.Time) *ExpertCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ExpertCreate) SetUpdatedAt(v time.Time) *ExpertCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ExpertCreate) SetNillableUpdatedAt(v *time.Time) *ExpertCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ExpertCreate) SetID(v uuid.UUID) *ExpertCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the ExpertMutation object of the builder.
func (_c *ExpertCreate) Mutation() *ExpertMutation {
	return _c.mutation
}

// Save creates the Expert in the database.
func (_c *ExpertCreate) Save(ctx context.Context) (*Expert, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ExpertCreate) SaveX(ctx context.Context) *Expert {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ExpertCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ExpertCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ExpertCreate) defaults() error {
	if _, ok := _c.mutation.Subtitle(); !ok {
		v := expert.DefaultSubtitle
		_c.mutation.SetSubtitle(v)
	}
	if _, ok := _c.mutation.Icon(); !ok {
		v := expert.DefaultIcon
		_c.mutation.SetIcon(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := expert.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := expert.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if expert.DefaultCreatedAt == nil {
			return fmt.Errorf("db: uninitialized expert.DefaultCreatedAt (forgotten import db/runtime?)")
		}
		v := expert.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if expert.DefaultUpdatedAt == nil {
			return fmt.Errorf("db: uninitialized expert.DefaultUpdatedAt (forgotten import db/runtime?)")
		}
		v := expert.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *ExpertCreate) check() error {
	if _, ok := _c.mutation.Slug(); !ok {
		return &ValidationError{Name: "slug", err: errors.New(`db: missing required field "Expert.slug"`)}
	}
	if v, ok := _c.mutation.Slug(); ok {
		if err := expert.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`db: validator failed for field "Expert.slug": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`db: missing required field "Expert.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := expert.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`db: validator failed for field "Expert.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Subtitle(); !ok {
		return &ValidationError{Name: "subtitle", err: errors.New(`db: missing required field "Expert.subtitle"`)}
	}
	if _, ok := _c.mutation.Icon(); !ok {
		return &ValidationError{Name: "icon", err: errors.New(`db: missing required field "Expert.icon"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`db: missing required field "Expert.status"`)}
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`db: missing required field "Expert.sort_order"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`db: missing required field "Expert.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`db: missing required field "Expert.updated_at"`)}
	}
	return nil
}

func (_c *ExpertCreate) sqlSave(ctx context.Context) (*Expert, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ExpertCreate) createSpec() (*Expert, *sqlgraph.CreateSpec) {
	var (
		_node = &Expert{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(expert.Table, sqlgraph.NewFieldSpec(expert.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(expert.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = value
	}
	if value, ok := _c.mutation.Slug(); ok {
		_spec.SetField(expert.FieldSlug, field.TypeString, value)
		_node.Slug = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(expert.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Subtitle(); ok {
		_spec.SetField(expert.FieldSubtitle, field.TypeString, value)
		_node.Subtitle = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(expert.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Icon(); ok {
		_spec.SetField(expert.FieldIcon, field.TypeString, value)
		_node.Icon = value
	}
	if value, ok := _c.mutation.Scenarios(); ok {
		_spec.SetField(expert.FieldScenarios, field.TypeJSON, value)
		_node.Scenarios = value
	}
	if value, ok := _c.mutation.RelatedSkills(); ok {
		_spec.SetField(expert.FieldRelatedSkills, field.TypeJSON, value)
		_node.RelatedSkills = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(expert.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(expert.FieldSortOrder, field.TypeInt, value)
		_node.SortOrder = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(expert.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(expert.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Expert.Create().
//		SetDeletedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ExpertUpsert) {
//			SetDeletedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ExpertCreate) OnConflict(opts ...sql.ConflictOption) *ExpertUpsertOne {
	_c.conflict = opts
	return &ExpertUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Expert.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ExpertCreate) OnConflictColumns(columns ...string) *ExpertUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ExpertUpsertOne{
		create: _c,
	}
}

type (
	// ExpertUpsertOne is the builder for "upsert"-ing
	//  one Expert node.
	ExpertUpsertOne struct {
		create *ExpertCreate
	}

	// ExpertUpsert is the "OnConflict" setter.
	ExpertUpsert struct {
		*sql.UpdateSet
	}
)

// SetDeletedAt sets the "deleted_at" field.
func (u *ExpertUpsert) SetDeletedAt(v time.Time) *ExpertUpsert {
	u.Set(expert.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ExpertUpsert) UpdateDeletedAt() *ExpertUpsert {
	u.SetExcluded(expert.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *ExpertUpsert) ClearDeletedAt() *ExpertUpsert {
	u.SetNull(expert.FieldDeletedAt)
	return u
}

// SetSlug sets the "slug" field.
func (u *ExpertUpsert) SetSlug(v string) *ExpertUpsert {
	u.Set(expert.FieldSlug, v)
	return u
}

// UpdateSlug sets the "slug" field to the value that was provided on create.
func (u *ExpertUpsert) UpdateSlug() *ExpertUpsert {
	u.SetExcluded(expert.FieldSlug)
	return u
}

// SetName sets the "name" field.
func (u *ExpertUpsert) SetName(v string) *ExpertUpsert {
	u.Set(expert.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ExpertUpsert) UpdateName() *ExpertUpsert {
	u.SetExcluded(expert.FieldName)
	return u
}

// SetSubtitle sets the "subtitle" field.
func (u *ExpertUpsert) SetSubtitle(v string) *ExpertUpsert {
	u.Set(expert.FieldSubtitle, v)
	return u
}

// UpdateSubtitle sets the "subtitle" field to the value that was provided on create.
func (u *ExpertUpsert) UpdateSubtitle() *ExpertUpsert {
	u.SetExcluded(expert.FieldSubtitle)
	return u
}

// SetDescription sets the "description" field.
func (u *ExpertUpsert) SetDescription(v string) *ExpertUpsert {
	u.Set(expert.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *ExpertUpsert) UpdateDescription() *ExpertUpsert {
	u.SetExcluded(expert.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *ExpertUpsert) ClearDescription() *ExpertUpsert {
	u.SetNull(expert.FieldDescription)
	return u
}

// SetIcon sets the "icon" field.
func (u *ExpertUpsert) SetIcon(v string) *ExpertUpsert {
	u.Set(expert.FieldIcon, v)
	return u
}

// UpdateIcon sets the "icon" field to the value that was provided on create.
func (u *ExpertUpsert) UpdateIcon() *ExpertUpsert {
	u.SetExcluded(expert.FieldIcon)
	return u
}

// SetScenarios sets the "scenarios" field.
func (u *ExpertUpsert) SetScenarios(v []string) *ExpertUpsert {
	u.Set(expert.FieldScenarios, v)
	return u
}

// UpdateScenarios sets the "scenarios" field to the value that was provided on create.
func (u *ExpertUpsert) UpdateScenarios() *ExpertUpsert {
	u.SetExcluded(expert.FieldScenarios)
	return u
}

// ClearScenarios clears the value of the "scenarios" field.
func (u *ExpertUpsert) ClearScenarios() *ExpertUpsert {
	u.SetNull(expert.FieldScenarios)
	return u
}

// SetRelatedSkills sets the "related_skills" field.
func (u *ExpertUpsert) SetRelatedSkills(v []string) *ExpertUpsert {
	u.Set(expert.FieldRelatedSkills, v)
	return u
}

// UpdateRelatedSkills sets the "related_skills" field to the value that was provided on create.
func (u *ExpertUpsert) UpdateRelatedSkills() *ExpertUpsert {
	u.SetExcluded(expert.FieldRelatedSkills)
	return u
}

// ClearRelatedSkills clears the value of the "related_skills" field.
func (u *ExpertUpsert) ClearRelatedSkills() *ExpertUpsert {
	u.SetNull(expert.FieldRelatedSkills)
	return u
}

// SetStatus sets the "status" field.
func (u *ExpertUpsert) SetStatus(v string) *ExpertUpsert {
	u.Set(expert.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ExpertUpsert) UpdateStatus() *ExpertUpsert {
	u.SetExcluded(expert.FieldStatus)
	return u
}

// SetSortOrder sets the "sort_order" field.
func (u *ExpertUpsert) SetSortOrder(v int) *ExpertUpsert {
	u.Set(expert.FieldSortOrder, v)
	return u
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *ExpertUpsert) UpdateSortOrder() *ExpertUpsert {
	u.SetExcluded(expert.FieldSortOrder)
	return u
}

// AddSortOrder adds v to the "sort_order" field.
func (u *ExpertUpsert) AddSortOrder(v int) *ExpertUpsert {
	u.Add(expert.FieldSortOrder, v)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *ExpertUpsert) SetCreatedAt(v time.Time) *ExpertUpsert {
	u.Set(expert.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *ExpertUpsert) UpdateCreatedAt() *ExpertUpsert {
	u.SetExcluded(expert.FieldCreatedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ExpertUpsert) SetUpdatedAt(v time.Time) *ExpertUpsert {
	u.Set(expert.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ExpertUpsert) UpdateUpdatedAt() *ExpertUpsert {
	u.SetExcluded(expert.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Expert.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(expert.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ExpertUpsertOne) UpdateNewValues() *ExpertUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(expert.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Expert.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ExpertUpsertOne) Ignore() *ExpertUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ExpertUpsertOne) DoNothing() *ExpertUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ExpertCreate.OnConflict
// documentation for more info.
func (u *ExpertUpsertOne) Update(set func(*ExpertUpsert)) *ExpertUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ExpertUpsert{UpdateSet: update})
	}))
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ExpertUpsertOne) SetDeletedAt(v time.Time) *ExpertUpsertOne {
	return u.Update(func(s *ExpertUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ExpertUpsertOne) UpdateDeletedAt() *ExpertUpsertOne {
	return u.Update(func(s *ExpertUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *ExpertUpsertOne) ClearDeletedAt() *ExpertUpsertOne {
	return u.Update(func(s *ExpertUpsert) {
		s.ClearDeletedAt()
	})
}

// SetSlug sets the "slug" field.
func (u *ExpertUpsertOne) SetSlug(v string) *ExpertUpsertOne {
	return u.Update(func(s *ExpertUpsert) {
		s.SetSlug(v)
	})
}

// UpdateSlug sets the "slug" field to the value that was provided on create.
func (u *ExpertUpsertOne) UpdateSlug() *ExpertUpsertOne {
	return u.Update(func(s *ExpertUpsert) {
		s.UpdateSlug()
	})
}

// SetName sets the "name" field.
func (u *ExpertUpsertOne) SetName(v string) *ExpertUpsertOne {
	return u.Update(func(s *ExpertUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ExpertUpsertOne) UpdateName() *ExpertUpsertOne {
	return u.Update(func(s *ExpertUpsert) {
		s.UpdateName()
	})
}

// SetSubtitle sets the "subtitle" field.
func (u *ExpertUpsertOne) SetSubtitle(v string) *ExpertUpsertOne {
	return u.Update(func(s *ExpertUpsert) {
		s.SetSubtitle(v)
	})
}

// UpdateSubtitle sets the "subtitle" field to the value that was provided on create.
func (u *ExpertUpsertOne) UpdateSubtitle() *ExpertUpsertOne {
	return u.Update(func(s *ExpertUpsert) {
		s.UpdateSubtitle()
	})
}

// SetDescription sets the "description" field.
func (u *ExpertUpsertOne) SetDescription(v string) *ExpertUpsertOne {
	return u.Update(func(s *ExpertUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *ExpertUpsertOne) UpdateDescription() *ExpertUpsertOne {
	return u.Update(func(s *ExpertUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *ExpertUpsertOne) ClearDescription() *ExpertUpsertOne {
	return u.Update(func(s *ExpertUpsert) {
		s.ClearDescription()
	})
}

// SetIcon sets the "icon" field.
func (u *ExpertUpsertOne) SetIcon(v string) *ExpertUpsertOne {
	return u.Update(func(s *ExpertUpsert) {
		s.SetIcon(v)
	})
}

// UpdateIcon sets the "icon" field to the value that was provided on create.
func (u *ExpertUpsertOne) UpdateIcon() *ExpertUpsertOne {
	return u.Update(func(s *ExpertUpsert) {
		s.UpdateIcon()
	})
}

// SetScenarios sets the "scenarios" field.
func (u *ExpertUpsertOne) SetScenarios(v []string) *ExpertUpsertOne {
	return u.Update(func(s *ExpertUpsert) {
		s.SetScenarios(v)
	})
}

// UpdateScenarios sets the "scenarios" field to the value that was provided on create.
func (u *ExpertUpsertOne) UpdateScenarios() *ExpertUpsertOne {
	return u.Update(func(s *ExpertUpsert) {
		s.UpdateScenarios()
	})
}

// ClearScenarios clears the value of the "scenarios" field.
func (u *ExpertUpsertOne) ClearScenarios() *ExpertUpsertOne {
	return u.Update(func(s *ExpertUpsert) {
		s.ClearScenarios()
	})
}

// SetRelatedSkills sets the "related_skills" field.
func (u *ExpertUpsertOne) SetRelatedSkills(v []string) *ExpertUpsertOne {
	return u.Update(func(s *ExpertUpsert) {
		s.SetRelatedSkills(v)
	})
}

// UpdateRelatedSkills sets the "related_skills" field to the value that was provided on create.
func (u *ExpertUpsertOne) UpdateRelatedSkills() *ExpertUpsertOne {
	return u.Update(func(s *ExpertUpsert) {
		s.UpdateRelatedSkills()
	})
}

// ClearRelatedSkills clears the value of the "related_skills" field.
func (u *ExpertUpsertOne) ClearRelatedSkills() *ExpertUpsertOne {
	return u.Update(func(s *ExpertUpsert) {
		s.ClearRelatedSkills()
	})
}

// SetStatus sets the "status" field.
func (u *ExpertUpsertOne) SetStatus(v string) *ExpertUpsertOne {
	return u.Update(func(s *ExpertUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ExpertUpsertOne) UpdateStatus() *ExpertUpsertOne {
	return u.Update(func(s *ExpertUpsert) {
		s.UpdateStatus()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *ExpertUpsertOne) SetSortOrder(v int) *ExpertUpsertOne {
	return u.Update(func(s *ExpertUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *ExpertUpsertOne) AddSortOrder(v int) *ExpertUpsertOne {
	return u.Update(func(s *ExpertUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *ExpertUpsertOne) UpdateSortOrder() *ExpertUpsertOne {
	return u.Update(func(s *ExpertUpsert) {
		s.UpdateSortOrder()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *ExpertUpsertOne) SetCreatedAt(v time.Time) *ExpertUpsertOne {
	return u.Update(func(s *ExpertUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *ExpertUpsertOne) UpdateCreatedAt() *ExpertUpsertOne {
	return u.Update(func(s *ExpertUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ExpertUpsertOne) SetUpdatedAt(v time.Time) *ExpertUpsertOne {
	return u.Update(func(s *ExpertUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ExpertUpsertOne) UpdateUpdatedAt() *ExpertUpsertOne {
	return u.Update(func(s *ExpertUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ExpertUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("db: missing options for ExpertCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ExpertUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ExpertUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("db: ExpertUpsertOne.ID is not supported by MySQL driver. Use ExpertUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ExpertUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ExpertCreateBulk is the builder for creating many Expert entities in bulk.
type ExpertCreateBulk struct {
	config
	err      error
	builders []*ExpertCreate
	conflict []sql.ConflictOption
}

// Save creates the Expert entities in the database.
func (_c *ExpertCreateBulk) Save(ctx context.Context) ([]*Expert, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Expert, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ExpertMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ExpertCreateBulk) SaveX(ctx context.Context) []*Expert {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ExpertCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ExpertCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Expert.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ExpertUpsert) {
//			SetDeletedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ExpertCreateBulk) OnConflict(opts ...sql.ConflictOption) *ExpertUpsertBulk {
	_c.conflict = opts
	return &ExpertUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Expert.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ExpertCreateBulk) OnConflictColumns(columns ...string) *ExpertUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ExpertUpsertBulk{
		create: _c,
	}
}

// ExpertUpsertBulk is the builder for "upsert"-ing
// a bulk of Expert nodes.
type ExpertUpsertBulk struct {
	create *ExpertCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Expert.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(expert.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ExpertUpsertBulk) UpdateNewValues() *ExpertUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(expert.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Expert.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ExpertUpsertBulk) Ignore() *ExpertUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ExpertUpsertBulk) DoNothing() *ExpertUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ExpertCreateBulk.OnConflict
// documentation for more info.
func (u *ExpertUpsertBulk) Update(set func(*ExpertUpsert)) *ExpertUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ExpertUpsert{UpdateSet: update})
	}))
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ExpertUpsertBulk) SetDeletedAt(v time.Time) *ExpertUpsertBulk {
	return u.Update(func(s *ExpertUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ExpertUpsertBulk) UpdateDeletedAt() *ExpertUpsertBulk {
	return u.Update(func(s *ExpertUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *ExpertUpsertBulk) ClearDeletedAt() *ExpertUpsertBulk {
	return u.Update(func(s *ExpertUpsert) {
		s.ClearDeletedAt()
	})
}

// SetSlug sets the "slug" field.
func (u *ExpertUpsertBulk) SetSlug(v string) *ExpertUpsertBulk {
	return u.Update(func(s *ExpertUpsert) {
		s.SetSlug(v)
	})
}

// UpdateSlug sets the "slug" field to the value that was provided on create.
func (u *ExpertUpsertBulk) UpdateSlug() *ExpertUpsertBulk {
	return u.Update(func(s *ExpertUpsert) {
		s.UpdateSlug()
	})
}

// SetName sets the "name" field.
func (u *ExpertUpsertBulk) SetName(v string) *ExpertUpsertBulk {
	return u.Update(func(s *ExpertUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ExpertUpsertBulk) UpdateName() *ExpertUpsertBulk {
	return u.Update(func(s *ExpertUpsert) {
		s.UpdateName()
	})
}

// SetSubtitle sets the "subtitle" field.
func (u *ExpertUpsertBulk) SetSubtitle(v string) *ExpertUpsertBulk {
	return u.Update(func(s *ExpertUpsert) {
		s.SetSubtitle(v)
	})
}

// UpdateSubtitle sets the "subtitle" field to the value that was provided on create.
func (u *ExpertUpsertBulk) UpdateSubtitle() *ExpertUpsertBulk {
	return u.Update(func(s *ExpertUpsert) {
		s.UpdateSubtitle()
	})
}

// SetDescription sets the "description" field.
func (u *ExpertUpsertBulk) SetDescription(v string) *ExpertUpsertBulk {
	return u.Update(func(s *ExpertUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *ExpertUpsertBulk) UpdateDescription() *ExpertUpsertBulk {
	return u.Update(func(s *ExpertUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *ExpertUpsertBulk) ClearDescription() *ExpertUpsertBulk {
	return u.Update(func(s *ExpertUpsert) {
		s.ClearDescription()
	})
}

// SetIcon sets the "icon" field.
func (u *ExpertUpsertBulk) SetIcon(v string) *ExpertUpsertBulk {
	return u.Update(func(s *ExpertUpsert) {
		s.SetIcon(v)
	})
}

// UpdateIcon sets the "icon" field to the value that was provided on create.
func (u *ExpertUpsertBulk) UpdateIcon() *ExpertUpsertBulk {
	return u.Update(func(s *ExpertUpsert) {
		s.UpdateIcon()
	})
}

// SetScenarios sets the "scenarios" field.
func (u *ExpertUpsertBulk) SetScenarios(v []string) *ExpertUpsertBulk {
	return u.Update(func(s *ExpertUpsert) {
		s.SetScenarios(v)
	})
}

// UpdateScenarios sets the "scenarios" field to the value that was provided on create.
func (u *ExpertUpsertBulk) UpdateScenarios() *ExpertUpsertBulk {
	return u.Update(func(s *ExpertUpsert) {
		s.UpdateScenarios()
	})
}

// ClearScenarios clears the value of the "scenarios" field.
func (u *ExpertUpsertBulk) ClearScenarios() *ExpertUpsertBulk {
	return u.Update(func(s *ExpertUpsert) {
		s.ClearScenarios()
	})
}

// SetRelatedSkills sets the "related_skills" field.
func (u *ExpertUpsertBulk) SetRelatedSkills(v []string) *ExpertUpsertBulk {
	return u.Update(func(s *ExpertUpsert) {
		s.SetRelatedSkills(v)
	})
}

// UpdateRelatedSkills sets the "related_skills" field to the value that was provided on create.
func (u *ExpertUpsertBulk) UpdateRelatedSkills() *ExpertUpsertBulk {
	return u.Update(func(s *ExpertUpsert) {
		s.UpdateRelatedSkills()
	})
}

// ClearRelatedSkills clears the value of the "related_skills" field.
func (u *ExpertUpsertBulk) ClearRelatedSkills() *ExpertUpsertBulk {
	return u.Update(func(s *ExpertUpsert) {
		s.ClearRelatedSkills()
	})
}

// SetStatus sets the "status" field.
func (u *ExpertUpsertBulk) SetStatus(v string) *ExpertUpsertBulk {
	return u.Update(func(s *ExpertUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ExpertUpsertBulk) UpdateStatus() *ExpertUpsertBulk {
	return u.Update(func(s *ExpertUpsert) {
		s.UpdateStatus()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *ExpertUpsertBulk) SetSortOrder(v int) *ExpertUpsertBulk {
	return u.Update(func(s *ExpertUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *ExpertUpsertBulk) AddSortOrder(v int) *ExpertUpsertBulk {
	return u.Update(func(s *ExpertUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *ExpertUpsertBulk) UpdateSortOrder() *ExpertUpsertBulk {
	return u.Update(func(s *ExpertUpsert) {
		s.UpdateSortOrder()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *ExpertUpsertBulk) SetCreatedAt(v time.Time) *ExpertUpsertBulk {
	return u.Update(func(s *ExpertUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *ExpertUpsertBulk) UpdateCreatedAt() *ExpertUpsertBulk {
	return u.Update(func(s *ExpertUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ExpertUpsertBulk) SetUpdatedAt(v time.Time) *ExpertUpsertBulk {
	return u.Update(func(s *ExpertUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ExpertUpsertBulk) UpdateUpdatedAt() *ExpertUpsertBulk {
	return u.Update(func(s *ExpertUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ExpertUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("db: OnConflict was set for builder %d. Set it on the ExpertCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("db: missing options for ExpertCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ExpertUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
