// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/nidao003/mclaw/backend/db/invitation"
)

// InvitationCreate is the builder for creating a Invitation entity.
type InvitationCreate struct {
	config
	mutation *InvitationMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetInviterID sets the "inviter_id" field.
func (_c *InvitationCreate) SetInviterID(v uuid.UUID) *InvitationCreate {
	_c.mutation.SetInviterID(v)
	return _c
}

// SetInviteeID sets the "invitee_id" field.
func (_c *InvitationCreate) SetInviteeID(v uuid.UUID) *InvitationCreate {
	_c.mutation.SetInviteeID(v)
	return _c
}

// SetReward sets the "reward" field.
func (_c *InvitationCreate) SetReward(v int64) *InvitationCreate {
	_c.mutation.SetReward(v)
	return _c
}

// SetNillableReward sets the "reward" field if the given value is not nil.
func (_c *InvitationCreate) SetNillableReward(v *int64) *InvitationCreate {
	if v != nil {
		_c.SetReward(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *InvitationCreate) SetCreatedAt(v time.Time) *InvitationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *InvitationCreate) SetNillableCreatedAt(v *time.Time) *InvitationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *InvitationCreate) SetID(v uuid.UUID) *InvitationCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the InvitationMutation object of the builder.
func (_c *InvitationCreate) Mutation() *InvitationMutation {
	return _c.mutation
}

// Save creates the Invitation in the database.
func (_c *InvitationCreate) Save(ctx context.Context) (*Invitation, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *InvitationCreate) SaveX(ctx context.Context) *Invitation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InvitationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InvitationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *InvitationCreate) defaults() {
	if _, ok := _c.mutation.Reward(); !ok {
		v := invitation.DefaultReward
		_c.mutation.SetReward(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := invitation.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *InvitationCreate) check() error {
	if _, ok := _c.mutation.InviterID(); !ok {
		return &ValidationError{Name: "inviter_id", err: errors.New(`db: missing required field "Invitation.inviter_id"`)}
	}
	if _, ok := _c.mutation.InviteeID(); !ok {
		return &ValidationError{Name: "invitee_id", err: errors.New(`db: missing required field "Invitation.invitee_id"`)}
	}
	if _, ok := _c.mutation.Reward(); !ok {
		return &ValidationError{Name: "reward", err: errors.New(`db: missing required field "Invitation.reward"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`db: missing required field "Invitation.created_at"`)}
	}
	return nil
}

func (_c *InvitationCreate) sqlSave(ctx context.Context) (*Invitation, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *InvitationCreate) createSpec() (*Invitation, *sqlgraph.CreateSpec) {
	var (
		_node = &Invitation{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(invitation.Table, sqlgraph.NewFieldSpec(invitation.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.InviterID(); ok {
		_spec.SetField(invitation.FieldInviterID, field.TypeUUID, value)
		_node.InviterID = value
	}
	if value, ok := _c.mutation.InviteeID(); ok {
		_spec.SetField(invitation.FieldInviteeID, field.TypeUUID, value)
		_node.InviteeID = value
	}
	if value, ok := _c.mutation.Reward(); ok {
		_spec.SetField(invitation.FieldReward, field.TypeInt64, value)
		_node.Reward = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(invitation.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Invitation.Create().
//		SetInviterID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InvitationUpsert) {
//			SetInviterID(v+v).
//		}).
//		Exec(ctx)
func (_c *InvitationCreate) OnConflict(opts ...sql.ConflictOption) *InvitationUpsertOne {
	_c.conflict = opts
	return &InvitationUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Invitation.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InvitationCreate) OnConflictColumns(columns ...string) *InvitationUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InvitationUpsertOne{
		create: _c,
	}
}

type (
	// InvitationUpsertOne is the builder for "upsert"-ing
	//  one Invitation node.
	InvitationUpsertOne struct {
		create *InvitationCreate
	}

	// InvitationUpsert is the "OnConflict" setter.
	InvitationUpsert struct {
		*sql.UpdateSet
	}
)

// SetInviterID sets the "inviter_id" field.
func (u *InvitationUpsert) SetInviterID(v uuid.UUID) *InvitationUpsert {
	u.Set(invitation.FieldInviterID, v)
	return u
}

// UpdateInviterID sets the "inviter_id" field to the value that was provided on create.
func (u *InvitationUpsert) UpdateInviterID() *InvitationUpsert {
	u.SetExcluded(invitation.FieldInviterID)
	return u
}

// SetInviteeID sets the "invitee_id" field.
func (u *InvitationUpsert) SetInviteeID(v uuid.UUID) *InvitationUpsert {
	u.Set(invitation.FieldInviteeID, v)
	return u
}

// UpdateInviteeID sets the "invitee_id" field to the value that was provided on create.
func (u *InvitationUpsert) UpdateInviteeID() *InvitationUpsert {
	u.SetExcluded(invitation.FieldInviteeID)
	return u
}

// SetReward sets the "reward" field.
func (u *InvitationUpsert) SetReward(v int64) *InvitationUpsert {
	u.Set(invitation.FieldReward, v)
	return u
}

// UpdateReward sets the "reward" field to the value that was provided on create.
func (u *InvitationUpsert) UpdateReward() *InvitationUpsert {
	u.SetExcluded(invitation.FieldReward)
	return u
}

// AddReward adds v to the "reward" field.
func (u *InvitationUpsert) AddReward(v int64) *InvitationUpsert {
	u.Add(invitation.FieldReward, v)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *InvitationUpsert) SetCreatedAt(v time.Time) *InvitationUpsert {
	u.Set(invitation.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *InvitationUpsert) UpdateCreatedAt() *InvitationUpsert {
	u.SetExcluded(invitation.FieldCreatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Invitation.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(invitation.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *InvitationUpsertOne) UpdateNewValues() *InvitationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(invitation.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Invitation.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *InvitationUpsertOne) Ignore() *InvitationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InvitationUpsertOne) DoNothing() *InvitationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InvitationCreate.OnConflict
// documentation for more info.
func (u *InvitationUpsertOne) Update(set func(*InvitationUpsert)) *InvitationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InvitationUpsert{UpdateSet: update})
	}))
	return u
}

// SetInviterID sets the "inviter_id" field.
func (u *InvitationUpsertOne) SetInviterID(v uuid.UUID) *InvitationUpsertOne {
	return u.Update(func(s *InvitationUpsert) {
		s.SetInviterID(v)
	})
}

// UpdateInviterID sets the "inviter_id" field to the value that was provided on create.
func (u *InvitationUpsertOne) UpdateInviterID() *InvitationUpsertOne {
	return u.Update(func(s *InvitationUpsert) {
		s.UpdateInviterID()
	})
}

// SetInviteeID sets the "invitee_id" field.
func (u *InvitationUpsertOne) SetInviteeID(v uuid.UUID) *InvitationUpsertOne {
	return u.Update(func(s *InvitationUpsert) {
		s.SetInviteeID(v)
	})
}

// UpdateInviteeID sets the "invitee_id" field to the value that was provided on create.
func (u *InvitationUpsertOne) UpdateInviteeID() *InvitationUpsertOne {
	return u.Update(func(s *InvitationUpsert) {
		s.UpdateInviteeID()
	})
}

// SetReward sets the "reward" field.
func (u *InvitationUpsertOne) SetReward(v int64) *InvitationUpsertOne {
	return u.Update(func(s *InvitationUpsert) {
		s.SetReward(v)
	})
}

// AddReward adds v to the "reward" field.
func (u *InvitationUpsertOne) AddReward(v int64) *InvitationUpsertOne {
	return u.Update(func(s *InvitationUpsert) {
		s.AddReward(v)
	})
}

// UpdateReward sets the "reward" field to the value that was provided on create.
func (u *InvitationUpsertOne) UpdateReward() *InvitationUpsertOne {
	return u.Update(func(s *InvitationUpsert) {
		s.UpdateReward()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *InvitationUpsertOne) SetCreatedAt(v time.Time) *InvitationUpsertOne {
	return u.Update(func(s *InvitationUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *InvitationUpsertOne) UpdateCreatedAt() *InvitationUpsertOne {
	return u.Update(func(s *InvitationUpsert) {
		s.UpdateCreatedAt()
	})
}

// Exec executes the query.
func (u *InvitationUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("db: missing options for InvitationCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InvitationUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *InvitationUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("db: InvitationUpsertOne.ID is not supported by MySQL driver. Use InvitationUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *InvitationUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// InvitationCreateBulk is the builder for creating many Invitation entities in bulk.
type InvitationCreateBulk struct {
	config
	err      error
	builders []*InvitationCreate
	conflict []sql.ConflictOption
}

// Save creates the Invitation entities in the database.
func (_c *InvitationCreateBulk) Save(ctx context.Context) ([]*Invitation, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Invitation, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InvitationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *InvitationCreateBulk) SaveX(ctx context.Context) []*Invitation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InvitationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InvitationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Invitation.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InvitationUpsert) {
//			SetInviterID(v+v).
//		}).
//		Exec(ctx)
func (_c *InvitationCreateBulk) OnConflict(opts ...sql.ConflictOption) *InvitationUpsertBulk {
	_c.conflict = opts
	return &InvitationUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Invitation.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InvitationCreateBulk) OnConflictColumns(columns ...string) *InvitationUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InvitationUpsertBulk{
		create: _c,
	}
}

// InvitationUpsertBulk is the builder for "upsert"-ing
// a bulk of Invitation nodes.
type InvitationUpsertBulk struct {
	create *InvitationCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Invitation.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(invitation.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *InvitationUpsertBulk) UpdateNewValues() *InvitationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(invitation.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Invitation.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *InvitationUpsertBulk) Ignore() *InvitationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InvitationUpsertBulk) DoNothing() *InvitationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InvitationCreateBulk.OnConflict
// documentation for more info.
func (u *InvitationUpsertBulk) Update(set func(*InvitationUpsert)) *InvitationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InvitationUpsert{UpdateSet: update})
	}))
	return u
}

// SetInviterID sets the "inviter_id" field.
func (u *InvitationUpsertBulk) SetInviterID(v uuid.UUID) *InvitationUpsertBulk {
	return u.Update(func(s *InvitationUpsert) {
		s.SetInviterID(v)
	})
}

// UpdateInviterID sets the "inviter_id" field to the value that was provided on create.
func (u *InvitationUpsertBulk) UpdateInviterID() *InvitationUpsertBulk {
	return u.Update(func(s *InvitationUpsert) {
		s.UpdateInviterID()
	})
}

// SetInviteeID sets the "invitee_id" field.
func (u *InvitationUpsertBulk) SetInviteeID(v uuid.UUID) *InvitationUpsertBulk {
	return u.Update(func(s *InvitationUpsert) {
		s.SetInviteeID(v)
	})
}

// UpdateInviteeID sets the "invitee_id" field to the value that was provided on create.
func (u *InvitationUpsertBulk) UpdateInviteeID() *InvitationUpsertBulk {
	return u.Update(func(s *InvitationUpsert) {
		s.UpdateInviteeID()
	})
}

// SetReward sets the "reward" field.
func (u *InvitationUpsertBulk) SetReward(v int64) *InvitationUpsertBulk {
	return u.Update(func(s *InvitationUpsert) {
		s.SetReward(v)
	})
}

// AddReward adds v to the "reward" field.
func (u *InvitationUpsertBulk) AddReward(v int64) *InvitationUpsertBulk {
	return u.Update(func(s *InvitationUpsert) {
		s.AddReward(v)
	})
}

// UpdateReward sets the "reward" field to the value that was provided on create.
func (u *InvitationUpsertBulk) UpdateReward() *InvitationUpsertBulk {
	return u.Update(func(s *InvitationUpsert) {
		s.UpdateReward()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *InvitationUpsertBulk) SetCreatedAt(v time.Time) *InvitationUpsertBulk {
	return u.Update(func(s *InvitationUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *InvitationUpsertBulk) UpdateCreatedAt() *InvitationUpsertBulk {
	return u.Update(func(s *InvitationUpsert) {
		s.UpdateCreatedAt()
	})
}

// Exec executes the query.
func (u *InvitationUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("db: OnConflict was set for builder %d. Set it on the InvitationCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("db: missing options for InvitationCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InvitationUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
