// Code generated by ent, DO NOT EDIT.

package db

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/nidao003/mclaw/backend/db/invitation"
)

// Invitation is the model entity for the Invitation schema.
type Invitation struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// InviterID holds the value of the "inviter_id" field.
	InviterID uuid.UUID `json:"inviter_id,omitempty"`
	// InviteeID holds the value of the "invitee_id" field.
	InviteeID uuid.UUID `json:"invitee_id,omitempty"`
	// Reward holds the value of the "reward" field.
	Reward int64 `json:"reward,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Invitation) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case invitation.FieldReward:
			values[i] = new(sql.NullInt64)
		case invitation.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case invitation.FieldID, invitation.FieldInviterID, invitation.FieldInviteeID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Invitation fields.
func (_m *Invitation) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case invitation.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case invitation.FieldInviterID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field inviter_id", values[i])
			} else if value != nil {
				_m.InviterID = *value
			}
		case invitation.FieldInviteeID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field invitee_id", values[i])
			} else if value != nil {
				_m.InviteeID = *value
			}
		case invitation.FieldReward:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field reward", values[i])
			} else if value.Valid {
				_m.Reward = value.Int64
			}
		case invitation.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Invitation.
// This includes values selected through modifiers, order, etc.
func (_m *Invitation) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Invitation.
// Note that you need to call Invitation.Unwrap() before calling this method if this Invitation
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Invitation) Update() *InvitationUpdateOne {
	return NewInvitationClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Invitation entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Invitation) Unwrap() *Invitation {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("db: Invitation is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Invitation) String() string {
	var builder strings.Builder
	builder.WriteString("Invitation(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("inviter_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.InviterID))
	builder.WriteString(", ")
	builder.WriteString("invitee_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.InviteeID))
	builder.WriteString(", ")
	builder.WriteString("reward=")
	builder.WriteString(fmt.Sprintf("%v", _m.Reward))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Invitations is a parsable slice of Invitation.
type Invitations []*Invitation
