// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/nidao003/mclaw/backend/db/plan"
	"github.com/nidao003/mclaw/backend/db/usersubscription"
)

// PlanCreate is the builder for creating a Plan entity.
type PlanCreate struct {
	config
	mutation *PlanMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "name" field.
func (_c *PlanCreate) SetName(v string) *PlanCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDisplayName sets the "display_name" field.
func (_c *PlanCreate) SetDisplayName(v string) *PlanCreate {
	_c.mutation.SetDisplayName(v)
	return _c
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_c *PlanCreate) SetNillableDisplayName(v *string) *PlanCreate {
	if v != nil {
		_c.SetDisplayName(*v)
	}
	return _c
}

// SetPriceMonth sets the "price_month" field.
func (_c *PlanCreate) SetPriceMonth(v int64) *PlanCreate {
	_c.mutation.SetPriceMonth(v)
	return _c
}

// SetNillablePriceMonth sets the "price_month" field if the given value is not nil.
func (_c *PlanCreate) SetNillablePriceMonth(v *int64) *PlanCreate {
	if v != nil {
		_c.SetPriceMonth(*v)
	}
	return _c
}

// SetPriceYear sets the "price_year" field.
func (_c *PlanCreate) SetPriceYear(v int64) *PlanCreate {
	_c.mutation.SetPriceYear(v)
	return _c
}

// SetNillablePriceYear sets the "price_year" field if the given value is not nil.
func (_c *PlanCreate) SetNillablePriceYear(v *int64) *PlanCreate {
	if v != nil {
		_c.SetPriceYear(*v)
	}
	return _c
}

// SetBasicTokenQuota sets the "basic_token_quota" field.
func (_c *PlanCreate) SetBasicTokenQuota(v int64) *PlanCreate {
	_c.mutation.SetBasicTokenQuota(v)
	return _c
}

// SetNillableBasicTokenQuota sets the "basic_token_quota" field if the given value is not nil.
func (_c *PlanCreate) SetNillableBasicTokenQuota(v *int64) *PlanCreate {
	if v != nil {
		_c.SetBasicTokenQuota(*v)
	}
	return _c
}

// SetProTokenQuota sets the "pro_token_quota" field.
func (_c *PlanCreate) SetProTokenQuota(v int64) *PlanCreate {
	_c.mutation.SetProTokenQuota(v)
	return _c
}

// SetNillableProTokenQuota sets the "pro_token_quota" field if the given value is not nil.
func (_c *PlanCreate) SetNillableProTokenQuota(v *int64) *PlanCreate {
	if v != nil {
		_c.SetProTokenQuota(*v)
	}
	return _c
}

// SetUltraTokenQuota sets the "ultra_token_quota" field.
func (_c *PlanCreate) SetUltraTokenQuota(v int64) *PlanCreate {
	_c.mutation.SetUltraTokenQuota(v)
	return _c
}

// SetNillableUltraTokenQuota sets the "ultra_token_quota" field if the given value is not nil.
func (_c *PlanCreate) SetNillableUltraTokenQuota(v *int64) *PlanCreate {
	if v != nil {
		_c.SetUltraTokenQuota(*v)
	}
	return _c
}

// SetMonthlyCredits sets the "monthly_credits" field.
func (_c *PlanCreate) SetMonthlyCredits(v int64) *PlanCreate {
	_c.mutation.SetMonthlyCredits(v)
	return _c
}

// SetNillableMonthlyCredits sets the "monthly_credits" field if the given value is not nil.
func (_c *PlanCreate) SetNillableMonthlyCredits(v *int64) *PlanCreate {
	if v != nil {
		_c.SetMonthlyCredits(*v)
	}
	return _c
}

// SetMaxConcurrency sets the "max_concurrency" field.
func (_c *PlanCreate) SetMaxConcurrency(v int) *PlanCreate {
	_c.mutation.SetMaxConcurrency(v)
	return _c
}

// SetNillableMaxConcurrency sets the "max_concurrency" field if the given value is not nil.
func (_c *PlanCreate) SetNillableMaxConcurrency(v *int) *PlanCreate {
	if v != nil {
		_c.SetMaxConcurrency(*v)
	}
	return _c
}

// SetFeatures sets the "features" field.
func (_c *PlanCreate) SetFeatures(v []string) *PlanCreate {
	_c.mutation.SetFeatures(v)
	return _c
}

// SetIsDefault sets the "is_default" field.
func (_c *PlanCreate) SetIsDefault(v bool) *PlanCreate {
	_c.mutation.SetIsDefault(v)
	return _c
}

// SetNillableIsDefault sets the "is_default" field if the given value is not nil.
func (_c *PlanCreate) SetNillableIsDefault(v *bool) *PlanCreate {
	if v != nil {
		_c.SetIsDefault(*v)
	}
	return _c
}

// SetIsActive sets the "is_active" field.
func (_c *PlanCreate) SetIsActive(v bool) *PlanCreate {
	_c.mutation.SetIsActive(v)
	return _c
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_c *PlanCreate) SetNillableIsActive(v *bool) *PlanCreate {
	if v != nil {
		_c.SetIsActive(*v)
	}
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *PlanCreate) SetSortOrder(v int) *PlanCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *PlanCreate) SetNillableSortOrder(v *int) *PlanCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PlanCreate) SetCreatedAt(v time.Time) *PlanCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PlanCreate) SetNillableCreatedAt(v *time.Time) *PlanCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PlanCreate) SetUpdatedAt(v time.Time) *PlanCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PlanCreate) SetNillableUpdatedAt(v *time.Time) *PlanCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *PlanCreate) SetID(v uuid.UUID) *PlanCreate {
	_c.mutation.SetID(v)
	return _c
}

// AddSubscriptionIDs adds the "subscriptions" edge to the UserSubscription entity by IDs.
func (_c *PlanCreate) AddSubscriptionIDs(ids ...uuid.UUID) *PlanCreate {
	_c.mutation.AddSubscriptionIDs(ids...)
	return _c
}

// AddSubscriptions adds the "subscriptions" edges to the UserSubscription entity.
func (_c *PlanCreate) AddSubscriptions(v ...*UserSubscription) *PlanCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddSubscriptionIDs(ids...)
}

// Mutation returns the PlanMutation object of the builder.
func (_c *PlanCreate) Mutation() *PlanMutation {
	return _c.mutation
}

// Save creates the Plan in the database.
func (_c *PlanCreate) Save(ctx context.Context) (*Plan, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PlanCreate) SaveX(ctx context.Context) *Plan {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PlanCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PlanCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PlanCreate) defaults() {
	if _, ok := _c.mutation.PriceMonth(); !ok {
		v := plan.DefaultPriceMonth
		_c.mutation.SetPriceMonth(v)
	}
	if _, ok := _c.mutation.PriceYear(); !ok {
		v := plan.DefaultPriceYear
		_c.mutation.SetPriceYear(v)
	}
	if _, ok := _c.mutation.BasicTokenQuota(); !ok {
		v := plan.DefaultBasicTokenQuota
		_c.mutation.SetBasicTokenQuota(v)
	}
	if _, ok := _c.mutation.ProTokenQuota(); !ok {
		v := plan.DefaultProTokenQuota
		_c.mutation.SetProTokenQuota(v)
	}
	if _, ok := _c.mutation.UltraTokenQuota(); !ok {
		v := plan.DefaultUltraTokenQuota
		_c.mutation.SetUltraTokenQuota(v)
	}
	if _, ok := _c.mutation.MonthlyCredits(); !ok {
		v := plan.DefaultMonthlyCredits
		_c.mutation.SetMonthlyCredits(v)
	}
	if _, ok := _c.mutation.MaxConcurrency(); !ok {
		v := plan.DefaultMaxConcurrency
		_c.mutation.SetMaxConcurrency(v)
	}
	if _, ok := _c.mutation.IsDefault(); !ok {
		v := plan.DefaultIsDefault
		_c.mutation.SetIsDefault(v)
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		v := plan.DefaultIsActive
		_c.mutation.SetIsActive(v)
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := plan.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := plan.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := plan.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PlanCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`db: missing required field "Plan.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := plan.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`db: validator failed for field "Plan.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PriceMonth(); !ok {
		return &ValidationError{Name: "price_month", err: errors.New(`db: missing required field "Plan.price_month"`)}
	}
	if _, ok := _c.mutation.PriceYear(); !ok {
		return &ValidationError{Name: "price_year", err: errors.New(`db: missing required field "Plan.price_year"`)}
	}
	if _, ok := _c.mutation.BasicTokenQuota(); !ok {
		return &ValidationError{Name: "basic_token_quota", err: errors.New(`db: missing required field "Plan.basic_token_quota"`)}
	}
	if _, ok := _c.mutation.ProTokenQuota(); !ok {
		return &ValidationError{Name: "pro_token_quota", err: errors.New(`db: missing required field "Plan.pro_token_quota"`)}
	}
	if _, ok := _c.mutation.UltraTokenQuota(); !ok {
		return &ValidationError{Name: "ultra_token_quota", err: errors.New(`db: missing required field "Plan.ultra_token_quota"`)}
	}
	if _, ok := _c.mutation.MonthlyCredits(); !ok {
		return &ValidationError{Name: "monthly_credits", err: errors.New(`db: missing required field "Plan.monthly_credits"`)}
	}
	if _, ok := _c.mutation.MaxConcurrency(); !ok {
		return &ValidationError{Name: "max_concurrency", err: errors.New(`db: missing required field "Plan.max_concurrency"`)}
	}
	if _, ok := _c.mutation.IsDefault(); !ok {
		return &ValidationError{Name: "is_default", err: errors.New(`db: missing required field "Plan.is_default"`)}
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		return &ValidationError{Name: "is_active", err: errors.New(`db: missing required field "Plan.is_active"`)}
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`db: missing required field "Plan.sort_order"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`db: missing required field "Plan.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`db: missing required field "Plan.updated_at"`)}
	}
	return nil
}

func (_c *PlanCreate) sqlSave(ctx context.Context) (*Plan, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PlanCreate) createSpec() (*Plan, *sqlgraph.CreateSpec) {
	var (
		_node = &Plan{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(plan.Table, sqlgraph.NewFieldSpec(plan.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(plan.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.DisplayName(); ok {
		_spec.SetField(plan.FieldDisplayName, field.TypeString, value)
		_node.DisplayName = value
	}
	if value, ok := _c.mutation.PriceMonth(); ok {
		_spec.SetField(plan.FieldPriceMonth, field.TypeInt64, value)
		_node.PriceMonth = value
	}
	if value, ok := _c.mutation.PriceYear(); ok {
		_spec.SetField(plan.FieldPriceYear, field.TypeInt64, value)
		_node.PriceYear = value
	}
	if value, ok := _c.mutation.BasicTokenQuota(); ok {
		_spec.SetField(plan.FieldBasicTokenQuota, field.TypeInt64, value)
		_node.BasicTokenQuota = value
	}
	if value, ok := _c.mutation.ProTokenQuota(); ok {
		_spec.SetField(plan.FieldProTokenQuota, field.TypeInt64, value)
		_node.ProTokenQuota = value
	}
	if value, ok := _c.mutation.UltraTokenQuota(); ok {
		_spec.SetField(plan.FieldUltraTokenQuota, field.TypeInt64, value)
		_node.UltraTokenQuota = value
	}
	if value, ok := _c.mutation.MonthlyCredits(); ok {
		_spec.SetField(plan.FieldMonthlyCredits, field.TypeInt64, value)
		_node.MonthlyCredits = value
	}
	if value, ok := _c.mutation.MaxConcurrency(); ok {
		_spec.SetField(plan.FieldMaxConcurrency, field.TypeInt, value)
		_node.MaxConcurrency = value
	}
	if value, ok := _c.mutation.Features(); ok {
		_spec.SetField(plan.FieldFeatures, field.TypeJSON, value)
		_node.Features = value
	}
	if value, ok := _c.mutation.IsDefault(); ok {
		_spec.SetField(plan.FieldIsDefault, field.TypeBool, value)
		_node.IsDefault = value
	}
	if value, ok := _c.mutation.IsActive(); ok {
		_spec.SetField(plan.FieldIsActive, field.TypeBool, value)
		_node.IsActive = value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(plan.FieldSortOrder, field.TypeInt, value)
		_node.SortOrder = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(plan.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(plan.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.SubscriptionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   plan.SubscriptionsTable,
			Columns: []string{plan.SubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Plan.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PlanUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *PlanCreate) OnConflict(opts ...sql.ConflictOption) *PlanUpsertOne {
	_c.conflict = opts
	return &PlanUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Plan.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PlanCreate) OnConflictColumns(columns ...string) *PlanUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PlanUpsertOne{
		create: _c,
	}
}

type (
	// PlanUpsertOne is the builder for "upsert"-ing
	//  one Plan node.
	PlanUpsertOne struct {
		create *PlanCreate
	}

	// PlanUpsert is the "OnConflict" setter.
	PlanUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *PlanUpsert) SetName(v string) *PlanUpsert {
	u.Set(plan.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *PlanUpsert) UpdateName() *PlanUpsert {
	u.SetExcluded(plan.FieldName)
	return u
}

// SetDisplayName sets the "display_name" field.
func (u *PlanUpsert) SetDisplayName(v string) *PlanUpsert {
	u.Set(plan.FieldDisplayName, v)
	return u
}

// UpdateDisplayName sets the "display_name" field to the value that was provided on create.
func (u *PlanUpsert) UpdateDisplayName() *PlanUpsert {
	u.SetExcluded(plan.FieldDisplayName)
	return u
}

// ClearDisplayName clears the value of the "display_name" field.
func (u *PlanUpsert) ClearDisplayName() *PlanUpsert {
	u.SetNull(plan.FieldDisplayName)
	return u
}

// SetPriceMonth sets the "price_month" field.
func (u *PlanUpsert) SetPriceMonth(v int64) *PlanUpsert {
	u.Set(plan.FieldPriceMonth, v)
	return u
}

// UpdatePriceMonth sets the "price_month" field to the value that was provided on create.
func (u *PlanUpsert) UpdatePriceMonth() *PlanUpsert {
	u.SetExcluded(plan.FieldPriceMonth)
	return u
}

// AddPriceMonth adds v to the "price_month" field.
func (u *PlanUpsert) AddPriceMonth(v int64) *PlanUpsert {
	u.Add(plan.FieldPriceMonth, v)
	return u
}

// SetPriceYear sets the "price_year" field.
func (u *PlanUpsert) SetPriceYear(v int64) *PlanUpsert {
	u.Set(plan.FieldPriceYear, v)
	return u
}

// UpdatePriceYear sets the "price_year" field to the value that was provided on create.
func (u *PlanUpsert) UpdatePriceYear() *PlanUpsert {
	u.SetExcluded(plan.FieldPriceYear)
	return u
}

// AddPriceYear adds v to the "price_year" field.
func (u *PlanUpsert) AddPriceYear(v int64) *PlanUpsert {
	u.Add(plan.FieldPriceYear, v)
	return u
}

// SetBasicTokenQuota sets the "basic_token_quota" field.
func (u *PlanUpsert) SetBasicTokenQuota(v int64) *PlanUpsert {
	u.Set(plan.FieldBasicTokenQuota, v)
	return u
}

// UpdateBasicTokenQuota sets the "basic_token_quota" field to the value that was provided on create.
func (u *PlanUpsert) UpdateBasicTokenQuota() *PlanUpsert {
	u.SetExcluded(plan.FieldBasicTokenQuota)
	return u
}

// AddBasicTokenQuota adds v to the "basic_token_quota" field.
func (u *PlanUpsert) AddBasicTokenQuota(v int64) *PlanUpsert {
	u.Add(plan.FieldBasicTokenQuota, v)
	return u
}

// SetProTokenQuota sets the "pro_token_quota" field.
func (u *PlanUpsert) SetProTokenQuota(v int64) *PlanUpsert {
	u.Set(plan.FieldProTokenQuota, v)
	return u
}

// UpdateProTokenQuota sets the "pro_token_quota" field to the value that was provided on create.
func (u *PlanUpsert) UpdateProTokenQuota() *PlanUpsert {
	u.SetExcluded(plan.FieldProTokenQuota)
	return u
}

// AddProTokenQuota adds v to the "pro_token_quota" field.
func (u *PlanUpsert) AddProTokenQuota(v int64) *PlanUpsert {
	u.Add(plan.FieldProTokenQuota, v)
	return u
}

// SetUltraTokenQuota sets the "ultra_token_quota" field.
func (u *PlanUpsert) SetUltraTokenQuota(v int64) *PlanUpsert {
	u.Set(plan.FieldUltraTokenQuota, v)
	return u
}

// UpdateUltraTokenQuota sets the "ultra_token_quota" field to the value that was provided on create.
func (u *PlanUpsert) UpdateUltraTokenQuota() *PlanUpsert {
	u.SetExcluded(plan.FieldUltraTokenQuota)
	return u
}

// AddUltraTokenQuota adds v to the "ultra_token_quota" field.
func (u *PlanUpsert) AddUltraTokenQuota(v int64) *PlanUpsert {
	u.Add(plan.FieldUltraTokenQuota, v)
	return u
}

// SetMonthlyCredits sets the "monthly_credits" field.
func (u *PlanUpsert) SetMonthlyCredits(v int64) *PlanUpsert {
	u.Set(plan.FieldMonthlyCredits, v)
	return u
}

// UpdateMonthlyCredits sets the "monthly_credits" field to the value that was provided on create.
func (u *PlanUpsert) UpdateMonthlyCredits() *PlanUpsert {
	u.SetExcluded(plan.FieldMonthlyCredits)
	return u
}

// AddMonthlyCredits adds v to the "monthly_credits" field.
func (u *PlanUpsert) AddMonthlyCredits(v int64) *PlanUpsert {
	u.Add(plan.FieldMonthlyCredits, v)
	return u
}

// SetMaxConcurrency sets the "max_concurrency" field.
func (u *PlanUpsert) SetMaxConcurrency(v int) *PlanUpsert {
	u.Set(plan.FieldMaxConcurrency, v)
	return u
}

// UpdateMaxConcurrency sets the "max_concurrency" field to the value that was provided on create.
func (u *PlanUpsert) UpdateMaxConcurrency() *PlanUpsert {
	u.SetExcluded(plan.FieldMaxConcurrency)
	return u
}

// AddMaxConcurrency adds v to the "max_concurrency" field.
func (u *PlanUpsert) AddMaxConcurrency(v int) *PlanUpsert {
	u.Add(plan.FieldMaxConcurrency, v)
	return u
}

// SetFeatures sets the "features" field.
func (u *PlanUpsert) SetFeatures(v []string) *PlanUpsert {
	u.Set(plan.FieldFeatures, v)
	return u
}

// UpdateFeatures sets the "features" field to the value that was provided on create.
func (u *PlanUpsert) UpdateFeatures() *PlanUpsert {
	u.SetExcluded(plan.FieldFeatures)
	return u
}

// ClearFeatures clears the value of the "features" field.
func (u *PlanUpsert) ClearFeatures() *PlanUpsert {
	u.SetNull(plan.FieldFeatures)
	return u
}

// SetIsDefault sets the "is_default" field.
func (u *PlanUpsert) SetIsDefault(v bool) *PlanUpsert {
	u.Set(plan.FieldIsDefault, v)
	return u
}

// UpdateIsDefault sets the "is_default" field to the value that was provided on create.
func (u *PlanUpsert) UpdateIsDefault() *PlanUpsert {
	u.SetExcluded(plan.FieldIsDefault)
	return u
}

// SetIsActive sets the "is_active" field.
func (u *PlanUpsert) SetIsActive(v bool) *PlanUpsert {
	u.Set(plan.FieldIsActive, v)
	return u
}

// UpdateIsActive sets the "is_active" field to the value that was provided on create.
func (u *PlanUpsert) UpdateIsActive() *PlanUpsert {
	u.SetExcluded(plan.FieldIsActive)
	return u
}

// SetSortOrder sets the "sort_order" field.
func (u *PlanUpsert) SetSortOrder(v int) *PlanUpsert {
	u.Set(plan.FieldSortOrder, v)
	return u
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *PlanUpsert) UpdateSortOrder() *PlanUpsert {
	u.SetExcluded(plan.FieldSortOrder)
	return u
}

// AddSortOrder adds v to the "sort_order" field.
func (u *PlanUpsert) AddSortOrder(v int) *PlanUpsert {
	u.Add(plan.FieldSortOrder, v)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *PlanUpsert) SetCreatedAt(v time.Time) *PlanUpsert {
	u.Set(plan.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *PlanUpsert) UpdateCreatedAt() *PlanUpsert {
	u.SetExcluded(plan.FieldCreatedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PlanUpsert) SetUpdatedAt(v time.Time) *PlanUpsert {
	u.Set(plan.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PlanUpsert) UpdateUpdatedAt() *PlanUpsert {
	u.SetExcluded(plan.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Plan.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(plan.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *PlanUpsertOne) UpdateNewValues() *PlanUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(plan.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Plan.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PlanUpsertOne) Ignore() *PlanUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PlanUpsertOne) DoNothing() *PlanUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PlanCreate.OnConflict
// documentation for more info.
func (u *PlanUpsertOne) Update(set func(*PlanUpsert)) *PlanUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PlanUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *PlanUpsertOne) SetName(v string) *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *PlanUpsertOne) UpdateName() *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.UpdateName()
	})
}

// SetDisplayName sets the "display_name" field.
func (u *PlanUpsertOne) SetDisplayName(v string) *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.SetDisplayName(v)
	})
}

// UpdateDisplayName sets the "display_name" field to the value that was provided on create.
func (u *PlanUpsertOne) UpdateDisplayName() *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.UpdateDisplayName()
	})
}

// ClearDisplayName clears the value of the "display_name" field.
func (u *PlanUpsertOne) ClearDisplayName() *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.ClearDisplayName()
	})
}

// SetPriceMonth sets the "price_month" field.
func (u *PlanUpsertOne) SetPriceMonth(v int64) *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.SetPriceMonth(v)
	})
}

// AddPriceMonth adds v to the "price_month" field.
func (u *PlanUpsertOne) AddPriceMonth(v int64) *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.AddPriceMonth(v)
	})
}

// UpdatePriceMonth sets the "price_month" field to the value that was provided on create.
func (u *PlanUpsertOne) UpdatePriceMonth() *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.UpdatePriceMonth()
	})
}

// SetPriceYear sets the "price_year" field.
func (u *PlanUpsertOne) SetPriceYear(v int64) *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.SetPriceYear(v)
	})
}

// AddPriceYear adds v to the "price_year" field.
func (u *PlanUpsertOne) AddPriceYear(v int64) *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.AddPriceYear(v)
	})
}

// UpdatePriceYear sets the "price_year" field to the value that was provided on create.
func (u *PlanUpsertOne) UpdatePriceYear() *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.UpdatePriceYear()
	})
}

// SetBasicTokenQuota sets the "basic_token_quota" field.
func (u *PlanUpsertOne) SetBasicTokenQuota(v int64) *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.SetBasicTokenQuota(v)
	})
}

// AddBasicTokenQuota adds v to the "basic_token_quota" field.
func (u *PlanUpsertOne) AddBasicTokenQuota(v int64) *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.AddBasicTokenQuota(v)
	})
}

// UpdateBasicTokenQuota sets the "basic_token_quota" field to the value that was provided on create.
func (u *PlanUpsertOne) UpdateBasicTokenQuota() *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.UpdateBasicTokenQuota()
	})
}

// SetProTokenQuota sets the "pro_token_quota" field.
func (u *PlanUpsertOne) SetProTokenQuota(v int64) *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.SetProTokenQuota(v)
	})
}

// AddProTokenQuota adds v to the "pro_token_quota" field.
func (u *PlanUpsertOne) AddProTokenQuota(v int64) *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.AddProTokenQuota(v)
	})
}

// UpdateProTokenQuota sets the "pro_token_quota" field to the value that was provided on create.
func (u *PlanUpsertOne) UpdateProTokenQuota() *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.UpdateProTokenQuota()
	})
}

// SetUltraTokenQuota sets the "ultra_token_quota" field.
func (u *PlanUpsertOne) SetUltraTokenQuota(v int64) *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.SetUltraTokenQuota(v)
	})
}

// AddUltraTokenQuota adds v to the "ultra_token_quota" field.
func (u *PlanUpsertOne) AddUltraTokenQuota(v int64) *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.AddUltraTokenQuota(v)
	})
}

// UpdateUltraTokenQuota sets the "ultra_token_quota" field to the value that was provided on create.
func (u *PlanUpsertOne) UpdateUltraTokenQuota() *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.UpdateUltraTokenQuota()
	})
}

// SetMonthlyCredits sets the "monthly_credits" field.
func (u *PlanUpsertOne) SetMonthlyCredits(v int64) *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.SetMonthlyCredits(v)
	})
}

// AddMonthlyCredits adds v to the "monthly_credits" field.
func (u *PlanUpsertOne) AddMonthlyCredits(v int64) *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.AddMonthlyCredits(v)
	})
}

// UpdateMonthlyCredits sets the "monthly_credits" field to the value that was provided on create.
func (u *PlanUpsertOne) UpdateMonthlyCredits() *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.UpdateMonthlyCredits()
	})
}

// SetMaxConcurrency sets the "max_concurrency" field.
func (u *PlanUpsertOne) SetMaxConcurrency(v int) *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.SetMaxConcurrency(v)
	})
}

// AddMaxConcurrency adds v to the "max_concurrency" field.
func (u *PlanUpsertOne) AddMaxConcurrency(v int) *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.AddMaxConcurrency(v)
	})
}

// UpdateMaxConcurrency sets the "max_concurrency" field to the value that was provided on create.
func (u *PlanUpsertOne) UpdateMaxConcurrency() *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.UpdateMaxConcurrency()
	})
}

// SetFeatures sets the "features" field.
func (u *PlanUpsertOne) SetFeatures(v []string) *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.SetFeatures(v)
	})
}

// UpdateFeatures sets the "features" field to the value that was provided on create.
func (u *PlanUpsertOne) UpdateFeatures() *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.UpdateFeatures()
	})
}

// ClearFeatures clears the value of the "features" field.
func (u *PlanUpsertOne) ClearFeatures() *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.ClearFeatures()
	})
}

// SetIsDefault sets the "is_default" field.
func (u *PlanUpsertOne) SetIsDefault(v bool) *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.SetIsDefault(v)
	})
}

// UpdateIsDefault sets the "is_default" field to the value that was provided on create.
func (u *PlanUpsertOne) UpdateIsDefault() *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.UpdateIsDefault()
	})
}

// SetIsActive sets the "is_active" field.
func (u *PlanUpsertOne) SetIsActive(v bool) *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.SetIsActive(v)
	})
}

// UpdateIsActive sets the "is_active" field to the value that was provided on create.
func (u *PlanUpsertOne) UpdateIsActive() *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.UpdateIsActive()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *PlanUpsertOne) SetSortOrder(v int) *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *PlanUpsertOne) AddSortOrder(v int) *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *PlanUpsertOne) UpdateSortOrder() *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.UpdateSortOrder()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *PlanUpsertOne) SetCreatedAt(v time.Time) *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *PlanUpsertOne) UpdateCreatedAt() *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PlanUpsertOne) SetUpdatedAt(v time.Time) *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PlanUpsertOne) UpdateUpdatedAt() *PlanUpsertOne {
	return u.Update(func(s *PlanUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *PlanUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("db: missing options for PlanCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PlanUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PlanUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("db: PlanUpsertOne.ID is not supported by MySQL driver. Use PlanUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PlanUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PlanCreateBulk is the builder for creating many Plan entities in bulk.
type PlanCreateBulk struct {
	config
	err      error
	builders []*PlanCreate
	conflict []sql.ConflictOption
}

// Save creates the Plan entities in the database.
func (_c *PlanCreateBulk) Save(ctx context.Context) ([]*Plan, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Plan, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PlanMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PlanCreateBulk) SaveX(ctx context.Context) []*Plan {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PlanCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PlanCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Plan.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PlanUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *PlanCreateBulk) OnConflict(opts ...sql.ConflictOption) *PlanUpsertBulk {
	_c.conflict = opts
	return &PlanUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Plan.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PlanCreateBulk) OnConflictColumns(columns ...string) *PlanUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PlanUpsertBulk{
		create: _c,
	}
}

// PlanUpsertBulk is the builder for "upsert"-ing
// a bulk of Plan nodes.
type PlanUpsertBulk struct {
	create *PlanCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Plan.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(plan.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *PlanUpsertBulk) UpdateNewValues() *PlanUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(plan.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Plan.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PlanUpsertBulk) Ignore() *PlanUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PlanUpsertBulk) DoNothing() *PlanUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PlanCreateBulk.OnConflict
// documentation for more info.
func (u *PlanUpsertBulk) Update(set func(*PlanUpsert)) *PlanUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PlanUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *PlanUpsertBulk) SetName(v string) *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *PlanUpsertBulk) UpdateName() *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.UpdateName()
	})
}

// SetDisplayName sets the "display_name" field.
func (u *PlanUpsertBulk) SetDisplayName(v string) *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.SetDisplayName(v)
	})
}

// UpdateDisplayName sets the "display_name" field to the value that was provided on create.
func (u *PlanUpsertBulk) UpdateDisplayName() *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.UpdateDisplayName()
	})
}

// ClearDisplayName clears the value of the "display_name" field.
func (u *PlanUpsertBulk) ClearDisplayName() *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.ClearDisplayName()
	})
}

// SetPriceMonth sets the "price_month" field.
func (u *PlanUpsertBulk) SetPriceMonth(v int64) *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.SetPriceMonth(v)
	})
}

// AddPriceMonth adds v to the "price_month" field.
func (u *PlanUpsertBulk) AddPriceMonth(v int64) *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.AddPriceMonth(v)
	})
}

// UpdatePriceMonth sets the "price_month" field to the value that was provided on create.
func (u *PlanUpsertBulk) UpdatePriceMonth() *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.UpdatePriceMonth()
	})
}

// SetPriceYear sets the "price_year" field.
func (u *PlanUpsertBulk) SetPriceYear(v int64) *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.SetPriceYear(v)
	})
}

// AddPriceYear adds v to the "price_year" field.
func (u *PlanUpsertBulk) AddPriceYear(v int64) *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.AddPriceYear(v)
	})
}

// UpdatePriceYear sets the "price_year" field to the value that was provided on create.
func (u *PlanUpsertBulk) UpdatePriceYear() *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.UpdatePriceYear()
	})
}

// SetBasicTokenQuota sets the "basic_token_quota" field.
func (u *PlanUpsertBulk) SetBasicTokenQuota(v int64) *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.SetBasicTokenQuota(v)
	})
}

// AddBasicTokenQuota adds v to the "basic_token_quota" field.
func (u *PlanUpsertBulk) AddBasicTokenQuota(v int64) *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.AddBasicTokenQuota(v)
	})
}

// UpdateBasicTokenQuota sets the "basic_token_quota" field to the value that was provided on create.
func (u *PlanUpsertBulk) UpdateBasicTokenQuota() *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.UpdateBasicTokenQuota()
	})
}

// SetProTokenQuota sets the "pro_token_quota" field.
func (u *PlanUpsertBulk) SetProTokenQuota(v int64) *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.SetProTokenQuota(v)
	})
}

// AddProTokenQuota adds v to the "pro_token_quota" field.
func (u *PlanUpsertBulk) AddProTokenQuota(v int64) *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.AddProTokenQuota(v)
	})
}

// UpdateProTokenQuota sets the "pro_token_quota" field to the value that was provided on create.
func (u *PlanUpsertBulk) UpdateProTokenQuota() *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.UpdateProTokenQuota()
	})
}

// SetUltraTokenQuota sets the "ultra_token_quota" field.
func (u *PlanUpsertBulk) SetUltraTokenQuota(v int64) *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.SetUltraTokenQuota(v)
	})
}

// AddUltraTokenQuota adds v to the "ultra_token_quota" field.
func (u *PlanUpsertBulk) AddUltraTokenQuota(v int64) *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.AddUltraTokenQuota(v)
	})
}

// UpdateUltraTokenQuota sets the "ultra_token_quota" field to the value that was provided on create.
func (u *PlanUpsertBulk) UpdateUltraTokenQuota() *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.UpdateUltraTokenQuota()
	})
}

// SetMonthlyCredits sets the "monthly_credits" field.
func (u *PlanUpsertBulk) SetMonthlyCredits(v int64) *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.SetMonthlyCredits(v)
	})
}

// AddMonthlyCredits adds v to the "monthly_credits" field.
func (u *PlanUpsertBulk) AddMonthlyCredits(v int64) *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.AddMonthlyCredits(v)
	})
}

// UpdateMonthlyCredits sets the "monthly_credits" field to the value that was provided on create.
func (u *PlanUpsertBulk) UpdateMonthlyCredits() *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.UpdateMonthlyCredits()
	})
}

// SetMaxConcurrency sets the "max_concurrency" field.
func (u *PlanUpsertBulk) SetMaxConcurrency(v int) *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.SetMaxConcurrency(v)
	})
}

// AddMaxConcurrency adds v to the "max_concurrency" field.
func (u *PlanUpsertBulk) AddMaxConcurrency(v int) *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.AddMaxConcurrency(v)
	})
}

// UpdateMaxConcurrency sets the "max_concurrency" field to the value that was provided on create.
func (u *PlanUpsertBulk) UpdateMaxConcurrency() *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.UpdateMaxConcurrency()
	})
}

// SetFeatures sets the "features" field.
func (u *PlanUpsertBulk) SetFeatures(v []string) *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.SetFeatures(v)
	})
}

// UpdateFeatures sets the "features" field to the value that was provided on create.
func (u *PlanUpsertBulk) UpdateFeatures() *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.UpdateFeatures()
	})
}

// ClearFeatures clears the value of the "features" field.
func (u *PlanUpsertBulk) ClearFeatures() *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.ClearFeatures()
	})
}

// SetIsDefault sets the "is_default" field.
func (u *PlanUpsertBulk) SetIsDefault(v bool) *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.SetIsDefault(v)
	})
}

// UpdateIsDefault sets the "is_default" field to the value that was provided on create.
func (u *PlanUpsertBulk) UpdateIsDefault() *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.UpdateIsDefault()
	})
}

// SetIsActive sets the "is_active" field.
func (u *PlanUpsertBulk) SetIsActive(v bool) *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.SetIsActive(v)
	})
}

// UpdateIsActive sets the "is_active" field to the value that was provided on create.
func (u *PlanUpsertBulk) UpdateIsActive() *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.UpdateIsActive()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *PlanUpsertBulk) SetSortOrder(v int) *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *PlanUpsertBulk) AddSortOrder(v int) *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *PlanUpsertBulk) UpdateSortOrder() *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.UpdateSortOrder()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *PlanUpsertBulk) SetCreatedAt(v time.Time) *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *PlanUpsertBulk) UpdateCreatedAt() *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PlanUpsertBulk) SetUpdatedAt(v time.Time) *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PlanUpsertBulk) UpdateUpdatedAt() *PlanUpsertBulk {
	return u.Update(func(s *PlanUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *PlanUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("db: OnConflict was set for builder %d. Set it on the PlanCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("db: missing options for PlanCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PlanUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
