// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/nidao003/mclaw/backend/db/predicate"
	"github.com/nidao003/mclaw/backend/db/skill"
	"github.com/nidao003/mclaw/backend/db/skillreview"
)

// SkillReviewUpdate is the builder for updating SkillReview entities.
type SkillReviewUpdate struct {
	config
	hooks     []Hook
	mutation  *SkillReviewMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the SkillReviewUpdate builder.
func (_u *SkillReviewUpdate) Where(ps ...predicate.SkillReview) *SkillReviewUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSkillID sets the "skill_id" field.
func (_u *SkillReviewUpdate) SetSkillID(v uuid.UUID) *SkillReviewUpdate {
	_u.mutation.SetSkillID(v)
	return _u
}

// SetNillableSkillID sets the "skill_id" field if the given value is not nil.
func (_u *SkillReviewUpdate) SetNillableSkillID(v *uuid.UUID) *SkillReviewUpdate {
	if v != nil {
		_u.SetSkillID(*v)
	}
	return _u
}

// SetReviewerID sets the "reviewer_id" field.
func (_u *SkillReviewUpdate) SetReviewerID(v uuid.UUID) *SkillReviewUpdate {
	_u.mutation.SetReviewerID(v)
	return _u
}

// SetNillableReviewerID sets the "reviewer_id" field if the given value is not nil.
func (_u *SkillReviewUpdate) SetNillableReviewerID(v *uuid.UUID) *SkillReviewUpdate {
	if v != nil {
		_u.SetReviewerID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SkillReviewUpdate) SetStatus(v string) *SkillReviewUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SkillReviewUpdate) SetNillableStatus(v *string) *SkillReviewUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetComment sets the "comment" field.
func (_u *SkillReviewUpdate) SetComment(v string) *SkillReviewUpdate {
	_u.mutation.SetComment(v)
	return _u
}

// SetNillableComment sets the "comment" field if the given value is not nil.
func (_u *SkillReviewUpdate) SetNillableComment(v *string) *SkillReviewUpdate {
	if v != nil {
		_u.SetComment(*v)
	}
	return _u
}

// ClearComment clears the value of the "comment" field.
func (_u *SkillReviewUpdate) ClearComment() *SkillReviewUpdate {
	_u.mutation.ClearComment()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *SkillReviewUpdate) SetCreatedAt(v time.Time) *SkillReviewUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *SkillReviewUpdate) SetNillableCreatedAt(v *time.Time) *SkillReviewUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetSkill sets the "skill" edge to the Skill entity.
func (_u *SkillReviewUpdate) SetSkill(v *Skill) *SkillReviewUpdate {
	return _u.SetSkillID(v.ID)
}

// Mutation returns the SkillReviewMutation object of the builder.
func (_u *SkillReviewUpdate) Mutation() *SkillReviewMutation {
	return _u.mutation
}

// ClearSkill clears the "skill" edge to the Skill entity.
func (_u *SkillReviewUpdate) ClearSkill() *SkillReviewUpdate {
	_u.mutation.ClearSkill()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SkillReviewUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SkillReviewUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SkillReviewUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SkillReviewUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SkillReviewUpdate) check() error {
	if _u.mutation.SkillCleared() && len(_u.mutation.SkillIDs()) > 0 {
		return errors.New(`db: clearing a required unique edge "SkillReview.skill"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *SkillReviewUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *SkillReviewUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *SkillReviewUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(skillreview.Table, skillreview.Columns, sqlgraph.NewFieldSpec(skillreview.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ReviewerID(); ok {
		_spec.SetField(skillreview.FieldReviewerID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(skillreview.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Comment(); ok {
		_spec.SetField(skillreview.FieldComment, field.TypeString, value)
	}
	if _u.mutation.CommentCleared() {
		_spec.ClearField(skillreview.FieldComment, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(skillreview.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.SkillCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   skillreview.SkillTable,
			Columns: []string{skillreview.SkillColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(skill.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SkillIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   skillreview.SkillTable,
			Columns: []string{skillreview.SkillColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(skill.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{skillreview.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SkillReviewUpdateOne is the builder for updating a single SkillReview entity.
type SkillReviewUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *SkillReviewMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetSkillID sets the "skill_id" field.
func (_u *SkillReviewUpdateOne) SetSkillID(v uuid.UUID) *SkillReviewUpdateOne {
	_u.mutation.SetSkillID(v)
	return _u
}

// SetNillableSkillID sets the "skill_id" field if the given value is not nil.
func (_u *SkillReviewUpdateOne) SetNillableSkillID(v *uuid.UUID) *SkillReviewUpdateOne {
	if v != nil {
		_u.SetSkillID(*v)
	}
	return _u
}

// SetReviewerID sets the "reviewer_id" field.
func (_u *SkillReviewUpdateOne) SetReviewerID(v uuid.UUID) *SkillReviewUpdateOne {
	_u.mutation.SetReviewerID(v)
	return _u
}

// SetNillableReviewerID sets the "reviewer_id" field if the given value is not nil.
func (_u *SkillReviewUpdateOne) SetNillableReviewerID(v *uuid.UUID) *SkillReviewUpdateOne {
	if v != nil {
		_u.SetReviewerID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SkillReviewUpdateOne) SetStatus(v string) *SkillReviewUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SkillReviewUpdateOne) SetNillableStatus(v *string) *SkillReviewUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetComment sets the "comment" field.
func (_u *SkillReviewUpdateOne) SetComment(v string) *SkillReviewUpdateOne {
	_u.mutation.SetComment(v)
	return _u
}

// SetNillableComment sets the "comment" field if the given value is not nil.
func (_u *SkillReviewUpdateOne) SetNillableComment(v *string) *SkillReviewUpdateOne {
	if v != nil {
		_u.SetComment(*v)
	}
	return _u
}

// ClearComment clears the value of the "comment" field.
func (_u *SkillReviewUpdateOne) ClearComment() *SkillReviewUpdateOne {
	_u.mutation.ClearComment()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *SkillReviewUpdateOne) SetCreatedAt(v time.Time) *SkillReviewUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *SkillReviewUpdateOne) SetNillableCreatedAt(v *time.Time) *SkillReviewUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetSkill sets the "skill" edge to the Skill entity.
func (_u *SkillReviewUpdateOne) SetSkill(v *Skill) *SkillReviewUpdateOne {
	return _u.SetSkillID(v.ID)
}

// Mutation returns the SkillReviewMutation object of the builder.
func (_u *SkillReviewUpdateOne) Mutation() *SkillReviewMutation {
	return _u.mutation
}

// ClearSkill clears the "skill" edge to the Skill entity.
func (_u *SkillReviewUpdateOne) ClearSkill() *SkillReviewUpdateOne {
	_u.mutation.ClearSkill()
	return _u
}

// Where appends a list predicates to the SkillReviewUpdate builder.
func (_u *SkillReviewUpdateOne) Where(ps ...predicate.SkillReview) *SkillReviewUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SkillReviewUpdateOne) Select(field string, fields ...string) *SkillReviewUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SkillReview entity.
func (_u *SkillReviewUpdateOne) Save(ctx context.Context) (*SkillReview, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SkillReviewUpdateOne) SaveX(ctx context.Context) *SkillReview {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SkillReviewUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SkillReviewUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SkillReviewUpdateOne) check() error {
	if _u.mutation.SkillCleared() && len(_u.mutation.SkillIDs()) > 0 {
		return errors.New(`db: clearing a required unique edge "SkillReview.skill"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *SkillReviewUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *SkillReviewUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *SkillReviewUpdateOne) sqlSave(ctx context.Context) (_node *SkillReview, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(skillreview.Table, skillreview.Columns, sqlgraph.NewFieldSpec(skillreview.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`db: missing "SkillReview.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, skillreview.FieldID)
		for _, f := range fields {
			if !skillreview.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("db: invalid field %q for query", f)}
			}
			if f != skillreview.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ReviewerID(); ok {
		_spec.SetField(skillreview.FieldReviewerID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(skillreview.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Comment(); ok {
		_spec.SetField(skillreview.FieldComment, field.TypeString, value)
	}
	if _u.mutation.CommentCleared() {
		_spec.ClearField(skillreview.FieldComment, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(skillreview.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.SkillCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   skillreview.SkillTable,
			Columns: []string{skillreview.SkillColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(skill.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SkillIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   skillreview.SkillTable,
			Columns: []string{skillreview.SkillColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(skill.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &SkillReview{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{skillreview.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
