// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/nidao003/mclaw/backend/consts"
	"github.com/nidao003/mclaw/backend/db/predicate"
	"github.com/nidao003/mclaw/backend/db/transactionlog"
)

// TransactionLogUpdate is the builder for updating TransactionLog entities.
type TransactionLogUpdate struct {
	config
	hooks     []Hook
	mutation  *TransactionLogMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the TransactionLogUpdate builder.
func (_u *TransactionLogUpdate) Where(ps ...predicate.TransactionLog) *TransactionLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *TransactionLogUpdate) SetUserID(v uuid.UUID) *TransactionLogUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *TransactionLogUpdate) SetNillableUserID(v *uuid.UUID) *TransactionLogUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetKind sets the "kind" field.
func (_u *TransactionLogUpdate) SetKind(v consts.TransactionKind) *TransactionLogUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *TransactionLogUpdate) SetNillableKind(v *consts.TransactionKind) *TransactionLogUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetInoutType sets the "inout_type" field.
func (_u *TransactionLogUpdate) SetInoutType(v consts.TransactionInoutType) *TransactionLogUpdate {
	_u.mutation.SetInoutType(v)
	return _u
}

// SetNillableInoutType sets the "inout_type" field if the given value is not nil.
func (_u *TransactionLogUpdate) SetNillableInoutType(v *consts.TransactionInoutType) *TransactionLogUpdate {
	if v != nil {
		_u.SetInoutType(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *TransactionLogUpdate) SetAmount(v int64) *TransactionLogUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *TransactionLogUpdate) SetNillableAmount(v *int64) *TransactionLogUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *TransactionLogUpdate) AddAmount(v int64) *TransactionLogUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetBalance sets the "balance" field.
func (_u *TransactionLogUpdate) SetBalance(v int64) *TransactionLogUpdate {
	_u.mutation.ResetBalance()
	_u.mutation.SetBalance(v)
	return _u
}

// SetNillableBalance sets the "balance" field if the given value is not nil.
func (_u *TransactionLogUpdate) SetNillableBalance(v *int64) *TransactionLogUpdate {
	if v != nil {
		_u.SetBalance(*v)
	}
	return _u
}

// AddBalance adds value to the "balance" field.
func (_u *TransactionLogUpdate) AddBalance(v int64) *TransactionLogUpdate {
	_u.mutation.AddBalance(v)
	return _u
}

// SetRemark sets the "remark" field.
func (_u *TransactionLogUpdate) SetRemark(v string) *TransactionLogUpdate {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *TransactionLogUpdate) SetNillableRemark(v *string) *TransactionLogUpdate {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// ClearRemark clears the value of the "remark" field.
func (_u *TransactionLogUpdate) ClearRemark() *TransactionLogUpdate {
	_u.mutation.ClearRemark()
	return _u
}

// SetSourceID sets the "source_id" field.
func (_u *TransactionLogUpdate) SetSourceID(v string) *TransactionLogUpdate {
	_u.mutation.SetSourceID(v)
	return _u
}

// SetNillableSourceID sets the "source_id" field if the given value is not nil.
func (_u *TransactionLogUpdate) SetNillableSourceID(v *string) *TransactionLogUpdate {
	if v != nil {
		_u.SetSourceID(*v)
	}
	return _u
}

// ClearSourceID clears the value of the "source_id" field.
func (_u *TransactionLogUpdate) ClearSourceID() *TransactionLogUpdate {
	_u.mutation.ClearSourceID()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *TransactionLogUpdate) SetCreatedAt(v time.Time) *TransactionLogUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *TransactionLogUpdate) SetNillableCreatedAt(v *time.Time) *TransactionLogUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the TransactionLogMutation object of the builder.
func (_u *TransactionLogUpdate) Mutation() *TransactionLogMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TransactionLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TransactionLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TransactionLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TransactionLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *TransactionLogUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *TransactionLogUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *TransactionLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(transactionlog.Table, transactionlog.Columns, sqlgraph.NewFieldSpec(transactionlog.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(transactionlog.FieldUserID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(transactionlog.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.InoutType(); ok {
		_spec.SetField(transactionlog.FieldInoutType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(transactionlog.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(transactionlog.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Balance(); ok {
		_spec.SetField(transactionlog.FieldBalance, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedBalance(); ok {
		_spec.AddField(transactionlog.FieldBalance, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(transactionlog.FieldRemark, field.TypeString, value)
	}
	if _u.mutation.RemarkCleared() {
		_spec.ClearField(transactionlog.FieldRemark, field.TypeString)
	}
	if value, ok := _u.mutation.SourceID(); ok {
		_spec.SetField(transactionlog.FieldSourceID, field.TypeString, value)
	}
	if _u.mutation.SourceIDCleared() {
		_spec.ClearField(transactionlog.FieldSourceID, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(transactionlog.FieldCreatedAt, field.TypeTime, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{transactionlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TransactionLogUpdateOne is the builder for updating a single TransactionLog entity.
type TransactionLogUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *TransactionLogMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUserID sets the "user_id" field.
func (_u *TransactionLogUpdateOne) SetUserID(v uuid.UUID) *TransactionLogUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *TransactionLogUpdateOne) SetNillableUserID(v *uuid.UUID) *TransactionLogUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetKind sets the "kind" field.
func (_u *TransactionLogUpdateOne) SetKind(v consts.TransactionKind) *TransactionLogUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *TransactionLogUpdateOne) SetNillableKind(v *consts.TransactionKind) *TransactionLogUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetInoutType sets the "inout_type" field.
func (_u *TransactionLogUpdateOne) SetInoutType(v consts.TransactionInoutType) *TransactionLogUpdateOne {
	_u.mutation.SetInoutType(v)
	return _u
}

// SetNillableInoutType sets the "inout_type" field if the given value is not nil.
func (_u *TransactionLogUpdateOne) SetNillableInoutType(v *consts.TransactionInoutType) *TransactionLogUpdateOne {
	if v != nil {
		_u.SetInoutType(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *TransactionLogUpdateOne) SetAmount(v int64) *TransactionLogUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *TransactionLogUpdateOne) SetNillableAmount(v *int64) *TransactionLogUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *TransactionLogUpdateOne) AddAmount(v int64) *TransactionLogUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetBalance sets the "balance" field.
func (_u *TransactionLogUpdateOne) SetBalance(v int64) *TransactionLogUpdateOne {
	_u.mutation.ResetBalance()
	_u.mutation.SetBalance(v)
	return _u
}

// SetNillableBalance sets the "balance" field if the given value is not nil.
func (_u *TransactionLogUpdateOne) SetNillableBalance(v *int64) *TransactionLogUpdateOne {
	if v != nil {
		_u.SetBalance(*v)
	}
	return _u
}

// AddBalance adds value to the "balance" field.
func (_u *TransactionLogUpdateOne) AddBalance(v int64) *TransactionLogUpdateOne {
	_u.mutation.AddBalance(v)
	return _u
}

// SetRemark sets the "remark" field.
func (_u *TransactionLogUpdateOne) SetRemark(v string) *TransactionLogUpdateOne {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *TransactionLogUpdateOne) SetNillableRemark(v *string) *TransactionLogUpdateOne {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// ClearRemark clears the value of the "remark" field.
func (_u *TransactionLogUpdateOne) ClearRemark() *TransactionLogUpdateOne {
	_u.mutation.ClearRemark()
	return _u
}

// SetSourceID sets the "source_id" field.
func (_u *TransactionLogUpdateOne) SetSourceID(v string) *TransactionLogUpdateOne {
	_u.mutation.SetSourceID(v)
	return _u
}

// SetNillableSourceID sets the "source_id" field if the given value is not nil.
func (_u *TransactionLogUpdateOne) SetNillableSourceID(v *string) *TransactionLogUpdateOne {
	if v != nil {
		_u.SetSourceID(*v)
	}
	return _u
}

// ClearSourceID clears the value of the "source_id" field.
func (_u *TransactionLogUpdateOne) ClearSourceID() *TransactionLogUpdateOne {
	_u.mutation.ClearSourceID()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *TransactionLogUpdateOne) SetCreatedAt(v time.Time) *TransactionLogUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *TransactionLogUpdateOne) SetNillableCreatedAt(v *time.Time) *TransactionLogUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the TransactionLogMutation object of the builder.
func (_u *TransactionLogUpdateOne) Mutation() *TransactionLogMutation {
	return _u.mutation
}

// Where appends a list predicates to the TransactionLogUpdate builder.
func (_u *TransactionLogUpdateOne) Where(ps ...predicate.TransactionLog) *TransactionLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TransactionLogUpdateOne) Select(field string, fields ...string) *TransactionLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TransactionLog entity.
func (_u *TransactionLogUpdateOne) Save(ctx context.Context) (*TransactionLog, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TransactionLogUpdateOne) SaveX(ctx context.Context) *TransactionLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TransactionLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TransactionLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *TransactionLogUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *TransactionLogUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *TransactionLogUpdateOne) sqlSave(ctx context.Context) (_node *TransactionLog, err error) {
	_spec := sqlgraph.NewUpdateSpec(transactionlog.Table, transactionlog.Columns, sqlgraph.NewFieldSpec(transactionlog.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`db: missing "TransactionLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, transactionlog.FieldID)
		for _, f := range fields {
			if !transactionlog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("db: invalid field %q for query", f)}
			}
			if f != transactionlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(transactionlog.FieldUserID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(transactionlog.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.InoutType(); ok {
		_spec.SetField(transactionlog.FieldInoutType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(transactionlog.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(transactionlog.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Balance(); ok {
		_spec.SetField(transactionlog.FieldBalance, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedBalance(); ok {
		_spec.AddField(transactionlog.FieldBalance, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(transactionlog.FieldRemark, field.TypeString, value)
	}
	if _u.mutation.RemarkCleared() {
		_spec.ClearField(transactionlog.FieldRemark, field.TypeString)
	}
	if value, ok := _u.mutation.SourceID(); ok {
		_spec.SetField(transactionlog.FieldSourceID, field.TypeString, value)
	}
	if _u.mutation.SourceIDCleared() {
		_spec.ClearField(transactionlog.FieldSourceID, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(transactionlog.FieldCreatedAt, field.TypeTime, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &TransactionLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{transactionlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
