// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/nidao003/mclaw/backend/db/predicate"
	"github.com/nidao003/mclaw/backend/db/user"
	"github.com/nidao003/mclaw/backend/db/userapikey"
)

// UserApiKeyUpdate is the builder for updating UserApiKey entities.
type UserApiKeyUpdate struct {
	config
	hooks     []Hook
	mutation  *UserApiKeyMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the UserApiKeyUpdate builder.
func (_u *UserApiKeyUpdate) Where(ps ...predicate.UserApiKey) *UserApiKeyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserApiKeyUpdate) SetUserID(v uuid.UUID) *UserApiKeyUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserApiKeyUpdate) SetNillableUserID(v *uuid.UUID) *UserApiKeyUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetKeyHash sets the "key_hash" field.
func (_u *UserApiKeyUpdate) SetKeyHash(v string) *UserApiKeyUpdate {
	_u.mutation.SetKeyHash(v)
	return _u
}

// SetNillableKeyHash sets the "key_hash" field if the given value is not nil.
func (_u *UserApiKeyUpdate) SetNillableKeyHash(v *string) *UserApiKeyUpdate {
	if v != nil {
		_u.SetKeyHash(*v)
	}
	return _u
}

// SetKeyPrefix sets the "key_prefix" field.
func (_u *UserApiKeyUpdate) SetKeyPrefix(v string) *UserApiKeyUpdate {
	_u.mutation.SetKeyPrefix(v)
	return _u
}

// SetNillableKeyPrefix sets the "key_prefix" field if the given value is not nil.
func (_u *UserApiKeyUpdate) SetNillableKeyPrefix(v *string) *UserApiKeyUpdate {
	if v != nil {
		_u.SetKeyPrefix(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *UserApiKeyUpdate) SetName(v string) *UserApiKeyUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *UserApiKeyUpdate) SetNillableName(v *string) *UserApiKeyUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetLastUsedAt sets the "last_used_at" field.
func (_u *UserApiKeyUpdate) SetLastUsedAt(v time.Time) *UserApiKeyUpdate {
	_u.mutation.SetLastUsedAt(v)
	return _u
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_u *UserApiKeyUpdate) SetNillableLastUsedAt(v *time.Time) *UserApiKeyUpdate {
	if v != nil {
		_u.SetLastUsedAt(*v)
	}
	return _u
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (_u *UserApiKeyUpdate) ClearLastUsedAt() *UserApiKeyUpdate {
	_u.mutation.ClearLastUsedAt()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *UserApiKeyUpdate) SetExpiresAt(v time.Time) *UserApiKeyUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *UserApiKeyUpdate) SetNillableExpiresAt(v *time.Time) *UserApiKeyUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *UserApiKeyUpdate) ClearExpiresAt() *UserApiKeyUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *UserApiKeyUpdate) SetIsActive(v bool) *UserApiKeyUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *UserApiKeyUpdate) SetNillableIsActive(v *bool) *UserApiKeyUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *UserApiKeyUpdate) SetCreatedAt(v time.Time) *UserApiKeyUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *UserApiKeyUpdate) SetNillableCreatedAt(v *time.Time) *UserApiKeyUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserApiKeyUpdate) SetUpdatedAt(v time.Time) *UserApiKeyUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserApiKeyUpdate) SetUser(v *User) *UserApiKeyUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the UserApiKeyMutation object of the builder.
func (_u *UserApiKeyUpdate) Mutation() *UserApiKeyMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserApiKeyUpdate) ClearUser() *UserApiKeyUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserApiKeyUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserApiKeyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserApiKeyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserApiKeyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserApiKeyUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := userapikey.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserApiKeyUpdate) check() error {
	if v, ok := _u.mutation.KeyHash(); ok {
		if err := userapikey.KeyHashValidator(v); err != nil {
			return &ValidationError{Name: "key_hash", err: fmt.Errorf(`db: validator failed for field "UserApiKey.key_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.KeyPrefix(); ok {
		if err := userapikey.KeyPrefixValidator(v); err != nil {
			return &ValidationError{Name: "key_prefix", err: fmt.Errorf(`db: validator failed for field "UserApiKey.key_prefix": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := userapikey.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`db: validator failed for field "UserApiKey.name": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`db: clearing a required unique edge "UserApiKey.user"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *UserApiKeyUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *UserApiKeyUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *UserApiKeyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userapikey.Table, userapikey.Columns, sqlgraph.NewFieldSpec(userapikey.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.KeyHash(); ok {
		_spec.SetField(userapikey.FieldKeyHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.KeyPrefix(); ok {
		_spec.SetField(userapikey.FieldKeyPrefix, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(userapikey.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastUsedAt(); ok {
		_spec.SetField(userapikey.FieldLastUsedAt, field.TypeTime, value)
	}
	if _u.mutation.LastUsedAtCleared() {
		_spec.ClearField(userapikey.FieldLastUsedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(userapikey.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(userapikey.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(userapikey.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(userapikey.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(userapikey.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userapikey.UserTable,
			Columns: []string{userapikey.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userapikey.UserTable,
			Columns: []string{userapikey.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userapikey.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserApiKeyUpdateOne is the builder for updating a single UserApiKey entity.
type UserApiKeyUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *UserApiKeyMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUserID sets the "user_id" field.
func (_u *UserApiKeyUpdateOne) SetUserID(v uuid.UUID) *UserApiKeyUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserApiKeyUpdateOne) SetNillableUserID(v *uuid.UUID) *UserApiKeyUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetKeyHash sets the "key_hash" field.
func (_u *UserApiKeyUpdateOne) SetKeyHash(v string) *UserApiKeyUpdateOne {
	_u.mutation.SetKeyHash(v)
	return _u
}

// SetNillableKeyHash sets the "key_hash" field if the given value is not nil.
func (_u *UserApiKeyUpdateOne) SetNillableKeyHash(v *string) *UserApiKeyUpdateOne {
	if v != nil {
		_u.SetKeyHash(*v)
	}
	return _u
}

// SetKeyPrefix sets the "key_prefix" field.
func (_u *UserApiKeyUpdateOne) SetKeyPrefix(v string) *UserApiKeyUpdateOne {
	_u.mutation.SetKeyPrefix(v)
	return _u
}

// SetNillableKeyPrefix sets the "key_prefix" field if the given value is not nil.
func (_u *UserApiKeyUpdateOne) SetNillableKeyPrefix(v *string) *UserApiKeyUpdateOne {
	if v != nil {
		_u.SetKeyPrefix(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *UserApiKeyUpdateOne) SetName(v string) *UserApiKeyUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *UserApiKeyUpdateOne) SetNillableName(v *string) *UserApiKeyUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetLastUsedAt sets the "last_used_at" field.
func (_u *UserApiKeyUpdateOne) SetLastUsedAt(v time.Time) *UserApiKeyUpdateOne {
	_u.mutation.SetLastUsedAt(v)
	return _u
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_u *UserApiKeyUpdateOne) SetNillableLastUsedAt(v *time.Time) *UserApiKeyUpdateOne {
	if v != nil {
		_u.SetLastUsedAt(*v)
	}
	return _u
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (_u *UserApiKeyUpdateOne) ClearLastUsedAt() *UserApiKeyUpdateOne {
	_u.mutation.ClearLastUsedAt()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *UserApiKeyUpdateOne) SetExpiresAt(v time.Time) *UserApiKeyUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *UserApiKeyUpdateOne) SetNillableExpiresAt(v *time.Time) *UserApiKeyUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *UserApiKeyUpdateOne) ClearExpiresAt() *UserApiKeyUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *UserApiKeyUpdateOne) SetIsActive(v bool) *UserApiKeyUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *UserApiKeyUpdateOne) SetNillableIsActive(v *bool) *UserApiKeyUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *UserApiKeyUpdateOne) SetCreatedAt(v time.Time) *UserApiKeyUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *UserApiKeyUpdateOne) SetNillableCreatedAt(v *time.Time) *UserApiKeyUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserApiKeyUpdateOne) SetUpdatedAt(v time.Time) *UserApiKeyUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserApiKeyUpdateOne) SetUser(v *User) *UserApiKeyUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the UserApiKeyMutation object of the builder.
func (_u *UserApiKeyUpdateOne) Mutation() *UserApiKeyMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserApiKeyUpdateOne) ClearUser() *UserApiKeyUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the UserApiKeyUpdate builder.
func (_u *UserApiKeyUpdateOne) Where(ps ...predicate.UserApiKey) *UserApiKeyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserApiKeyUpdateOne) Select(field string, fields ...string) *UserApiKeyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserApiKey entity.
func (_u *UserApiKeyUpdateOne) Save(ctx context.Context) (*UserApiKey, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserApiKeyUpdateOne) SaveX(ctx context.Context) *UserApiKey {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserApiKeyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserApiKeyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserApiKeyUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := userapikey.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserApiKeyUpdateOne) check() error {
	if v, ok := _u.mutation.KeyHash(); ok {
		if err := userapikey.KeyHashValidator(v); err != nil {
			return &ValidationError{Name: "key_hash", err: fmt.Errorf(`db: validator failed for field "UserApiKey.key_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.KeyPrefix(); ok {
		if err := userapikey.KeyPrefixValidator(v); err != nil {
			return &ValidationError{Name: "key_prefix", err: fmt.Errorf(`db: validator failed for field "UserApiKey.key_prefix": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := userapikey.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`db: validator failed for field "UserApiKey.name": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`db: clearing a required unique edge "UserApiKey.user"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *UserApiKeyUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *UserApiKeyUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *UserApiKeyUpdateOne) sqlSave(ctx context.Context) (_node *UserApiKey, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userapikey.Table, userapikey.Columns, sqlgraph.NewFieldSpec(userapikey.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`db: missing "UserApiKey.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userapikey.FieldID)
		for _, f := range fields {
			if !userapikey.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("db: invalid field %q for query", f)}
			}
			if f != userapikey.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.KeyHash(); ok {
		_spec.SetField(userapikey.FieldKeyHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.KeyPrefix(); ok {
		_spec.SetField(userapikey.FieldKeyPrefix, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(userapikey.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastUsedAt(); ok {
		_spec.SetField(userapikey.FieldLastUsedAt, field.TypeTime, value)
	}
	if _u.mutation.LastUsedAtCleared() {
		_spec.ClearField(userapikey.FieldLastUsedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(userapikey.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(userapikey.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(userapikey.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(userapikey.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(userapikey.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userapikey.UserTable,
			Columns: []string{userapikey.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userapikey.UserTable,
			Columns: []string{userapikey.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &UserApiKey{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userapikey.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
