ALTER TABLE skills
  ADD COLUMN IF NOT EXISTS source_type VARCHAR(32) NOT NULL DEFAULT 'official',
  ADD COLUMN IF NOT EXISTS icon_name VARCHAR(64),
  ADD COLUMN IF NOT EXISTS summary TEXT,
  ADD COLUMN IF NOT EXISTS minio_path VARCHAR(512),
  ADD COLUMN IF NOT EXISTS npm_publish_status VARCHAR(32) NOT NULL DEFAULT 'pending';

ALTER TABLE users
  ALTER COLUMN role SET DEFAULT 'user';
