export const MCLAW_OPENAI_IMAGE_PROVIDER_KEY = 'mclaw-openai-image';
export const MCLAW_OPENAI_IMAGE_DEFAULT_MODEL = 'gpt-image-2';
export const MCLAW_OPENAI_IMAGE_DEFAULT_REF = `${MCLAW_OPENAI_IMAGE_PROVIDER_KEY}/${MCLAW_OPENAI_IMAGE_DEFAULT_MODEL}`;
