// Code generated by ent, DO NOT EDIT.

package plan

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/nidao003/mclaw/backend/db/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Plan {
	return predicate.Plan(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Plan {
	return predicate.Plan(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Plan {
	return predicate.Plan(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Plan {
	return predicate.Plan(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Plan {
	return predicate.Plan(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Plan {
	return predicate.Plan(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Plan {
	return predicate.Plan(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldName, v))
}

// DisplayName applies equality check predicate on the "display_name" field. It's identical to DisplayNameEQ.
func DisplayName(v string) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldDisplayName, v))
}

// PriceMonth applies equality check predicate on the "price_month" field. It's identical to PriceMonthEQ.
func PriceMonth(v int64) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldPriceMonth, v))
}

// PriceYear applies equality check predicate on the "price_year" field. It's identical to PriceYearEQ.
func PriceYear(v int64) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldPriceYear, v))
}

// DailyTokenQuota applies equality check predicate on the "daily_token_quota" field. It's identical to DailyTokenQuotaEQ.
func DailyTokenQuota(v int64) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldDailyTokenQuota, v))
}

// WeeklyTokenQuota applies equality check predicate on the "weekly_token_quota" field. It's identical to WeeklyTokenQuotaEQ.
func WeeklyTokenQuota(v int64) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldWeeklyTokenQuota, v))
}

// MonthlyTokenQuota applies equality check predicate on the "monthly_token_quota" field. It's identical to MonthlyTokenQuotaEQ.
func MonthlyTokenQuota(v int64) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldMonthlyTokenQuota, v))
}

// MonthlyCredits applies equality check predicate on the "monthly_credits" field. It's identical to MonthlyCreditsEQ.
func MonthlyCredits(v int64) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldMonthlyCredits, v))
}

// BasicTokenQuota applies equality check predicate on the "basic_token_quota" field. It's identical to BasicTokenQuotaEQ.
func BasicTokenQuota(v int64) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldBasicTokenQuota, v))
}

// ProTokenQuota applies equality check predicate on the "pro_token_quota" field. It's identical to ProTokenQuotaEQ.
func ProTokenQuota(v int64) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldProTokenQuota, v))
}

// UltraTokenQuota applies equality check predicate on the "ultra_token_quota" field. It's identical to UltraTokenQuotaEQ.
func UltraTokenQuota(v int64) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldUltraTokenQuota, v))
}

// MaxConcurrency applies equality check predicate on the "max_concurrency" field. It's identical to MaxConcurrencyEQ.
func MaxConcurrency(v int) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldMaxConcurrency, v))
}

// IsDefault applies equality check predicate on the "is_default" field. It's identical to IsDefaultEQ.
func IsDefault(v bool) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldIsDefault, v))
}

// IsActive applies equality check predicate on the "is_active" field. It's identical to IsActiveEQ.
func IsActive(v bool) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldIsActive, v))
}

// SortOrder applies equality check predicate on the "sort_order" field. It's identical to SortOrderEQ.
func SortOrder(v int) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldSortOrder, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Plan {
	return predicate.Plan(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Plan {
	return predicate.Plan(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Plan {
	return predicate.Plan(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Plan {
	return predicate.Plan(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Plan {
	return predicate.Plan(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Plan {
	return predicate.Plan(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Plan {
	return predicate.Plan(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Plan {
	return predicate.Plan(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Plan {
	return predicate.Plan(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Plan {
	return predicate.Plan(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Plan {
	return predicate.Plan(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Plan {
	return predicate.Plan(sql.FieldContainsFold(FieldName, v))
}

// DisplayNameEQ applies the EQ predicate on the "display_name" field.
func DisplayNameEQ(v string) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldDisplayName, v))
}

// DisplayNameNEQ applies the NEQ predicate on the "display_name" field.
func DisplayNameNEQ(v string) predicate.Plan {
	return predicate.Plan(sql.FieldNEQ(FieldDisplayName, v))
}

// DisplayNameIn applies the In predicate on the "display_name" field.
func DisplayNameIn(vs ...string) predicate.Plan {
	return predicate.Plan(sql.FieldIn(FieldDisplayName, vs...))
}

// DisplayNameNotIn applies the NotIn predicate on the "display_name" field.
func DisplayNameNotIn(vs ...string) predicate.Plan {
	return predicate.Plan(sql.FieldNotIn(FieldDisplayName, vs...))
}

// DisplayNameGT applies the GT predicate on the "display_name" field.
func DisplayNameGT(v string) predicate.Plan {
	return predicate.Plan(sql.FieldGT(FieldDisplayName, v))
}

// DisplayNameGTE applies the GTE predicate on the "display_name" field.
func DisplayNameGTE(v string) predicate.Plan {
	return predicate.Plan(sql.FieldGTE(FieldDisplayName, v))
}

// DisplayNameLT applies the LT predicate on the "display_name" field.
func DisplayNameLT(v string) predicate.Plan {
	return predicate.Plan(sql.FieldLT(FieldDisplayName, v))
}

// DisplayNameLTE applies the LTE predicate on the "display_name" field.
func DisplayNameLTE(v string) predicate.Plan {
	return predicate.Plan(sql.FieldLTE(FieldDisplayName, v))
}

// DisplayNameContains applies the Contains predicate on the "display_name" field.
func DisplayNameContains(v string) predicate.Plan {
	return predicate.Plan(sql.FieldContains(FieldDisplayName, v))
}

// DisplayNameHasPrefix applies the HasPrefix predicate on the "display_name" field.
func DisplayNameHasPrefix(v string) predicate.Plan {
	return predicate.Plan(sql.FieldHasPrefix(FieldDisplayName, v))
}

// DisplayNameHasSuffix applies the HasSuffix predicate on the "display_name" field.
func DisplayNameHasSuffix(v string) predicate.Plan {
	return predicate.Plan(sql.FieldHasSuffix(FieldDisplayName, v))
}

// DisplayNameIsNil applies the IsNil predicate on the "display_name" field.
func DisplayNameIsNil() predicate.Plan {
	return predicate.Plan(sql.FieldIsNull(FieldDisplayName))
}

// DisplayNameNotNil applies the NotNil predicate on the "display_name" field.
func DisplayNameNotNil() predicate.Plan {
	return predicate.Plan(sql.FieldNotNull(FieldDisplayName))
}

// DisplayNameEqualFold applies the EqualFold predicate on the "display_name" field.
func DisplayNameEqualFold(v string) predicate.Plan {
	return predicate.Plan(sql.FieldEqualFold(FieldDisplayName, v))
}

// DisplayNameContainsFold applies the ContainsFold predicate on the "display_name" field.
func DisplayNameContainsFold(v string) predicate.Plan {
	return predicate.Plan(sql.FieldContainsFold(FieldDisplayName, v))
}

// PriceMonthEQ applies the EQ predicate on the "price_month" field.
func PriceMonthEQ(v int64) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldPriceMonth, v))
}

// PriceMonthNEQ applies the NEQ predicate on the "price_month" field.
func PriceMonthNEQ(v int64) predicate.Plan {
	return predicate.Plan(sql.FieldNEQ(FieldPriceMonth, v))
}

// PriceMonthIn applies the In predicate on the "price_month" field.
func PriceMonthIn(vs ...int64) predicate.Plan {
	return predicate.Plan(sql.FieldIn(FieldPriceMonth, vs...))
}

// PriceMonthNotIn applies the NotIn predicate on the "price_month" field.
func PriceMonthNotIn(vs ...int64) predicate.Plan {
	return predicate.Plan(sql.FieldNotIn(FieldPriceMonth, vs...))
}

// PriceMonthGT applies the GT predicate on the "price_month" field.
func PriceMonthGT(v int64) predicate.Plan {
	return predicate.Plan(sql.FieldGT(FieldPriceMonth, v))
}

// PriceMonthGTE applies the GTE predicate on the "price_month" field.
func PriceMonthGTE(v int64) predicate.Plan {
	return predicate.Plan(sql.FieldGTE(FieldPriceMonth, v))
}

// PriceMonthLT applies the LT predicate on the "price_month" field.
func PriceMonthLT(v int64) predicate.Plan {
	return predicate.Plan(sql.FieldLT(FieldPriceMonth, v))
}

// PriceMonthLTE applies the LTE predicate on the "price_month" field.
func PriceMonthLTE(v int64) predicate.Plan {
	return predicate.Plan(sql.FieldLTE(FieldPriceMonth, v))
}

// PriceYearEQ applies the EQ predicate on the "price_year" field.
func PriceYearEQ(v int64) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldPriceYear, v))
}

// PriceYearNEQ applies the NEQ predicate on the "price_year" field.
func PriceYearNEQ(v int64) predicate.Plan {
	return predicate.Plan(sql.FieldNEQ(FieldPriceYear, v))
}

// PriceYearIn applies the In predicate on the "price_year" field.
func PriceYearIn(vs ...int64) predicate.Plan {
	return predicate.Plan(sql.FieldIn(FieldPriceYear, vs...))
}

// PriceYearNotIn applies the NotIn predicate on the "price_year" field.
func PriceYearNotIn(vs ...int64) predicate.Plan {
	return predicate.Plan(sql.FieldNotIn(FieldPriceYear, vs...))
}

// PriceYearGT applies the GT predicate on the "price_year" field.
func PriceYearGT(v int64) predicate.Plan {
	return predicate.Plan(sql.FieldGT(FieldPriceYear, v))
}

// PriceYearGTE applies the GTE predicate on the "price_year" field.
func PriceYearGTE(v int64) predicate.Plan {
	return predicate.Plan(sql.FieldGTE(FieldPriceYear, v))
}

// PriceYearLT applies the LT predicate on the "price_year" field.
func PriceYearLT(v int64) predicate.Plan {
	return predicate.Plan(sql.FieldLT(FieldPriceYear, v))
}

// PriceYearLTE applies the LTE predicate on the "price_year" field.
func PriceYearLTE(v int64) predicate.Plan {
	return predicate.Plan(sql.FieldLTE(FieldPriceYear, v))
}

// DailyTokenQuotaEQ applies the EQ predicate on the "daily_token_quota" field.
func DailyTokenQuotaEQ(v int64) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldDailyTokenQuota, v))
}

// DailyTokenQuotaNEQ applies the NEQ predicate on the "daily_token_quota" field.
func DailyTokenQuotaNEQ(v int64) predicate.Plan {
	return predicate.Plan(sql.FieldNEQ(FieldDailyTokenQuota, v))
}

// DailyTokenQuotaIn applies the In predicate on the "daily_token_quota" field.
func DailyTokenQuotaIn(vs ...int64) predicate.Plan {
	return predicate.Plan(sql.FieldIn(FieldDailyTokenQuota, vs...))
}

// DailyTokenQuotaNotIn applies the NotIn predicate on the "daily_token_quota" field.
func DailyTokenQuotaNotIn(vs ...int64) predicate.Plan {
	return predicate.Plan(sql.FieldNotIn(FieldDailyTokenQuota, vs...))
}

// DailyTokenQuotaGT applies the GT predicate on the "daily_token_quota" field.
func DailyTokenQuotaGT(v int64) predicate.Plan {
	return predicate.Plan(sql.FieldGT(FieldDailyTokenQuota, v))
}

// DailyTokenQuotaGTE applies the GTE predicate on the "daily_token_quota" field.
func DailyTokenQuotaGTE(v int64) predicate.Plan {
	return predicate.Plan(sql.FieldGTE(FieldDailyTokenQuota, v))
}

// DailyTokenQuotaLT applies the LT predicate on the "daily_token_quota" field.
func DailyTokenQuotaLT(v int64) predicate.Plan {
	return predicate.Plan(sql.FieldLT(FieldDailyTokenQuota, v))
}

// DailyTokenQuotaLTE applies the LTE predicate on the "daily_token_quota" field.
func DailyTokenQuotaLTE(v int64) predicate.Plan {
	return predicate.Plan(sql.FieldLTE(FieldDailyTokenQuota, v))
}

// WeeklyTokenQuotaEQ applies the EQ predicate on the "weekly_token_quota" field.
func WeeklyTokenQuotaEQ(v int64) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldWeeklyTokenQuota, v))
}

// WeeklyTokenQuotaNEQ applies the NEQ predicate on the "weekly_token_quota" field.
func WeeklyTokenQuotaNEQ(v int64) predicate.Plan {
	return predicate.Plan(sql.FieldNEQ(FieldWeeklyTokenQuota, v))
}

// WeeklyTokenQuotaIn applies the In predicate on the "weekly_token_quota" field.
func WeeklyTokenQuotaIn(vs ...int64) predicate.Plan {
	return predicate.Plan(sql.FieldIn(FieldWeeklyTokenQuota, vs...))
}

// WeeklyTokenQuotaNotIn applies the NotIn predicate on the "weekly_token_quota" field.
func WeeklyTokenQuotaNotIn(vs ...int64) predicate.Plan {
	return predicate.Plan(sql.FieldNotIn(FieldWeeklyTokenQuota, vs...))
}

// WeeklyTokenQuotaGT applies the GT predicate on the "weekly_token_quota" field.
func WeeklyTokenQuotaGT(v int64) predicate.Plan {
	return predicate.Plan(sql.FieldGT(FieldWeeklyTokenQuota, v))
}

// WeeklyTokenQuotaGTE applies the GTE predicate on the "weekly_token_quota" field.
func WeeklyTokenQuotaGTE(v int64) predicate.Plan {
	return predicate.Plan(sql.FieldGTE(FieldWeeklyTokenQuota, v))
}

// WeeklyTokenQuotaLT applies the LT predicate on the "weekly_token_quota" field.
func WeeklyTokenQuotaLT(v int64) predicate.Plan {
	return predicate.Plan(sql.FieldLT(FieldWeeklyTokenQuota, v))
}

// WeeklyTokenQuotaLTE applies the LTE predicate on the "weekly_token_quota" field.
func WeeklyTokenQuotaLTE(v int64) predicate.Plan {
	return predicate.Plan(sql.FieldLTE(FieldWeeklyTokenQuota, v))
}

// MonthlyTokenQuotaEQ applies the EQ predicate on the "monthly_token_quota" field.
func MonthlyTokenQuotaEQ(v int64) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldMonthlyTokenQuota, v))
}

// MonthlyTokenQuotaNEQ applies the NEQ predicate on the "monthly_token_quota" field.
func MonthlyTokenQuotaNEQ(v int64) predicate.Plan {
	return predicate.Plan(sql.FieldNEQ(FieldMonthlyTokenQuota, v))
}

// MonthlyTokenQuotaIn applies the In predicate on the "monthly_token_quota" field.
func MonthlyTokenQuotaIn(vs ...int64) predicate.Plan {
	return predicate.Plan(sql.FieldIn(FieldMonthlyTokenQuota, vs...))
}

// MonthlyTokenQuotaNotIn applies the NotIn predicate on the "monthly_token_quota" field.
func MonthlyTokenQuotaNotIn(vs ...int64) predicate.Plan {
	return predicate.Plan(sql.FieldNotIn(FieldMonthlyTokenQuota, vs...))
}

// MonthlyTokenQuotaGT applies the GT predicate on the "monthly_token_quota" field.
func MonthlyTokenQuotaGT(v int64) predicate.Plan {
	return predicate.Plan(sql.FieldGT(FieldMonthlyTokenQuota, v))
}

// MonthlyTokenQuotaGTE applies the GTE predicate on the "monthly_token_quota" field.
func MonthlyTokenQuotaGTE(v int64) predicate.Plan {
	return predicate.Plan(sql.FieldGTE(FieldMonthlyTokenQuota, v))
}

// MonthlyTokenQuotaLT applies the LT predicate on the "monthly_token_quota" field.
func MonthlyTokenQuotaLT(v int64) predicate.Plan {
	return predicate.Plan(sql.FieldLT(FieldMonthlyTokenQuota, v))
}

// MonthlyTokenQuotaLTE applies the LTE predicate on the "monthly_token_quota" field.
func MonthlyTokenQuotaLTE(v int64) predicate.Plan {
	return predicate.Plan(sql.FieldLTE(FieldMonthlyTokenQuota, v))
}

// MonthlyCreditsEQ applies the EQ predicate on the "monthly_credits" field.
func MonthlyCreditsEQ(v int64) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldMonthlyCredits, v))
}

// MonthlyCreditsNEQ applies the NEQ predicate on the "monthly_credits" field.
func MonthlyCreditsNEQ(v int64) predicate.Plan {
	return predicate.Plan(sql.FieldNEQ(FieldMonthlyCredits, v))
}

// MonthlyCreditsIn applies the In predicate on the "monthly_credits" field.
func MonthlyCreditsIn(vs ...int64) predicate.Plan {
	return predicate.Plan(sql.FieldIn(FieldMonthlyCredits, vs...))
}

// MonthlyCreditsNotIn applies the NotIn predicate on the "monthly_credits" field.
func MonthlyCreditsNotIn(vs ...int64) predicate.Plan {
	return predicate.Plan(sql.FieldNotIn(FieldMonthlyCredits, vs...))
}

// MonthlyCreditsGT applies the GT predicate on the "monthly_credits" field.
func MonthlyCreditsGT(v int64) predicate.Plan {
	return predicate.Plan(sql.FieldGT(FieldMonthlyCredits, v))
}

// MonthlyCreditsGTE applies the GTE predicate on the "monthly_credits" field.
func MonthlyCreditsGTE(v int64) predicate.Plan {
	return predicate.Plan(sql.FieldGTE(FieldMonthlyCredits, v))
}

// MonthlyCreditsLT applies the LT predicate on the "monthly_credits" field.
func MonthlyCreditsLT(v int64) predicate.Plan {
	return predicate.Plan(sql.FieldLT(FieldMonthlyCredits, v))
}

// MonthlyCreditsLTE applies the LTE predicate on the "monthly_credits" field.
func MonthlyCreditsLTE(v int64) predicate.Plan {
	return predicate.Plan(sql.FieldLTE(FieldMonthlyCredits, v))
}

// BasicTokenQuotaEQ applies the EQ predicate on the "basic_token_quota" field.
func BasicTokenQuotaEQ(v int64) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldBasicTokenQuota, v))
}

// BasicTokenQuotaNEQ applies the NEQ predicate on the "basic_token_quota" field.
func BasicTokenQuotaNEQ(v int64) predicate.Plan {
	return predicate.Plan(sql.FieldNEQ(FieldBasicTokenQuota, v))
}

// BasicTokenQuotaIn applies the In predicate on the "basic_token_quota" field.
func BasicTokenQuotaIn(vs ...int64) predicate.Plan {
	return predicate.Plan(sql.FieldIn(FieldBasicTokenQuota, vs...))
}

// BasicTokenQuotaNotIn applies the NotIn predicate on the "basic_token_quota" field.
func BasicTokenQuotaNotIn(vs ...int64) predicate.Plan {
	return predicate.Plan(sql.FieldNotIn(FieldBasicTokenQuota, vs...))
}

// BasicTokenQuotaGT applies the GT predicate on the "basic_token_quota" field.
func BasicTokenQuotaGT(v int64) predicate.Plan {
	return predicate.Plan(sql.FieldGT(FieldBasicTokenQuota, v))
}

// BasicTokenQuotaGTE applies the GTE predicate on the "basic_token_quota" field.
func BasicTokenQuotaGTE(v int64) predicate.Plan {
	return predicate.Plan(sql.FieldGTE(FieldBasicTokenQuota, v))
}

// BasicTokenQuotaLT applies the LT predicate on the "basic_token_quota" field.
func BasicTokenQuotaLT(v int64) predicate.Plan {
	return predicate.Plan(sql.FieldLT(FieldBasicTokenQuota, v))
}

// BasicTokenQuotaLTE applies the LTE predicate on the "basic_token_quota" field.
func BasicTokenQuotaLTE(v int64) predicate.Plan {
	return predicate.Plan(sql.FieldLTE(FieldBasicTokenQuota, v))
}

// ProTokenQuotaEQ applies the EQ predicate on the "pro_token_quota" field.
func ProTokenQuotaEQ(v int64) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldProTokenQuota, v))
}

// ProTokenQuotaNEQ applies the NEQ predicate on the "pro_token_quota" field.
func ProTokenQuotaNEQ(v int64) predicate.Plan {
	return predicate.Plan(sql.FieldNEQ(FieldProTokenQuota, v))
}

// ProTokenQuotaIn applies the In predicate on the "pro_token_quota" field.
func ProTokenQuotaIn(vs ...int64) predicate.Plan {
	return predicate.Plan(sql.FieldIn(FieldProTokenQuota, vs...))
}

// ProTokenQuotaNotIn applies the NotIn predicate on the "pro_token_quota" field.
func ProTokenQuotaNotIn(vs ...int64) predicate.Plan {
	return predicate.Plan(sql.FieldNotIn(FieldProTokenQuota, vs...))
}

// ProTokenQuotaGT applies the GT predicate on the "pro_token_quota" field.
func ProTokenQuotaGT(v int64) predicate.Plan {
	return predicate.Plan(sql.FieldGT(FieldProTokenQuota, v))
}

// ProTokenQuotaGTE applies the GTE predicate on the "pro_token_quota" field.
func ProTokenQuotaGTE(v int64) predicate.Plan {
	return predicate.Plan(sql.FieldGTE(FieldProTokenQuota, v))
}

// ProTokenQuotaLT applies the LT predicate on the "pro_token_quota" field.
func ProTokenQuotaLT(v int64) predicate.Plan {
	return predicate.Plan(sql.FieldLT(FieldProTokenQuota, v))
}

// ProTokenQuotaLTE applies the LTE predicate on the "pro_token_quota" field.
func ProTokenQuotaLTE(v int64) predicate.Plan {
	return predicate.Plan(sql.FieldLTE(FieldProTokenQuota, v))
}

// UltraTokenQuotaEQ applies the EQ predicate on the "ultra_token_quota" field.
func UltraTokenQuotaEQ(v int64) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldUltraTokenQuota, v))
}

// UltraTokenQuotaNEQ applies the NEQ predicate on the "ultra_token_quota" field.
func UltraTokenQuotaNEQ(v int64) predicate.Plan {
	return predicate.Plan(sql.FieldNEQ(FieldUltraTokenQuota, v))
}

// UltraTokenQuotaIn applies the In predicate on the "ultra_token_quota" field.
func UltraTokenQuotaIn(vs ...int64) predicate.Plan {
	return predicate.Plan(sql.FieldIn(FieldUltraTokenQuota, vs...))
}

// UltraTokenQuotaNotIn applies the NotIn predicate on the "ultra_token_quota" field.
func UltraTokenQuotaNotIn(vs ...int64) predicate.Plan {
	return predicate.Plan(sql.FieldNotIn(FieldUltraTokenQuota, vs...))
}

// UltraTokenQuotaGT applies the GT predicate on the "ultra_token_quota" field.
func UltraTokenQuotaGT(v int64) predicate.Plan {
	return predicate.Plan(sql.FieldGT(FieldUltraTokenQuota, v))
}

// UltraTokenQuotaGTE applies the GTE predicate on the "ultra_token_quota" field.
func UltraTokenQuotaGTE(v int64) predicate.Plan {
	return predicate.Plan(sql.FieldGTE(FieldUltraTokenQuota, v))
}

// UltraTokenQuotaLT applies the LT predicate on the "ultra_token_quota" field.
func UltraTokenQuotaLT(v int64) predicate.Plan {
	return predicate.Plan(sql.FieldLT(FieldUltraTokenQuota, v))
}

// UltraTokenQuotaLTE applies the LTE predicate on the "ultra_token_quota" field.
func UltraTokenQuotaLTE(v int64) predicate.Plan {
	return predicate.Plan(sql.FieldLTE(FieldUltraTokenQuota, v))
}

// MaxConcurrencyEQ applies the EQ predicate on the "max_concurrency" field.
func MaxConcurrencyEQ(v int) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldMaxConcurrency, v))
}

// MaxConcurrencyNEQ applies the NEQ predicate on the "max_concurrency" field.
func MaxConcurrencyNEQ(v int) predicate.Plan {
	return predicate.Plan(sql.FieldNEQ(FieldMaxConcurrency, v))
}

// MaxConcurrencyIn applies the In predicate on the "max_concurrency" field.
func MaxConcurrencyIn(vs ...int) predicate.Plan {
	return predicate.Plan(sql.FieldIn(FieldMaxConcurrency, vs...))
}

// MaxConcurrencyNotIn applies the NotIn predicate on the "max_concurrency" field.
func MaxConcurrencyNotIn(vs ...int) predicate.Plan {
	return predicate.Plan(sql.FieldNotIn(FieldMaxConcurrency, vs...))
}

// MaxConcurrencyGT applies the GT predicate on the "max_concurrency" field.
func MaxConcurrencyGT(v int) predicate.Plan {
	return predicate.Plan(sql.FieldGT(FieldMaxConcurrency, v))
}

// MaxConcurrencyGTE applies the GTE predicate on the "max_concurrency" field.
func MaxConcurrencyGTE(v int) predicate.Plan {
	return predicate.Plan(sql.FieldGTE(FieldMaxConcurrency, v))
}

// MaxConcurrencyLT applies the LT predicate on the "max_concurrency" field.
func MaxConcurrencyLT(v int) predicate.Plan {
	return predicate.Plan(sql.FieldLT(FieldMaxConcurrency, v))
}

// MaxConcurrencyLTE applies the LTE predicate on the "max_concurrency" field.
func MaxConcurrencyLTE(v int) predicate.Plan {
	return predicate.Plan(sql.FieldLTE(FieldMaxConcurrency, v))
}

// FeaturesIsNil applies the IsNil predicate on the "features" field.
func FeaturesIsNil() predicate.Plan {
	return predicate.Plan(sql.FieldIsNull(FieldFeatures))
}

// FeaturesNotNil applies the NotNil predicate on the "features" field.
func FeaturesNotNil() predicate.Plan {
	return predicate.Plan(sql.FieldNotNull(FieldFeatures))
}

// IsDefaultEQ applies the EQ predicate on the "is_default" field.
func IsDefaultEQ(v bool) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldIsDefault, v))
}

// IsDefaultNEQ applies the NEQ predicate on the "is_default" field.
func IsDefaultNEQ(v bool) predicate.Plan {
	return predicate.Plan(sql.FieldNEQ(FieldIsDefault, v))
}

// IsActiveEQ applies the EQ predicate on the "is_active" field.
func IsActiveEQ(v bool) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldIsActive, v))
}

// IsActiveNEQ applies the NEQ predicate on the "is_active" field.
func IsActiveNEQ(v bool) predicate.Plan {
	return predicate.Plan(sql.FieldNEQ(FieldIsActive, v))
}

// SortOrderEQ applies the EQ predicate on the "sort_order" field.
func SortOrderEQ(v int) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldSortOrder, v))
}

// SortOrderNEQ applies the NEQ predicate on the "sort_order" field.
func SortOrderNEQ(v int) predicate.Plan {
	return predicate.Plan(sql.FieldNEQ(FieldSortOrder, v))
}

// SortOrderIn applies the In predicate on the "sort_order" field.
func SortOrderIn(vs ...int) predicate.Plan {
	return predicate.Plan(sql.FieldIn(FieldSortOrder, vs...))
}

// SortOrderNotIn applies the NotIn predicate on the "sort_order" field.
func SortOrderNotIn(vs ...int) predicate.Plan {
	return predicate.Plan(sql.FieldNotIn(FieldSortOrder, vs...))
}

// SortOrderGT applies the GT predicate on the "sort_order" field.
func SortOrderGT(v int) predicate.Plan {
	return predicate.Plan(sql.FieldGT(FieldSortOrder, v))
}

// SortOrderGTE applies the GTE predicate on the "sort_order" field.
func SortOrderGTE(v int) predicate.Plan {
	return predicate.Plan(sql.FieldGTE(FieldSortOrder, v))
}

// SortOrderLT applies the LT predicate on the "sort_order" field.
func SortOrderLT(v int) predicate.Plan {
	return predicate.Plan(sql.FieldLT(FieldSortOrder, v))
}

// SortOrderLTE applies the LTE predicate on the "sort_order" field.
func SortOrderLTE(v int) predicate.Plan {
	return predicate.Plan(sql.FieldLTE(FieldSortOrder, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Plan {
	return predicate.Plan(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasSubscriptions applies the HasEdge predicate on the "subscriptions" edge.
func HasSubscriptions() predicate.Plan {
	return predicate.Plan(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, SubscriptionsTable, SubscriptionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSubscriptionsWith applies the HasEdge predicate on the "subscriptions" edge with a given conditions (other predicates).
func HasSubscriptionsWith(preds ...predicate.UserSubscription) predicate.Plan {
	return predicate.Plan(func(s *sql.Selector) {
		step := newSubscriptionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Plan) predicate.Plan {
	return predicate.Plan(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Plan) predicate.Plan {
	return predicate.Plan(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Plan) predicate.Plan {
	return predicate.Plan(sql.NotPredicates(p))
}
